### ISSUE TITLE
keep system folders

### ISSUE THREAD

**Issue by aosucas499** [pieroproietti/penguins-eggs-legacy#101]
Hi my friend!

I'm updating a new iso of educaandos plus (guadalinex plus). In the first iso I did with the help of your amazing tool was great and very succesfull. 

I need to keep a system folder and a system file from my system that penguin eggs doesn't keep when create the ISO.

"/var/log/cga-update-manager/" --> folder
/var/log/cga-update-manager/cga-updater.log ---> file

I took a look at the file [exclude.list](https://github.com/aosucas499/guadalinex/blob/ead0db25760cfe5b1a43028aa0bd8aaec9dc034c/isobuilder/eggs/exclude.list#L65) but it's not there so I don't understand why it's not in the final ISO.

Are there any way to include a "include.list" file or a post-script? 
In the past I solve with this [code](https://github.com/aosucas499/guadalinex/blob/ead0db25760cfe5b1a43028aa0bd8aaec9dc034c/src/apps-educaandos#L48) but I would like that the installer keeps the file and folder.

Thank you so much and congratulations for your amazing work.

**Comment by pieroproietti** [comment]
Hi aosucas,

have good time my friend. From time to time I'm watching what you're doing and I'm very happy for your success with the past edition: EducaAndOs is a wonderful idea!

Looking to exclude.list, there is:
```
# remove everithing with the exceptions: 
# apache2, clamav, pveprozy, samba, mysql
var/log/!(apache2|clamav|pveproxy|samba|mysql|))
```
I suppose who change the line with:
```
# remove everithing with the exceptions: 
# apache2, clamav, pveprozy, samba, mysql and cga-update-manager
var/log/!(apache2|clamav|pveproxy|samba|mysql|cga-update-manager))
```
can solve your first question. 

To save something in the user home, the second part of the question, we can find an idea, I have to look better your code, tomorrow. 

Did you need this patch in the current eggs version (9.x  amd_64) or for eggs 8.x (i386) or both?

**Comment by pieroproietti** [comment]
I'm installing your EducandOS to check better... As I see you switched to amd64 too, so I think you can successfully use eggs 9.0.2 and following.

I saw you made a calamares theme too, if you want I can include it in the next version, so you can produce with your theme just with: ```sudo eggs produce --theme educandos``` 

I want to try the new eggs in your system, but unfortunately don't let me to install eggs. I suppose it depend on educandos repos and, perhaps this ```cga-update-manager ```

**Comment by pieroproietti** [comment]
Ok, I add a moment ```deb http://security.ubuntu.com/ubuntu focal-security main``` in ```/etc/apt/sources.list``` and was able to use last version of eggs. 
Now we will see that to do for the other

**Comment by aosucas499** [comment]
> Hi aosucas,
> 
> have good time my friend. From time to time I'm watching what you're doing and I'm very happy for your success with the past edition: EducaAndOs is a wonderful idea!
> 
> Looking to exclude.list, there is:
> ```
> # remove everithing with the exceptions: 
> # apache2, clamav, pveprozy, samba, mysql
> var/log/!(apache2|clamav|pveproxy|samba|mysql|))
> ```
> I suppose who change the line with:
> ```
> # remove everithing with the exceptions: 
> # apache2, clamav, pveprozy, samba, mysql and cga-update-manager
> var/log/!(apache2|clamav|pveproxy|samba|mysql|cga-update-manager))
> ```
> can solve your first question. 
> 
> To save something in the user home, the second part of the question, we can find an idea, I have to look better your code, tomorrow. 
> 
> Did you need this patch in the current eggs version (9.x  amd_64) or for eggs 8.x (i386) or both?
> 
> 
> 
> 
> 

Great!!!! I'll solve with that, I didn't understand the code inside exclude.list, my italian is horrible jaja

**Comment by aosucas499** [comment]
> I'm installing your EducandOS to check better... As I see you switched to amd64 too, so I think you can successfully eggs 9.0.2 and following.
> 
> I saw you made a calamares theme too, if you want I can include it in the next version, so you can produce with your theme just with: ```sudo eggs produce --theme educandos``` 
> 
> I want to try the new eggs in your system, but unfortunately don't let me to install eggs. I suppose it depend on educandos repos and, perhaps this ```cga-update-manager ```
> 
> 

Yes, he point is my version of educaandos is not the official. Teachers use my version because the official of the government doesn't have root account or user with admin privileges. But anyway I tried to let the official system with all I can without touching. For that is you see my code for penguin eggs, first i add the repo of Ubuntu and when i install the dependencies the script delete again the ubuntu repo. 

I tried the new version 9 but with the folders I copied the files was unsuccessful so I used  the old version. It could be great for this new iso the nre version and if you make me a theme that copy all I need it would be fantastic!!

**Comment by pieroproietti** [comment]
Great!!! I was just playing with your system I saw you have internal repo who I can reach from here... I don't understood everything, expecially why I have the host called pc101-61, sound like last ip numer plus last net number 192.168.61.101 + '-' + 61. 

For theme and others. we can try... let me to see a bit the situation.

**Comment by aosucas499** [comment]
> Great!!! I was just playing with your system I saw you have internal repo who I can reach from here... I don't understood everything, expecially why I have the host called pc101-61, sound like last ip numer plus last net number 192.168.61.101 + '-' + 61. 

I don't know right now, normally when I used the live and I install, it changes but I don't remember well, probably was something I didn't change well in penguin eggs or it's something internal from the internal nets from the government and the official system. Anyway thousands of teacher install and the net goes well

**Comment by pieroproietti** [comment]
OK aosuscas,

I just put on line the version 9.0.3 with your theme educaandos. For the other question, I dit not changed ```exclude.list``` it is universal and I must to think to the others too. 

If you can make a fork of penguins-eggs you can do that you want, and clean a bit your theme too, I saw there are old images you don't use and perhaps you can build it better, find more images and so on.

Did you need again your old guadalinex theme? 

Have nice time

**Comment by aosucas499** [comment]
Thank you! it worked with exclude.list, I have to improve my Italian. 

When I'll have time i'll check using the theme and I will modify to let the theme perfect (i'm very busy at school now with covid and children, but i'll do to have ready for the feature)

Thank you so much my friend.
