### ISSUE TITLE
Trying to produce an egg of Pop_OS getting error :(

### ISSUE THREAD

**Issue by greatdesign** [pieroproietti/penguins-eggs-legacy#108]
Hi Piero. I am trying to produce an egg from Pop_OS and after run the command: `sudo eggs dad` 
I am getting this error:
```
eggs >>> Using preesixent yolk....
eggs >>> Creating egg in /home/eggs/ovarium/.
systemd
eggs >>> Cannot find initrd=EFI/Pop_OS-f97ee1ec-fc78-4da6-aa14-e0d6c490e7da/initrd.img.
eggs >>> Try to edit /etc/penguins-eggs.d/eggs.yaml and check for.
eggs >>> vmlinuz: initrd=EFI/Pop_OS-f97ee1ec-fc78-4da6-aa14-e0d6c490e7da/initrd.img.
```

I double checked the eggs.yaml file and is OK. Also i checked if the folder **Pop_OS-f97ee1ec-fc78-4da6-aa14-e0d6c490e7da** exists under boot/efi/EFI/ and is there! 

Why is this happens?

**Comment by pieroproietti** [comment]
can you give this two commands:

```sudo eggs dad --default```
```eggs info```

and send the result.

btw: your initrd path start with EFI/... sure it's right?
