### ISSUE TITLE
No Internet connection after installing with Calamares

### ISSUE THREAD

**Issue by psinagra** [pieroproietti/penguins-eggs-legacy#122]
Hello! The creation of the iso of my custom Ubuntu Jammy with Cinnamon desktop was a success. The installation was a success. 
However, after the system is finally installed, I have no connections at all. I cannot update my system. I cannot run synaptic. I cannot run sudo apt update. Firefox does not reach any page at all. They all seem to be having an issue with connectivity. 

Network Manager says I have a connection, but again I can't use firefox either. Only reason I mention this is because on the original system everything works. It's after installing with calamares that nothing works. 

Aside from this small thing, eggs is great!!! Please help if possible. Thanks!

**Comment by psinagra** [comment]
To be clear, I am installing and running this new system in a virtual machine using VMWare.

**Comment by pieroproietti** [comment]
Hi Psinagra


at the moment i don't know why there is this problem, but you can do this workaround:

```
sudo rm /etc/resolv.conf

sudo ln -s usr/lib/systemd/resolv.conf /etc/resolv.conf
```


If you or me discover a better solution, please share.

**Comment by psinagra** [comment]
Pierproietti,

I figured out the problem. The file stub-resolv.conf in /run/systemd/resolv needed to be linked to the file resolv.conf in /etc.
Once this was done, it was immediately fixed after a restart. Thank you again for your help! It works perfectly now!

**Comment by pieroproietti** [comment]
We need to understand that to change in calamares configurations files to to that.

**Comment by psinagra** [comment]
It was strange. In my original system, the two files I mentioned above were linked. 
But on the new system created with eggs, the file was not linked and it was completely empty. Somehow, the file was unlinked and completely made blank during the creation process. The file I am talking about is /etc/resolv.conf
I made a script for my system however where the link will be re-established during each start-up. I made the script a service. This should keep the file from being erased, even after the system has been remastered with eggs. 
Overall however, eggs is a wonderful tool. It is exactly what I need! So thank you again for your efforts!

**Comment by pieroproietti** [comment]
I think we solved this problem, in two different ways... I'm just checking the result of an Ubuntu jammy made with eggs-9.1.17 and the result is good!

![colibri-ubuntu-jammy](https://user-images.githubusercontent.com/958613/167435966-9a3f3f7e-dd3b-42c8-acad-1017abc0d75d.png)

Now calamares generate a correct /etc/resolv.conf

I meet the solution adapting my old calamares configuration taking from [Lubuntu](https://github.com/lubuntu-team/calamares-settings-ubuntu)

**Comment by psinagra** [comment]
Thank you again! I will try the newest version of eggs and see if it works!

**Comment by pieroproietti** [comment]
Hi Psinagra

at the moment i don't know why there is this problem, but you can do this
workaround:

sudo rm /etc/resolv.conf
sudo ln -s usr/lib/systemd/resolv.conf /etc/resolv.conf



From the man of systemd-resolv

•A static file /usr/lib/systemd/resolv.conf is provided that lists the
127.0.0.53 DNS stub (see above) as only DNS server. This file may be
symlinked from /etc/resolv.conf in order to connect all local clients that
bypass local DNS APIs to *systemd-resolved*. This mode of operation is
recommended.



Il dom 8 mag 2022, 21:53 psinagra ***@***.***> ha scritto:
