### ISSUE TITLE
No key available with this passphrase

### ISSUE THREAD

**Issue by theoneandonly-vector** [pieroproietti/penguins-eggs-legacy#126]
I run this command:
```
sudo eggs produce -b -n --basename myISO
```
the idea is to create an ISO which automatically installs a copy of my current setup, I don't need no live-setup.

after some time it asks me for a passphrase and I just enter something so I get:
```
No key available with this passphrase
```

I think I'm missing a step or something..

**Comment by theoneandonly-vector** [comment]
or in other words..

what's the easiest way to create an installable ISO which includes all data and doesn't add any live-system?
->
I have a system with XFCE in Kiosk mode which somehow isn't compatible with the live-system stuff as there is no real Desktop

**Comment by theoneandonly-vector** [comment]
so I really don't need to encrypt anything and just want to create a 1:1 restore of the system on another system

**Comment by pieroproietti** [comment]
Unfortunately I decided to encrypt it and let you just to restore the datas from a crypted file to not let user to share the iso with all personal datas. 

You can take your destop configuration, just before to create iso put:
```sudo eggs tools skel```

and this will copy your XFCE configuration, but again not data.

This is an intended feathure - but as always - it's possible same workaroud, for example move your home under /opt, in that case just create iso without backup option and your data under /opt will be copied too.

**Comment by theoneandonly-vector** [comment]
but how can I do this with the intended way? I think it should ask for my passphrase when I set it up from the iso and then auto-copy the users-settings to the install right?
but how to set it up then? I can enter whatever passphrase I want and always get "No key available with this passphrase" sop do I need to prepare something first? or maybe you can add an additional parameter which skips this step? as I'm coming from "Systemback" where I was able to do what I want how I want (but sadly it's (the most used fork of it) not compatible to restore on many hardware options)

**Comment by theoneandonly-vector** [comment]
or maybe you can help me move all homes to /opt?

**Comment by pieroproietti** [comment]
You can make a test, without use a lot of data to not be bored waiting long the iso build. 
Just:

```
sudo mkdir /opt/home
sudo cp /home/myuser /opt/home -R
sudo eggs produce --fast 
```

**Comment by pieroproietti** [comment]
# The intended way

> but how can I do this with the intended way? I think it should ask for my passphrase when I set it up from the iso and then auto-copy the users-settings to the install right?
Yes, it work just in this way if you reinstall the iso with krill. krill it is a CLI installer inside eggs, very easy to use.

> but how to set it up then? I can enter whatever passphrase I want and always get "No key available with this passphrase" sop do I need to prepare something first?
When you run: 
```
eggs produce --backup --fast 
```
eggs before produce the filesystem.squashfs - without private datas - and after ask:

```
...
eggs >>> Creating an encrypted file /tmp/luks-eggs-backup blocks=5271180, block size: 1024, size: 5.03GB.
eggs >>> Enter a large string of random text below to setup the pre-encryption.
cryptsetup -y -v --type luks2 luksFormat  /tmp/luks-eggs-backup

WARNING!
========
Ciò sovrascriverà i dati in /tmp/luks-eggs-backup in modo irreversibile.

Are you sure? (Type 'yes' in capital letters): YES
Inserire la passphrase per /tmp/luks-eggs-backup:
```
here you must decide your passphrase and confirm it.
![backup2](https://user-images.githubusercontent.com/958613/171221246-be67c12c-21a7-4493-9510-3238f4434534.png)
After eggs, will open the LUKS volume and ask again the passphase. Simply put it again
![backup3](https://user-images.githubusercontent.com/958613/171221549-e709425f-53bd-4a0e-84ea-12c4b5d55137.png)

When finished use the iso to install your system, but install it with krill not with calamares.
Open a terminal and:
```
sudo eggs install --cli
```
krill will format your destination disk and after completed the copy of filesystem.squashfs will ask again about your passphrase. introduce it and it will restore all your users data and account.

If I understood well your question, this is the way.

**Comment by theoneandonly-vector** [comment]
I just move the homes to /opt/home
and then tried to do the restore using:
```
sudo eggs install --cli
```
but I ge:
```Command failed with code "1"```

when reaching just 1%

**Comment by theoneandonly-vector** [comment]
there's no option to just skip the live-setup stuff and let it install directly automatically?

**Comment by pieroproietti** [comment]
Can you let me to access your system via anydesk?

**Comment by theoneandonly-vector** [comment]
hey there, sure, we can do this tmr if that works for you, sadly I'm not able to access the computer anymore today.
which system do you mean, the live-one I try to install or the original I create the ISO from?

**Comment by pieroproietti** [comment]
We can start just with https://meet.jit.si/PenguinsEggsMeeting I'm waiting you 

OK, I think you probably are busy or unable to connect at the moment. Anyway, to backup and restore your system with eggs it's easy enoght, just follow the indication I gave you before. 

Forgot to move home in same other position, I told this just as workaroung, without understand really your problem.

Simply install eggs, don't install calamares, you don't need and creare a backup:

```
sudo eggs produce --fast --backup
```
Will be requested you to enter a passphrase and to confirm it.
After that you must insert the SAME passphrase again to open the LUKS volume.

Of course, you need sufficient free space on the disk, for filesystem compressed and your data encrypted.

When finish, put the iso in a USB key and try to restore in another CLEAN machine.

To restore symply open a terminal and give:
```
sudo eggs install --cli
```
After the installation finish, krill will ask you for passphrase, put the same passphrase you decided before and will restore your datas.

**Comment by theoneandonly-vector** [comment]
as I said I can only do this tomorrow, is 09:30 GMT+2 ok?

**Comment by pieroproietti** [comment]
I'm in timezone Europe/Rome, you can contact me with [telegram](https://telegram.me/PieroProietti) or via mail: piero.proietti@gmail.com to advise.
