### ISSUE TITLE
Usermod Installation Error

### ISSUE THREAD

**Issue by aaprice** [pieroproietti/penguins-eggs-legacy#127]
Hello!, first of all thank you for making such a great tool for the community! 

Recently I have been working on a distribution of ubuntu linux for security tools and training. I went through the process using dad and the normal sudo eggs produce --release. Using VMware I can succesfully run a live instance of my distro. When I try to install, however, it goes through the process and then throws an error relating to usermod( picture below). If you have any ideas what may be happening here I would greatly appreciate the help. Thank you for your time. Also, I'm not sure if this is related but when I try to run the .iso with Virtual Box it won't even load in the live format, it throws a kernel panic error and gets stuck. 
![image](https://user-images.githubusercontent.com/48139036/172934477-5190994f-656b-4bf9-9cf0-43582dd1b02f.png)

**Comment by pieroproietti** [comment]
Hi aaprice,

I had that error too, it not deoend on virtualvox or vmware, I m using proxmox ve (kvm). If Im not wrong it happen in jammy for same reason, this morning I was testing with limuxmint 20.3, Linux mint vanessa beta and an ubuntu jammy with xfce. I don't r'emember if I correct or bypassed it...

**Comment by pieroproietti** [comment]
I clos

**Comment by aaprice** [comment]
Thank you for your response. I'm using xubuntu 20.04, focal fossa, which uses xcfe4 i think, do you think this is an issue with the xfce4 as desktop environment?

**Comment by pieroproietti** [comment]
No, it must to work I started with that.
This morning I make same adjustments in eggs to try to solve this problem, changing /etc/calamares/modules/users.conf and /etc/calamares/modules/unpacking.conf, but I was not able to install with calamares too. 
At that point I installed it with internal krill installer: ```sudo eggs install -cli``` and the operation go well, now I'm making a new iso to see if the problem arise again or it's solved.
The strange is who the version of colibri in jammy install nicelly.

Anyway, if you have time, you can use one of the versions of colibri to help to solve the problem. I make colibri in varius versions and consists in a live installable with calamares, "dressed" with xfce4 and tools to develop with typescript. 
Install it, and:
* ```git clone https://github.com/pieroproietti/penguins-eggs```
* ```cd penguins-eggs```
* ```pnpm i```
At this point you can make your changes in penguins-eggs, and use it directly from the directory ```penguins-eggs``` or build a new deb version with ```pnpm build```.

Nothing to do... now I'm getting this error
![Screenshot](https://user-images.githubusercontent.com/958613/173008398-05ccf901-2e17-4624-ae4b-50cc2be69485.png)

From where it receive the order to mount cdrom? 

But I must to leave...

**Comment by pieroproietti** [comment]
Well at last...

![Screenshot](https://user-images.githubusercontent.com/958613/173042138-777c47f7-c123-4268-923a-1f7f38bcb9f6.png)

I can't assure all is working... but in some ways it worked, produced a eggs-of-ubuntu-focal-colibri (XFCE4) and I suppose will work -  but not have time now to test - in ubuntu 22.04 jammy too.

The previus problem who arise wad depending on local repository yolk, I create a little local repository to let to user install without connections, alway worked as I configurated it, strange enought now in focal don't take shim-signed, I simply added it in /src/classes/yolk.ts.

I put for you eggs-9.1.30_amd64.deb on [testing](https://sourceforge.net/projects/penguins-eggs/files/packages-deb/testing/), you can test it.

**Comment by aaprice** [comment]
Thank you again. I will get to testing that this weekend, my day today is a little full so I might not be able to until tomorrow
