### ISSUE TITLE
Blackscreen after Installation and Shutdown

### ISSUE THREAD

**Issue by ibuntuos** [pieroproietti/penguins-eggs-legacy#131]
Hello,

I am using V 9.1.32 and tested also with 9.1.34 and I remastered a Version of Ubuntu 18.04.6.
The system comes up normally, only getting stuck for unknown reasons at "dev-getty.device" daemon until timeout. I could live with that but still strange. 
Than I install the system with calamares - it runs through normally. 
But when I than want to shut it down for the first boot I get a Blackscreen and it is stuck. Once I got error messages, saying 

`SQUASHFS error: Unable to read fragment`

![image](https://user-images.githubusercontent.com/68012153/177053822-b62f9057-1c7d-424b-a39e-4633f5188ae6.png)

The only "solution" i have than is to Power Off the machine by hand. After that the installed system comes up normally and also shut down is working well than.

I think it might have something to do with the way the ISO is generated - I coded a simple Builder myself last year, which faced a lot of other problems, penguins-eggs now has solved for me, but at least it booted fast and after an installation the system went down without a hangup.

Could you please try to verify the issue with a Ubuntu 18.04.6 Version and see what is the root cause for this behaviour?

Best Regards and thanks for your great tool which keeps the possibility of remastering your system alive

**Comment by pieroproietti** [comment]
I rewote the anwser here, with mail don't work markdown.

**Comment by pieroproietti** [comment]
It's long time I'm following new distros and versions and forgot old ones, like bionic. 

As soon I will have time I'll will re-test it and probably will solve your problems.

Nice to hear you did something similar, as I understood: a tools to remaster! 

You can also try to hack eggs to find and solve: your problem.

You need a Debian or ubuntu installation,  nodejs >= 16.x, pnpm, git and
vscode. I did same configurated live called colibri on Debian and Ubuntu focal -
you can find on penguins-eggs page of sourceforge. 

But probably for your case, it's better install the tools in your system. The only "strange" thing is pnpm: you can simply install using 

```sudo npm i pnpm -g```

At this point, clone penguings-eggs with the command:

```git clone https://github.com/pieroproietti/penguins-eggs```

```cd penguins-eggs```

```pnpn i```

and you can use eggs by the script ./eggs in the same directory.

Example:

```sudo ./eggs dad -d```

```sudo ./eggs cakamares --install```

```sudo ./eggs produce --fast```

Explain all the sources in a mail it's too long, just consider the main point of eggs is the class ovary.ts where happen the magic.

**Comment by pieroproietti** [comment]
This morning I'm trying to replicate it:
* installed a ubuntu-18.04-desktop
* install nodejs 16, from nodesource (v18 have lacks some library), git, vscode, pnpm 
* clone https://github.com/pieroproietti/penguins-eggs
* cd penguins-eggs
* pnpm -i
* pnpm build
* dpkg -i perrisbrewery/workdir/eggs_9.1.34_amd64.deb
* sudo apt install -f
* sudo eggs dad -d
* sudo eggs calamars --install
* sudo eggs produce --fast

After the live was ready, I boot another VM with it and:
* wait on boot for getty-device, after that it started correctly
* At this point I try to install with calamares clicking on the desktop link, calamares don't start
* started calamares opening a Terminal and: sudo calamares -d, installation was correct
* I had to reset the VM to restart it when the installation finished
* testing the resulting VM was OK

**Comment by pieroproietti** [comment]
I will upload resulting live on [penguins-eggs/file/iso/ubuntu/bionic](https://sourceforge.net/projects/penguins-eggs/files/iso/ubuntu/bionic/), it's complete with eggs and you can experiment.

file: egg-of-ubuntu-bionic-colibri-amd64_2022-07-04_0728.iso 2GB (compression max)

You can also clone my repo and make your tests with sources, note: nodejs, pnpn, vscode and git are already installed.

Kernel was updated at linux-image-5.4.0-121-generic,

Just a note: I made an apt full-upgrade and removed original kernel. The system always ask if I want to upgrade the version, but I refused.

**Comment by pieroproietti** [comment]
To get the job a more complete, I remastered the naked version of bionic too against eggs 9.1.34. As always I updated everything and removed old kernels to reduce the size.

You can find the resulting iso on the same place,

file: 
* egg-of-ubuntu-bionic-naked-amd64_2022-07-04_0759.iso 874M (compression fast)
* egg-of-ubuntu-bionic-naked-amd64_2022-07-04_0919.iso 582M (compression max)

Note: I discovered who the installation with krill (without calamares) need grub-pc package, I installed it and rebuild the naked iso.

**Comment by pieroproietti** [comment]
I was not satisfacted again and want to try wardrobe too, so on the new installed naked:

```eggs wardrobe get```

```eggs wardrobe wear colibri```

And I get my preferreted configuration, with XFCE4 and tools for developer.

You can get an idea of wardrobe from the README of the repo: https://github.com/pieroproietti/penguins-wardrobe
![bionic-colibri](https://user-images.githubusercontent.com/958613/177092983-1b32bb04-dbe6-4c56-bc00-8c71768bded2.png)

The only problem I get was change to change the desktop wallpaper!!!

**Comment by pieroproietti** [comment]
The new colibri version, based on LXDE it's named:

egg-of-ubuntu-bionic-colibri-amd64_2022-07-04_0824.iso 1,7G (compression fast)

And you can find it under [sourceforge, project penguins, file, iso, ubuntu, bionic](https://sourceforge.net/projects/penguins-eggs/files/iso/ubuntu/bionic/)

Note: this iso is little than the previous one, and I used just --fast as compression. That is really usefull during tests.

![bionic-colibri-install](https://user-images.githubusercontent.com/958613/177095360-68fc3581-b293-4f1a-947e-73d6560eb688.png)

**Comment by pieroproietti** [comment]
Well, really I don't solve your problem, did't touch it at all. But I hope I give you enought curiosity and an entrance, to try find the solution in your own and, possibly, collaborate in this project.

Saluti, Piero

**Comment by ibuntuos** [comment]
Good Morning,

First thanks for your effort in analysing this issue.

From what I hear this issue is only occuring on 18.04 and not on newer versions of Ubuntu which would be a good thing. I just still have this old System I still want to maintain until Ubuntus EOL of 18.04 in April 2023. And by experimenting and analysing I get a deeper understanding of how the remastering of a system works which is a lot of fun - at least if in the end everything is working as expected :-) 


For the non-starting Calamares i found out that the Exec-Statement in the install-debian.desktop file need to be changed to 

`Exec=sh -c "pkexec /usr/bin/calamares"`

With that the installer starts propperly. Maybe penguines-eggs is excluding something in the process of gathering the files for the filesqashfs . My own builder (which is a very rusty mesh-up between the original remastersys script and the adapted script the tool "bodhibuilder" used) has other issues which is why I can't use it anymore. But interstingly it produces way bigger ISO-Files, means it doesn't exclude that much. And these ISOs are at least booting and shutting down without issues. 

Maybe I will try to reduce the excludes in the excludes.list for testing purposes. If this does the trick than I can slightly take back the excludes until it will fail again, than I know what not has to be excluded for bionic. 
Long try and error process well - I will keep you informed maybe the result can also help for further development.

Thanks and please keep up the great work, your tool seems to be the only remaining remastering-tool out there.

**Comment by pieroproietti** [comment]
I hope to continue and improve penguins-eggs... but there is need of a community too.

Well, God know, that will happen in future, at the moment I insert your suggestion on debian-install script: a little step but I not noticed that. Thanks!

```Exec=sh -c "pkexec /usr/bin/calamares"```

**Comment by ibuntuos** [comment]
One question I still have, I managed to fix the "getty-device" by changing the mksquashfs command to the one I used with my own builder in the past. The issue that the live cd will hang up on shutdown after install is still there.
But what I know figured out was, that the installer creates an own /etc/default/grub file and therefore an own /boot/grub/grub.cfg where the "splash" command is missing. I tried to modify the /usr/share/calamares/modules/grubfg.conf and the settings.conf of calamares before install, to force calamares to overwrite the default command from "quiet" to "quiet splash" but it didn't took effect.

Did you manage to create remastered isos where the installed system than showed the splash bootscreen?

**Comment by pieroproietti** [comment]
Nice for the adjustment in mksquashfs, the problem is boring and it happen in buster too. 

Are you speacking for the live or installed system? I don't touch it at all, and usually the system is installed as was in the janitor.

**Comment by ibuntuos** [comment]
The only difference I do is, I don't use wildcards now for the mksuqashfs, my command looks like this now:

![image](https://user-images.githubusercontent.com/68012153/177574763-0f2540d1-1c59-41e5-9168-3203d6a0d185.png)

With this the getty-device.service doesn't hang anymore during booting.

Also I found a solution for the missing splash screen in live-system now.

So it's more or less again just the issue with the SQUASHFS-Errors which prevents the Live-System from shutting down after installation.

**Comment by pieroproietti** [comment]
i will try your adjustments in a whiile...  just the time to go down on the garage... here is summer and 35°C so I wait until 5:00 pm before to go.

**Comment by pieroproietti** [comment]
No, I removed -wildcards, but I can't confirm.
![Screenshot](https://user-images.githubusercontent.com/958613/177590639-aa5c0a8a-ac8c-4e51-a34c-20bd77f3122c.png)

and from [tldp](https://tldp.org/HOWTO/html_single/SquashFS-HOWTO/):

 ```-wildcards``` enable the extended shell wildcards to exclude directories/files **(to be used with -e)** 

we are using -e to exclude files. But yes, I'm not using wildcards inside the command, so probably it's the same, but at least for my bionic the situation remain the same.

```mksquashfs /home/eggs/ovarium/filesystem.squashfs /home/eggs/ovarium/iso/live/filesystem.squashfs -comp lz4 -ef /usr/local/share/penguins-eggs/exclude.list -e 'boot/efi/EFI' 'etc/fstab' 'etc/mtab' 'etc/udev/rules.d/70-persistent-cd.rules' 'etc/udev/rules.d/70-persistent-net.rules' 'etc/rc0.dK01cryptdisks' 'etc/rc0.dK01cryptdisks-early' 'etc/rc6.dK01cryptdisks' 'etc/rc6.dK01cryptdisks-early' 'etc/rcS.dS01cryptdisks' 'etc/rcS.dS01cryptdisks-early' 'home/eggs/' ```

**Comment by pieroproietti** [comment]
I confirm to have the same problems removing -wildcards and adding your exclusion, I tryed this too:

```
mksquashfs /home/eggs/ovarium/filesystem.squashfs /home/eggs/ovarium/iso/live/filesystem.squashfs -comp lz4 -ef /usr/local/share/penguins-eggs/exclude.list -e '/root' '/boot/efi/EFI' '/boot/grub' '/etc/fstab' '/etc/mtab' '/etc/udev/rules.d/70-persistent-cd.rules' '/etc/udev/rules.d/70-persistent-net.rules' '/swapfile' '/etc/rc0.dK01cryptdisks' '/etc/rc0.dK01cryptdisks-early' '/etc/rc6.dK01cryptdisks' '/etc/rc6.dK01cryptdisks-early' '/etc/rcS.dS01cryptdisks' '/etc/rcS.dS01cryptdisks-early' '/home/eggs/' 
```

**Comment by pieroproietti** [comment]
Well, after that experiments I restart to investigate on the problem and refresh ```excludes.list``` from refractasnapshot-base. This seem to correct the problem  "getty-device" at boot time of live.

You can test the result installing eggs-9.1.35

**Comment by ibuntuos** [comment]
So it basically was not the "wildcard" expression itself but just too many excludes maybe. 
In the meantime I figured out a nice workaround for the "SQUASHFS" Situation by creating a "Hard Reboot" Application which basically emits Alt+SysReq+B and force the system to shut off instantly and reboot. With a bootscript I than correct the missing "splash" argument in the default grub and with another, now "normal" reboot of the new installation, the "Hard Reboot" will be deleted again since I only need it for rebooting instantly after the installation is finished. 
Rough and dirty but it works :-D 

I definitely will install and use eggs 9.1.35 as soon as I was able to create my first stable ISO within almost two years thanks to your program 👍

**Comment by pieroproietti** [comment]
Well, I'm proud of it! :-)

I saw your distro, it is interesting and very well maintained. From my point of view, however is too large, perhaps it would be appropriate to unbundle it, removing the lesser used packages, and give to the users the possibility to install them after.

In any case, you can see that a great deal of work has been done.

**Comment by ibuntuos** [comment]
Well, I always want to reduce the iso-size of the distrubution but the question is than on what packages are to be removed and which not, this is one of our goals, to at least stay below 5 GB in size, i know that's still way more than most distros have but since we also bundle a lot of features and pre-configs within it, this creates a lot of dependencies - with KDE even more.

So far thanks to your software we are now out of the tale of tears we were stuck in for so long and can bring back our project back to life and that's just great - let me know on how I could thank you for that :-)
