### ISSUE TITLE
Edit content just before ISO creation?

### ISSUE THREAD

**Issue by kalligator** [pieroproietti/penguins-eggs-legacy#132]
Is there a way to pause the procedure just before the ISO packaging stage so as to edit the content in the meantime e.g. to add system-wide theme & icons, add a backup of a few .dotfiles etc, then resume the procedure?

**Comment by pieroproietti** [comment]
You can use the produce flag --scripts

The iso will be not created, but just scripts for it's creations. 

You will have in /home/eggs/ovarium the follows scripts:

* bind
* mksquashfs
* mkiso
* ubind

They can used in sequence, to mount the filesystem binded in /home/eggs/ovarium/filesystem.squashfs, create squashed fs in /home/eggs/ovarium/iso/live/filesystem.squashfs, create the iso and umount filesystemfs.

PS: this scripts are always generated - also without the flag --scripts, the diference is just they are not executed - so they can always used to edit the content of the iso.

**Comment by kalligator** [comment]
I'll probably find a way to mess it up hehehe. 
I think a flag like dad -p (pause) would be safer for idiots like me. If you find it worthy perhaps you can implement something like that in the future?

**Comment by pieroproietti** [comment]
If you need just to change just iso, edit the contents in /home/eggs/ovarium/iso.

There are 4 folders:
* boot
* efi
* isolinux
* live

in boot you can change same parameters for grub in the live, example splash.png, theme.cfg all related to grub for iso;

the same in isolinux, but for isolinux live,

And just run mkiso when you finish your configuration.
