### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/home/eggs/ovarium/filesystem.squashfs/etc/sddm.conf.d/autologin.conf'

### ISSUE THREAD

**Issue by allanlaal** [pieroproietti/penguins-eggs-legacy#155]
penguins-eggs       Perri's Brewery edition        ver. 9.2.6       
command: produce --fast

**Comment by pieroproietti** [comment]
Hi Allan,

I'm just rewriting the routines for autologin, this errors is caused becouse I try to see where autologin is configurated, and on the distros I used was in /etc/sddm.conf or /etc/sddm.conf.d/autologin.conf.

You just can ```sudo touch /etc/sddm.conf.d/autologin.conf``` as momentary workaround before I fix it.

Thanx for the advice Allan

**Comment by pieroproietti** [comment]
OK, just finished [bugfix](https://github.com/pieroproietti/penguins-eggs/commit/2610c1c4dcde22fa2ba58a07aff7e9ef41116267), and uploaded new version [eggs-9.2.7](https://sourceforge.net/projects/penguins-eggs/files/DEBS/)

## From changelog
### eggs-9.2.7
install:
* added flag --domain to pass domain for unattended installation, eg: ```sudo eggs install unrd penguins-eggs.net```
* added flag --none create a minimun swap partition of 256M
* rewrote routines autologin for sddm and lightdm.

Note: to have autologin on the live your current used MUST to be configured with autologin.
