### ISSUE TITLE
Fail with Internet connection 

### ISSUE THREAD

**Issue by aosucas499** [pieroproietti/penguins-eggs-legacy#167]
Hi friend.
Some users, sometimes, when they install my system [educandos+](https://github.com/aosucas499/guadalinex) (eggs 7.8.39), have the fail of this image. (It's related to yolk)
![IMG_20221107_194843_502](https://user-images.githubusercontent.com/72696244/200391174-f4e867fa-e062-4683-ae87-44cc1df0e35e.jpg)
 
This problem is solved if they disconnect the networks. What can I fix this when I made the iso?
Thanks!

**Comment by pieroproietti** [comment]
Can you use something more recent or there are problems?

In all the way yolk is just a local repository for the packages need for bootloader, i put in grub and grub-efi and related dipendencies.

Now I'm on telephone, tomorrow i will check better.

Have great time,

Piero



On recent version i can adapt

Il lun 7 nov 2022, 19:55 aosucas499 ***@***.***> ha scritto:

**Comment by aosucas499** [comment]
Yes, I tried the new version you told me [here](https://github.com/aosucas499/guadalinex/issues/34), but it had a los of problems to install. I supossed it was because I used ubuntu focal and your new versions need dependencies from ubuntu 22.

ok, when you can.

Thamk you so much.

**Comment by aosucas499** [comment]
Not dependencies sorry, problems with my old files to adapt in eggs 9.x. from 7.x. These days I'm going to try to make a theme for the system and try to use eggs 9.x and cuckoo, hoping it will solve the problems of yolk. Thank you.

**Comment by pieroproietti** [comment]
I'm just installing your EducaAndOS-plus-x64_2022-10-23.iso, 

I installed on it eggs-9.3.7 just adding the original focal /etc/apt/sources.list, after that I removed the addiction.

```
deb http://it.archive.ubuntu.com/ubuntu/ jammy main universe restricted multiverse
deb-src http://it.archive.ubuntu.com/ubuntu/ jammy main universe restricted multiverse

deb http://security.ubuntu.com/ubuntu jammy-security main universe restricted multiverse
deb-src http://security.ubuntu.com/ubuntu jammy-security main universe restricted multiverse

deb http://it.archive.ubuntu.com/ubuntu/ jammy-updates main universe restricted multiverse
deb-src http://it.archive.ubuntu.com/ubuntu/ jammy-updates main universe restricted multiverse
```

There was not problems installing eggs - just added same packages using ```apt install -f```,  but the system became unstable after I tried to install ```grub-efi-amd64-bin``` and not boot.

After indaging, I saw who was installed another kernel linux-image-5.0.14-131-generic, and to restore all, I boot with the old kernel and give an: ```dpkg --configure -a```

![educandos-prob1](https://user-images.githubusercontent.com/958613/200761276-f1847495-582b-49e3-b137-3d13b8766163.png)

But the system remain unstable and I can't boot.

Now I'm leaving to work, but in the afternoon I will try again, if your are free  we cab do this together.

**Comment by pieroproietti** [comment]
https://t.me/penguins_eggs

**Comment by aosucas499** [comment]
Thanks for the investigation.

Yes , two kernels from the official version. I try to don't touch a lot from the official so when the changes something like packages don't result into problems.
I'm going to try to do the iso again with your new version of eggs but I need time to make a theme for eggs. ASAP I'll do and I'll give you feedback here or in your Telegram group. Thank you so much for your work and time.

**Comment by pieroproietti** [comment]
There is again the old theme included in eggs, just use theme=educandos

**Comment by aosucas499** [comment]
Great! I didn't see in the new version

**Comment by pieroproietti** [comment]
You are right, I think I deleted it for same reasons... but we can take it from an old version and put in the new. Anyway I'm trying again your system, now I will try to use less possible ubuntu repository - to change less possible - and see that happen.

**Comment by aosucas499** [comment]
Don't worry for the theme, I'll do again with some changes and after I send you so you can include.
This is the [script/commands](https://github.com/aosucas499/guadalinex/blob/main/isobuilder/eggs/eggs-install%2B.sh) I use to generate Iso (eggs 7.x)

**Comment by pieroproietti** [comment]
You mean I must install a clean ubuntu focal and apply your script? Please, can you call me via whatapp or telegram?  https://t.me/penguins_eggs

**Comment by aosucas499** [comment]
Noooo, I modify my system in VirtualBox, and with these commands I made the ISO. Sorry, I'm in meetings from the job today, I'll give you feedback as soon I made a new ISO with eggs 9.x.

**Comment by pieroproietti** [comment]
OK, perfect. See you soon

**Comment by aosucas499** [comment]
I get a few time to make a theme in a [testing branch](https://github.com/aosucas499/guadalinex/tree/eggs-9.x/isobuilder/eggs) and in VM install eggs 9.3.7. In this folder are the eggs.yaml, eggs-install+.sh...
All is OK but when I enter eggs mom or eggs status give me mistakes about a dependencies probably, [here](https://github.com/aosucas499/guadalinex/raw/eggs-9.x/im%C3%A1genes/eggs-9-fail.png) is the picture.
If you tell what is the package, I could try to add in the system. Thank you

**Comment by aosucas499** [comment]
![16680232284982867794449310388272](https://user-images.githubusercontent.com/72696244/200926737-876dbf07-6e4f-48a9-a1e8-54bd5dc48eb0.jpg)

**Comment by pieroproietti** [comment]
![ubuntu-focal](https://user-images.githubusercontent.com/958613/201021772-9471f0f1-471e-4b51-b703-e1995628a96a.png)

This morning I tested again under a just installed and upgraded Ubuntu 20.04, now I will create the iso and put it on [sorceforge page of eggs](https://sourceforge.net/projects/penguins-eggs/files/ISOS/ubuntu/focal/).

I hope this can help.

**Comment by aosucas499** [comment]
After talk with you in telegram I have solved the problem of install eggs 9. Apparently I can't copy the file eggs.yaml and produce an eggs, always it's necessary to produce interactive with eggs dad. Thank you
