### ISSUE TITLE
Request: Eggs for FreeBSD?

### ISSUE THREAD

**Issue by Wamphyre** [pieroproietti/penguins-eggs-legacy#170]
Hi! First of all, thank you very much for your work making eggs, that's a really useful and amazing tool for sysadmin and distro-makers!

I'm a heavy user of FreeBSD and I was wondering if would be possible to do a "BSD-Eggs" version which could work in the very same way as penguins-eggs do (make bootable isos from full-preinstalled system).

Is this a practical and doable idea? Would be difficult to do it?

Greetings!

**Comment by pieroproietti** [comment]
Hi @Wamphyre ,

I think it is possible, as far I know there are live in BSD like FreeSBIE and others, I think  we must manage package manager and initial ram disk and use mount --bind, unionfs, squashfs who i suppose are present and equal in both the os.

 I don't know BSD at all, just installed probably FreeSBIE years ago but I think you know deeply it.

Can be really a great idea!

**Comment by pieroproietti** [comment]
Playing with a FreeBSD just installed: install bash, git, node, npm, pnpm, sudo. Problem about spice-vdagent, it seem not exists here, I need becouse I'm insidea KVM (proxmox VE) and is pratical to cut and copy, resize the windows and so on.

I started a new branch [FreeBSD](https://github.com/pieroproietti/penguins-eggs/tree/FreeBSD), and wrote same [FreeBSD notes](https://github.com/pieroproietti/penguins-eggs/blob/FreeBSD/documents/FreeBSD.md).

![basis](https://user-images.githubusercontent.com/958613/206454869-a44843d1-d607-4e1f-94dd-d8a8428f6a1d.png)

**Comment by pieroproietti** [comment]
We must to solve this:
```
#############################################################
# /var is a directory need to be presente, and rw
# -----------------------------------------------------------
# create mountpoint lower
mkdir /home/eggs/ovarium/.overlay/lowerdir/var -p
# first: mount /var rw in /home/eggs/ovarium/.overlay/lowerdir/var
mount --bind --make-slave /var /home/eggs/ovarium/.overlay/lowerdir/var
# now remount it ro
mount -o remount,bind,ro /home/eggs/ovarium/.overlay/lowerdir/var

# second: create mountpoint upper, work and /home/eggs/ovarium/filesystem.squashfs and mount var
mkdir /home/eggs/ovarium/.overlay/upperdir/var -p
mkdir /home/eggs/ovarium/.overlay/workdir/var -p
mkdir /home/eggs/ovarium/filesystem.squashfs/var -p

# thirth: mount /var rw in /home/eggs/ovarium/filesystem.squashfs
mount -t overlay overlay -o lowerdir=/home/eggs/ovarium/.overlay/lowerdir/var,upperdir=/home/eggs/ovarium/.overlay/upperdir/var,workdir=/home/eggs/ovarium/.overlay/workdir/var /home/eggs/ovarium/filesystem.squashfs/var
```

**Comment by OpenOS-Project-Creator-Founder** [comment]
I will suggest using RavynOS as a possible target Distro of FreeBSD for Eggs 🥚. 

http://github.com/ravynsoft/ravynos

**Comment by OpenOS-Project-Creator-Founder** [comment]
> Playing with a FreeBSD just installed: install bash, git, node, npm, pnpm, sudo. Problem about spice-vdagent, it seem not exists here, I need becouse I'm insidea KVM (proxmox VE) and is pratical to cut and copy, resize the windows and so on.
> 
> I started a new branch [FreeBSD](https://github.com/pieroproietti/penguins-eggs/tree/FreeBSD), and wrote same [FreeBSD notes](https://github.com/pieroproietti/penguins-eggs/blob/FreeBSD/documents/FreeBSD.md).
> 
> ![basis](https://user-images.githubusercontent.com/958613/206454869-a44843d1-d607-4e1f-94dd-d8a8428f6a1d.png)
> 

https://freebsd.kde.org/

**Comment by pieroproietti** [comment]
I think we must find the most easy possible solution, after to get something usable we can always extend to others distros. 

As I understood FreeBSD and GhostBSD are the most diffused. 

I read same days ago about a way to create a livecd from FreeBSD manuals but actually can't find it again, I'm wrong?

Materials I found:
* https://wiki.freebsd.org/AndriyGapon/AvgLiveCD
* https://forums.freebsd.org/threads/installing-freebsd-manually-no-installer.63201/

On installed FreeBSD we have:
* da0% da0p1% da0p2% da0p3% 

```
gpart create -s gpt /dev/da0
gpart add -t freebsd-boot -s 128k -l boot da0p1
gpart add -t freebsd-zfs -l system da0p2
mkdir /tmp/zfs
zpool create -m / -R /tmp/zfs zroot da0p2
zpool set bootfs=zroot zroot

# mkdir /tmp/zfs/usr
# zfs create zroot/home

# zfs create -o mountpoint=/usr/ports -o compression=on -o setuid=off zroot/ports
# zfs create -o compression=off -o exec=off -o setuid=off zroot/ports/distfiles
# zfs create -o compression=off -o exec=off -o setuid=off zroot/ports/packages

# zfs create -o mountpoint=/usr/local zroot/local
# zfs create -o mountpoint=/usr/src -o compression=on zroot/src
# zfs create -o mountpoint=/usr/doc -o compression=on zroot/doc

# zfs create zroot/var
# zfs create -o exec=off -o setuid=off zroot/var/db
# zfs create -o compression=on -o exec=on -o setuid=off zroot/var/db/pkg
# zfs create -o compression=on -o exec=off -o setuid=off zroot/var/mail
# zfs create -o compression=on -o exec=off -o setuid=off zroot/var/log
# zfs create -o exec=off -o setuid=off zroot/var/run
# zfs create -o exec=off -o setuid=off zroot/var/tmp
# zfs create -o exec=off -o setuid=off zroot/tmp
# chmod 1777 /tmp/zfs/tmp /tmp/zfs/var/tmp

# zfs create zroot/opt
# zfs create -o refquota=250M zroot/opt/jails

zfs create -V 4G zroot/swap

cd /tmp/zfs
tar xvJf /usr/freebsd-dist/base.txz
tar xvJf /usr/freebsd-dist/kernel.txz
tar xvJf /usr/freebsd-dist/lib32.txz

gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i 1 da0p2

# cd /mnt/zfs/boot
# echo 'zfs_load="YES"' > loader.conf
# echo 'vfs.root.mountfrom="zfs:zroot"' >> loader.conf
# echo 'zfs_enable="YES"' > ../etc/rc.conf

# Finally reboot
shutdown -r now
```

**Comment by pieroproietti** [comment]
It was a nice idea... but too long :-1:
