### ISSUE TITLE
 How to change the images of the installer ?

### ISSUE THREAD

**Issue by cdelpierre1** [pieroproietti/penguins-eggs-legacy#187]
I would like to know the configuration file of the installer in order to change the images that run in a loop during the final installation.
Thank you in advance for your help!

**Comment by pieroproietti** [comment]
Hi Pierre,

You can change the eggs theme or use others, if you clone yourself [penguins-wardrobe](https://github.com/pieroproietti/penguins-wardrobe), under the themes folder you will find some examples.
All you have to do is copy one and modify it as you want, so to use it, let's say you named it pierre, just start production with the --theme parameter /path/to/pierre.

Example:

```
sudo eggs produce --theme ./pierre
```

**Comment by pieroproietti** [comment]
The themes allow customization of calamares and the ability to have its own splashscreen during liveCD booting.

Both the startup of the live and the appearance of [calamares](https://calamares.io/) is configurable. Get a look [here](https://github.com/calamares/calamares/blob/calamares/src/branding/README.md) from calamares.

You can create a custom theme by simply copying an existing one and changing its name and content.
