### ISSUE TITLE
[Manjaro Talos] Error "distro not yet recognized" and typo

### ISSUE THREAD

**Issue by SHA-NDY** [pieroproietti/penguins-eggs-legacy#217]
The distro "Manjaro/Talos" is not yet recognized. I had a look into the yaml file but didn't find an example for Manjaro to copy from.
There's a typo in the path to the yaml file: "../conf/derivaties.yaml" should be corrected to "../conf/derivatives.yaml".

Thanks for your work!

![image](https://user-images.githubusercontent.com/67801045/229200870-9a9c2233-8675-43f4-83b0-45cae2e1c031.png)

**Comment by pieroproietti** [comment]
I updated  eggs today for manjaro, probably tomorrow Will be on, if not you can use the follow PKGBUILD

https://github.com/pieroproietti/penguins-eggs-pkgbuilds/blob/master/manjaro/PKGBUILD

**Comment by SHA-NDY** [comment]
Thank you
