### ISSUE TITLE
[Manjaro Talos] Error when booting LiveISO

### ISSUE THREAD

**Issue by SHA-NDY** [pieroproietti/penguins-eggs-legacy#219]
When I boot the created ISO (with user data in this case) I get the following error.

![IMG_20230401_183655_312_1.jpg](https://user-images.githubusercontent.com/67801045/229303471-a12173bd-3974-4947-b674-31ed5d96ac23.jpg)

What does that mean? Can I do anything about it?

**Comment by pieroproietti** [comment]
To be honest from this I can't understand the reason. 

Try to post the commands You used, distro version and so on ... thanks.

Ops, it was on the title... :-)

**Comment by pieroproietti** [comment]
I just repeat your experiment creating this image egg-of-manjarolinux-talos-kde_clone_amd64_2023-04-02_1203.iso

![manjaro-clone](https://user-images.githubusercontent.com/958613/229346473-828e7419-3a19-4293-8153-70bc5401caff.png)

The result was normal

![manjaro-cloned](https://user-images.githubusercontent.com/958613/229346618-7092ca46-60ce-403d-bac2-410593616f69.png)

I used just a VM:
```
cores: 2
ide2: zfs-dir:iso/archlinux-2023.04.01-x86_64.iso,media=cdrom,size=828748K
memory: 4096
meta: creation-qemu=7.2.0,ctime=1679583374
name: arch
net0: virtio=42:BF:6C:2B:D8:0A,bridge=vmbr0,firewall=1
numa: 0
ostype: l26
scsi0: local-lvm:vm-110-disk-0,iothread=1,size=8G
scsihw: virtio-scsi-single
smbios1: uuid=862cf146-b3e4-40e3-9bbb-1c99689903fc
sockets: 2
vga: qxl
vmgenid: 176e97de-c82f-4697-8688-7df575defedecores: 2
ide2: zfs-dir:iso/archlinux-2023.04.01-x86_64.iso,media=cdrom,size=828748K
memory: 4096
meta: creation-qemu=7.2.0,ctime=1679583374
name: arch
net0: virtio=42:BF:6C:2B:D8:0A,bridge=vmbr0,firewall=1
numa: 0
ostype: l26
scsi0: local-lvm:vm-110-disk-0,iothread=1,size=8G
scsihw: virtio-scsi-single
smbios1: uuid=862cf146-b3e4-40e3-9bbb-1c99689903fc
sockets: 2
vga: qxl
vmgenid: 176e97de-c82f-4697-8688-7df575defede
cores: 2
ide2: zfs-dir:iso/archlinux-2023.04.01-x86_64.iso,media=cdrom,size=828748K
memory: 4096
meta: creation-qemu=7.2.0,ctime=1679583374
name: arch
net0: virtio=42:BF:6C:2B:D8:0A,bridge=vmbr0,firewall=1
numa: 0
ostype: l26
scsi0: local-lvm:vm-110-disk-0,iothread=1,size=8G
scsihw: virtio-scsi-single
smbios1: uuid=862cf146-b3e4-40e3-9bbb-1c99689903fc
sockets: 2
vga: qxl
vmgenid: 176e97de-c82f-4697-8688-7df575defedecores: 2
ide2: zfs-dir:iso/archlinux-2023.04.01-x86_64.iso,media=cdrom,size=828748K
memory: 4096
meta: creation-qemu=7.2.0,ctime=1679583374
name: arch
net0: virtio=42:BF:6C:2B:D8:0A,bridge=vmbr0,firewall=1
numa: 0
ostype: l26
scsi0: local-lvm:vm-110-disk-0,iothread=1,size=8G
scsihw: virtio-scsi-single
smbios1: uuid=862cf146-b3e4-40e3-9bbb-1c99689903fc
sockets: 2
vga: qxl
vmgenid: 176e97de-c82f-4697-8688-7df575defede
```
Filesystem was ext4.

I can confirm the re-installation too
![manjaro-cloned-reinstalled](https://user-images.githubusercontent.com/958613/229347186-41e8e9c0-a71f-40f1-945f-ca3462788555.png)

**Comment by SHA-NDY** [comment]
Perhaps something in my setup was screwed up. I did a fresh install now and booted the egg via Ventoy. Worked now.
Don't know what caused it, anyway, thanks for clarifying and have a nice Sunday.

I'll test installing now. I want to switch from ext4 to BTRFS.
