### ISSUE TITLE
Package Build Error

### ISSUE THREAD

**Issue by grimy192837465** [pieroproietti/penguins-eggs-legacy#223]
Hello, I am trying to install penguin-eggs. No matter if I install through Yay, Paru, or manually via git clone and makepkg, I always get the same error. I am on an Arch based distribution and do not know what is causing this. Any help or solution possible? Thanks

`==> Making package: penguins-eggs 9.4.6-1 (Fri 21 Apr 2023 19:46:30 BST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning penguins-eggs git repo...
Cloning into bare repository '/home/adamj/penguins-eggs/penguins-eggs'...
remote: Enumerating objects: 39324, done.
remote: Counting objects: 100% (1377/1377), done.
remote: Compressing objects: 100% (526/526), done.
remote: Total 39324 (delta 785), reused 1294 (delta 711), pack-reused 37947
Receiving objects: 100% (39324/39324), 290.65 MiB | 1.64 MiB/s, done.
Resolving deltas: 100% (25629/25629), done.
==> Validating source files with sha256sums...
    penguins-eggs ... Skipped
==> Extracting sources...
  -> Creating working copy of penguins-eggs git repo...
Cloning into 'penguins-eggs'...
done.
Switched to a new branch 'makepkg'
==> Starting pkgver()...
==> Starting build()...
/home/adamj/penguins-eggs/PKGBUILD: line 34: pnpm: command not found
==> ERROR: A failure occurred in build().
    Aborting...`

**Comment by grimy192837465** [comment]
Seems it's because I don't have pnpm. Is there no mention of installing this as a dependency on the installation instructions?

**Comment by pieroproietti** [comment]
Hi Grimy,

Just need to have pnpm installed, unfortunately on AUR non always pnpm is aligned with the official release, so I went back to install it with npm.

Its was my fault, in this version I removed `pnpm` from dependencies  and put `npm` on dependencies, but at last I forgot to restore/add the follow line to install it:

```
sudo npm i pnpm -g
```

**Comment by pieroproietti** [comment]
Now Arch is OK
