### ISSUE TITLE
Alpine support

### ISSUE THREAD

**Issue by ghost** [pieroproietti/penguins-eggs-legacy#230]
This project would be nice. But it's missing Alpine support.

**Comment by pieroproietti** [comment]
To be honest I know really few or nothing about Alpine, but from start I tried to be as much universal was possible.

The biggest part of eggs production is at last to create the compressed filesystem.squashfs and this is generic enought;
* we have building initrd.img for Debian / Devuan / Ubuntu, or initramfs on Arch and derivates;
* we lacks initramfs for Fedora and others... 

If someone want to help, I think can be possible.

**Comment by pieroproietti** [comment]
![alpine-eggs](https://github.com/pieroproietti/penguins-eggs/assets/958613/d2f1c247-ae7f-4da7-98d5-946fce785a40)

I think its not impossibile to address penguins-eggs to alpine... This morning just played a bit and here we are... 

![playing-with-alpine](https://github.com/pieroproietti/penguins-eggs/assets/958613/7bb98ac4-ff26-44c9-8306-664b180f7e94)
