### ISSUE TITLE
Exclude.list not working

### ISSUE THREAD

**Issue by Rockets31** [pieroproietti/penguins-eggs-legacy#231]
Hi,
I am running encrypted linuxmint-21.1 on btrfs filesystem and using also swapfile. Swapfile 4GB needs its own subvolume, which is mount under folder "/swap".  I added "/swap" to "/usr/local/share/penguins-eggs/exclude.list" but It is added to the ISO (~8GB) instead. It seems the exclude.list is not  observed for building the squashfs (?!)

**Comment by pieroproietti** [comment]
Hi Rockets, 

yes, you are right and at the moment, I can't understand where arise the problem!

This exclude file, exists from the time of refracta-snapshot, so was always included in eggs, and always used to exclude files.

Syntax is quite simple:
```
# Exclude some system files. These are required, shouldn't be changed.
- /dev/*
- /cdrom/*
```
We must investigate.
```
eggs >>> squashing filesystem: -comp zstd -b 256K -Xcompression-level 1.
mksquashfs /home/eggs/ovarium/filesystem.squashfs /home/eggs/ovarium/iso/live/filesystem.squashfs -comp zstd -b 256K -Xcompression-level 1 -wildcards -ef /usr/local/share/penguins-eggs/exclude.list -e 'boot/efi/EFI' 'etc/fstab' 'etc/mtab' 'etc/udev/rules.d/70-persistent-cd.rules' 'etc/udev/rules.d/70-persistent-net.rules' 'etc/rc0.dK01cryptdisks' 'etc/rc0.dK01cryptdisks-early' 'etc/rc6.dK01cryptdisks' 'etc/rc6.dK01cryptdisks-early' 'etc/rcS.dS01cryptdisks' 'etc/rcS.dS01cryptdisks-early' 'home/eggs/' 
```

**Comment by pieroproietti** [comment]
depends on the fact that the syntax used in exclude.list is for rsync, but I no longer copy the filesystem simply mount it --bind, so it is completely irrelevant.

I had never noticed this problem, also because in truth I use this characteristic very little, now that you have pointed it out to me, let's try to put a patch on it.

**Comment by Rockets31** [comment]
I understand, if this exclude.list is only referred to rsync which isn't used anymore... Instead of that the feature excluding files & directories is useful for controlling Image size and content. I think implementing this is a good tweak.

**Comment by pieroproietti** [comment]
Yes, is really usefull: crucial in same cases, a must to have! 

For now I just removed everything, but I need to reimplement it, same advises?

**Comment by Rockets31** [comment]
I didn't look deeper Into building workflow. I assumed 'mksquashfs' processes 'excluding.list' while building squashfs. 'Eggs' cleans up user directory so this function could be helpful(?!)

**Comment by pieroproietti** [comment]
OK, i fixed it!

Please, try the new eggs-v9.4.10 on [testing](https://sourceforge.net/projects/penguins-eggs/files/DEBS/testing/).

I completely changed the exclude.list file I restarted from an old version on refracta and changed it from rsync to mksquashfs. 

It seems that now the exclusions are working, of course some break-in and testing needs to be done.

Get a look to the new [exclude.list](https://github.com/pieroproietti/penguins-eggs/blob/master/conf/exclude.list).

**Comment by pieroproietti** [comment]
OK, I just released eggs v9.4.10, so you just need to update eggs and put your exclusions on the the new exclude.list.

**Comment by pieroproietti** [comment]
https://penguins--eggs-net.translate.goog/blog/sulla-strada-sospeso-a-meta?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp&_x_tr_hist=true

**Comment by Rockets31** [comment]
Small change big impact! My last iso-built shrank about half of its size... So I had to test installing it via calamares on external usb-c-ssd plugged in my described linux mint system (luks-encrypted). I tested btrfs-unencrypted & btrfs-encrypted installations, which were very smooth without errors. The system-restart.
First, I booted brtfs-unencrypted, which told me luks-partition sucessfully opened, but the uuid was from its "parent-system" of the internal-ssd -> this means initramfs wasn't updated after installation and also for producing the live-iso before. The original luks-keyfile & crypttab resides still in the initramfs, so it is probably a copy of the original.
While booting: error ~ "failed re-mount rw -> system in ro" -> graphical-DE did not start just command-line. So I removed "space_cache" mount-option from fstab and system boots into desktop. Here I checked via gnome-disk-utility that luks-partition
of the "parent-system" is really opened -> correct. I closed that luks-partition and ran "update-initramfs -uk all", reboot was without errors & not-opening luks-partition -> old keyfile & crypttab were gone. 

The encrypted-btrfs installation asked for password and then also opened automatically the "parent luks-partition" but after that it "could not find root-device" -> busybox. I chroot into encrypted-btrfs-system -> "update-initramfs -uk all" & removed "space_cache" from fstab -> reboot without errors into graphical DE.

**Comment by pieroproietti** [comment]
I didn't understand much of what you're doing, but I'm satisfied that it's working. And, that's enough for me for today!

**Comment by Rockets31** [comment]
I am sorry for my poor explanation! All in all, there is a security issue remastering encrypted systems which use a keyfile. While producing the 'squashfs' the original initramfs-images (with included keyfile) were copied 1-by-1 to the resulting iso-file. So everybody could extract the keyfile out of the iso-file.

**Comment by shah-newaz** [comment]
@pieroproietti Well, now my image creation finished within 2 minutes with just a 88MB ISO file :D The logs doesn't show anywhere that it's using the exclude list though. Of course the image doesn't work.

What could be wrong? Using ver. 9.4.10

**Comment by shah-newaz** [comment]
Also, where can I find the full log of last run? Towards the end, it seems it was trying to show some error but it very quickly disappears and says image was created successfully (egg is finished). Right after this:

![Screenshot_20230515_010941](https://github.com/pieroproietti/penguins-eggs/assets/11506530/560d69ed-d020-4f79-b315-0ae62496b504)

**Comment by pieroproietti** [comment]
Hi shah-newaz,
sorry to admit: eggs don't create a log!
well, I Hope with a little help from my friends, as Beatles, we can add...

For the reasons , i think you excluded everything i suppose 88 MB Is just vmlinuz and initrd.img

**Comment by shah-newaz** [comment]
haha! Well, here is my exclude file: @pieroproietti 

```
# I started from https://git.devuan.org/devuan/refractasnapshot-base/src/branch/master/snapshot_exclude.list
# converting it from rsync - not more used - to mksquashfs

home/*/.zsh_history
home/*/.zhistory
home/*/.git*

home/*/.kube/*
home/*/.aws/*

home/*/.config/microsoft-edge/*
home/*/.config/GitHub*/*
home/*/.config/google-chrome/*
home/*/.config/opera/*
home/*/.config/Slack/*
home/*/.zoom/*
home/*/.local/share/DBeaverData/*

home/*/.cache/JetBrains/*
home/*/.cache/Microsoft/*
home/*/.cache/microsoft-edge/*
home/*/.cache/zoom/*

home/*/apps/intelle-hub
home/*/apps/breakbio
home/*/apps/tagbot

home/*/Downloads/*
home/*/Documents/*
home/*/Pictures/*
home/*/Music/*
home/*/Videos/*

/var/lib/docker/overlay2/*
/var/lib/docker/containers/*
/var/lib/docker/tmp/*
/var/lib/docker/volumes/*


# Required: ou probably shouldn't change them.
boot/*.bak
boot/*.old-dkms
boot/grub/device.map
boot/grub/grub.cfg
boot/grub/menu.lst
cdrom/*
dev/*
etc/apt/sources.list~
etc/blkid.tab
etc/blkid.tab.old
etc/crypttab
etc/fstab
etc/fstab.d/*
etc/initramfs-tools/conf.d/cryptroot  # see remove-cryptroot and nocrypt.sh
etc/initramfs-tools/conf.d/resume     # see remove-cryptroot and nocrypt.sh
etc/mtab
etc/popularity-contest.conf
etc/ssh/ssh_host_*_key*
etc/ssh/ssh_host_key*
etc/udev/rules.d/70-persistent-cd.rules
etc/udev/rules.d/70-persistent-net.rules
home/snapshot
lib/live/image
lib/live/mount
lib/live/overlay
lib/live/rootfs
live
media/*
mnt/*
persistence.conf
proc/*
run/*
swapfile
sys/*
tmp/*
usr/lib/live/image
usr/lib/live/mount
usr/lib/live/overlay
usr/lib/live/rootfs
usr/share/icons/*/icon-theme.cache
var/backups/*.bak
var/backups/*.gz
var/cache/apt/apt-file/*
var/cache/apt/archives/*.deb
var/cache/apt/pkgcache.bin
var/cache/apt/srcpkgcache.bin
var/cache/debconf/*~old
var/lib/apt/*~
var/lib/apt/cdroms.list
var/lib/apt/lists/*
var/lib/aptitude/*.old
var/lib/dbus/machine-id
var/lib/dhcp/*
var/lib/dpkg/*~old
var/lib/live/config/*
var/mail/*
var/spool/mail/*

# root: you can exclude all 
root/.aptitude
root/.bash_history
root/.disk-manager.conf
root/.fstab.log
root/.ICEauthority
root/.lesshst
root/.local/share/*
root/.nano_history
root/.ssh
root/.synaptic
root/.VirtualBox
root/.Xauthority
root/*/.log

# home: mostly clean
home/*/.adobe
home/*/.aptitude
home/*/.bash_history
home/*/.cache
home/*/.config/hexchat
home/*/.dbus
home/*/.gksu*
home/*/.gnupg
home/*/.gvfs
home/*/.ICEauthority
home/*/.lesshst
home/*/.local/share/recently-used.xbel
home/*/.local/share/Trash/*
home/*/.log
home/*/.macromedia
home/*/.mozilla/*/Cache/*
home/*/.mozilla/*/cookies.sqlite
home/*/.mozilla/*/downloads.sqlite
home/*/.mozilla/*/formhistory.sqlite
home/*/.mozilla/*/places.sqlite
home/*/.mozilla/*/signons.sqlite
home/*/.mozilla/*/urlclassifier3.sqlite
home/*/.nano_history
home/*/.pulse*
home/*/.recently-used
home/*/.recently-used.xbel
home/*/.ssh
home/*/.thumbnails/fail/*
home/*/.thumbnails/large/*
home/*/.thumbnails/normal/*
home/*/.Trash*
home/*/.vbox*
home/*/.VirtualBox
home/*/.wine
home/*/.Xauthority
home/*/.xchat2
home/*/.xsession-errors*
home/*/VirtualBox\ VMs

# custom
.snapshots/*
swap/*
swapfile
```

**Comment by shah-newaz** [comment]
Actually, I figured out the issue by running it like this :laughing: No need for a logger (for now)!

`sudo eggs produce --clone --standard | tee /tmp/log`

The error was that the file exclusion does not support wildcards for locations starting with .. or /
So, my problematic line were:
```

/var/lib/docker/overlay2/*
/var/lib/docker/containers/*
/var/lib/docker/tmp/*
/var/lib/docker/volumes/*
```

Changed them to

```
var/lib/docker/overlay2/*
var/lib/docker/containers/*
var/lib/docker/tmp/*
var/lib/docker/volumes/*
```

And it started working

**Comment by pieroproietti** [comment]
Great!

**Comment by shah-newaz** [comment]
I think we should close this? New version seems to be working perfectly for exclusion.

**Comment by jupgithub** [comment]
Hi,
Just a comment about the exclusions file.  Some time ago I discovered that there are 2 files with that name.

Exclude list folders:
Permanent: /usr/local/share/penguins-eggs/exclude.list
Editable: /usr/lib/penguins-eggs/conf/exclude.list

I hope this can help clear some things.

**Comment by jupgithub** [comment]
> Hi, I am running encrypted linuxmint-21.1 on btrfs filesystem and using also swapfile. Swapfile 4GB needs its own subvolume, which is mount under folder "/swap". I added "/swap" to "/usr/local/share/penguins-eggs/exclude.list" but It is added to the ISO (~8GB) instead. It seems the exclude.list is not observed for building the squashfs (?!)

See my last post...

**Comment by jupgithub** [comment]
> Great!

Hi Piero,

See my last post here.

**Comment by jupgithub** [comment]
Piero clarified the reason for the two exclude.list files.

The /usr/local/share/penguins-eggs/exclude.list is the file to make changes, but when the command -
sudo eggs dad -d
is executed or when installing eggs, the system erase the custom configuration from that file, using the other
/usr/lib/penguins-eggs/conf/exclude.list
