### ISSUE TITLE
Live ISO from installed Linux Mint 21.1 shows installed users only

### ISSUE THREAD

**Issue by jupgithub** [pieroproietti/penguins-eggs-legacy#232]
Hi,
Live ISO from installed Linux Mint 21.1 shows installed users only.
No way to use user: live/evolution

And some more things, like font.pf2 not found, etc.

Thanks.

**Comment by pieroproietti** [comment]
Hi jupgithub,

looks a lot like using the --clone flag?

If not, can you please explain in more detail what commands you used?

**Comment by jupgithub** [comment]
Hi pieroproietti,
No, no flags.  I used only : eggs produce

**Comment by jupgithub** [comment]
Copied the ISO to a ventoy usb drive, and when booting it shows me my personal list of users, and not the supposed Live users:  live/evolution.  
Additional, an error for folder Desktop, not created.... (that was after I got to enter by terminal, and startx)

**Comment by pieroproietti** [comment]
I'm downloading a LinuxMint 21.1 vera to replicate... I think it will work normally but, today I changed something on the exclude.list and want to check.

`sudo dpkg -i eggs_9.4.10_amd64.deb` then `sudo apt install -f` to complete installation.

`sudo eggs calamares --install`
![calamares](https://github.com/pieroproietti/penguins-eggs/assets/958613/b07c1882-7286-4c11-9df7-de9c03f94f37)

and finally:  `sudo eggs dad -d`

Well, we can produce now!

`sudo eggs produce`
![eggs-produce](https://github.com/pieroproietti/penguins-eggs/assets/958613/69f81d4b-848b-4c93-a279-02fcbaf384ca)

Finally the image is ready
![eggs-produce-end](https://github.com/pieroproietti/penguins-eggs/assets/958613/def3779b-7a20-48d6-b169-fae816a061c3)

**Comment by pieroproietti** [comment]
I'm creating it... just installing calamares
![calamares](https://github.com/pieroproietti/penguins-eggs/assets/958613/1037bd70-fa70-4f59-a07c-7746f57a6c8d)

**Comment by pieroproietti** [comment]
Now I'm booting from the live....
![boot](https://github.com/pieroproietti/penguins-eggs/assets/958613/71be701f-16dd-4894-9788-d38f1e75370b)

OK, booted and automatically logged
![first-boot](https://github.com/pieroproietti/penguins-eggs/assets/958613/061beee1-4ce1-4d74-a71b-7073f324dfef)

Now I'm using calamares to install
![installing](https://github.com/pieroproietti/penguins-eggs/assets/958613/c786f654-133f-4414-9c45-7748a35cc826)

Here seem all regular... llnuxmint21.1 remastered with eggs-v9.4.10 

In the while the installer is making his work...
![installing](https://github.com/pieroproietti/penguins-eggs/assets/958613/e3d3db88-8710-4a2a-a836-d4937ad8bc74)

**Comment by pieroproietti** [comment]
Here seem all regular...

**Comment by pieroproietti** [comment]
You can try to replicate... 
I'm also uploading this image on sourceforge, 

the last resource is to check you iso if possible.

Piero

**Comment by jupgithub** [comment]
I did not use: "and finally: sudo eggs dad -d"
Maybe there is some complication with my installed Linux Mint 21.1.  I have years upgrading Linux Mint.
I think I added the repository, and installed it.

**Comment by jupgithub** [comment]
My system was updating the repository, and now I see a pending update for eggs, from 9.4.9 to 9.4.10.

**Comment by jupgithub** [comment]
I am going to try again with my installed system when I have time, to test a new produced egg...

**Comment by jupgithub** [comment]
I do not remember this step:
"sudo eggs calamares --install"
I think I installed calamares but without eggs in that command.  I tried your way, and some things I am seeing here...  The egg is in process.  We'll see...

**Comment by jupgithub** [comment]
Just in case this is important:

Unrecognised xattr prefix system.posix_acl_access
Unrecognised xattr prefix system.posix_acl_access
Unrecognised xattr prefix system.posix_acl_access
[============================================================================================================================================|    ] 1125772/1150564  97%
Unrecognised xattr prefix system.posix_acl_access
Unrecognised xattr prefix system.posix_acl_access
Unrecognised xattr prefix system.posix_acl_access
Unrecognised xattr prefix system.posix_acl_access
Unrecognised xattr prefix system.posix_acl_access
Unrecognised xattr prefix system.posix_acl_access

**Comment by jupgithub** [comment]
The old ISO was - 27.7 gb
This new ISO is - 27.1 gb
These are some errors that I have been capturing.

This time, I had two personal users, but less than before.
![errors_booting_egg](https://github.com/pieroproietti/penguins-eggs/assets/84473445/54f0fcfc-54bc-4e1c-ab3d-81286316f75a)

**Comment by jupgithub** [comment]
Interesting find, different behavior.

With Ventoy, it brings personal users.
With Virtualbox, no, but some issues with applets not loading, asking me to delete them.  (MATE stuff, etc).
Also, the Desktop folder is not working yet.

Just in case, this is a non-efi system.

**Comment by pieroproietti** [comment]
This is necessary: `sudo eggs dad -d`  

and:  `sudo eggs calamares --install`  too! 

While is perfectly possible to install calamares from apt, in this way calamares don't install this two packages: `qml-module-qtquick2` and `qml-module-qtquick-controls` and need of them. Again using `sudo eggs calamares --install` calamares is configured to be used without password. 

>My system was updating the repository, and now I see a pending update for eggs, from 9.4.9 to 9.4.10.

Yes, `eggs-v9.4.10`, I released just yesterday you added penguins-eggs-ppa and so You get update. it's normal.

I see your system is about 27 Gb in size, not only: you told me are not using --clone

It look really too big to be just system and applications? 

Cannot understand too much from the errors you show, but I think they are not crucial and not related at all with the problem of users.

>Interesting find, different behavior.

>With Ventoy, it brings personal users.

>With Virtualbox, no, but some issues with applets not loading, asking me to delete them. (MATE stuff, etc).

Copy the iso on Ventoy or use it directly on a VM must be perfectly the same from the point of view of eggs: we just build a live ISO of the system and - in same way - ignore the existence of Ventoy, VM and so on.

I think there are same problems I can't understand, but not related with eggs.

**Comment by jupgithub** [comment]
Hi,
Yes, yesterday I did this:
sudo eggs dad -d
sudo eggs calamares --install
(with the updated eggs)
sudo eggs produce
But I don't know why the system is bringing something from the users, but I cannot use the passwords assigned to them.
And the Desktop folder was missing, and the button for menu was missing.  I tried ALT + F2 for calling calamares and try the install, but failed.  Something is not right, but I don't know where is.  I am available to test with some additional exclusions for my system if you want, or I will wait for future updates.  I really wish this works for my system.  That is something that I look for to do. I have years upgrading from version to version and installing programs, uninstalling, etc, learning...  I don't know if there is something on my root partition out of place.  Right now I have two system in the same SSD drive.  And the second system took the grub for boot menu.  Not sure is there is something to do with boot folder or boot partition.  I upgraded recently from Linux Mint 20.3 to 21 and then 21.1 (MATE).  Long process because of my old and so much space of my system. 
Maybe there is something related to my personal users on other place, or a backup, or some program, I don't know.
I will keep trying when I can, and I accept recommendations, be for more exclusions before producing the egg, or something.

**Comment by jupgithub** [comment]
![VirtualBox_Linux Mint_13_05_2023_22_03_17](https://github.com/pieroproietti/penguins-eggs/assets/84473445/1c8d03bf-6390-4a3b-96db-1e9ada5adb16)
![VirtualBox_Linux Mint_13_05_2023_22_04_04](https://github.com/pieroproietti/penguins-eggs/assets/84473445/5313de3a-47db-4247-a305-8f3e187ab7b9)
![VirtualBox_Linux Mint_13_05_2023_22_04_25](https://github.com/pieroproietti/penguins-eggs/assets/84473445/0a4e96d5-f966-42d8-8534-05e3243e274a)
![VirtualBox_Linux Mint_13_05_2023_22_04_53](https://github.com/pieroproietti/penguins-eggs/assets/84473445/7257b6dd-a96e-4e7b-a82e-4afbb69a2fb8)
![VirtualBox_Linux Mint_13_05_2023_22_05_12](https://github.com/pieroproietti/penguins-eggs/assets/84473445/ce8e5212-b3ac-4a39-98e2-5dc612396714)
![VirtualBox_Linux Mint_13_05_2023_22_05_27](https://github.com/pieroproietti/penguins-eggs/assets/84473445/fb411e55-59ab-4538-b832-f6529b125937)
![VirtualBox_Linux Mint_13_05_2023_22_09_12](https://github.com/pieroproietti/penguins-eggs/assets/84473445/f65c5d34-225c-47f0-8838-8acd97952c46)
![VirtualBox_Linux Mint_13_05_2023_22_10_35](https://github.com/pieroproietti/penguins-eggs/assets/84473445/bd321cbb-346b-49f7-83d5-ef33b8d699cd)
Steps done:

1.  Deleted and uninstalled a pair of things (home folders or files) or trash
2.  Removed completedly calamares and reinstalled again with the command: sudo eggs calamares --install
3.  sudo eggs dad -d
4.  sudo eggs produce
5.  I used VirtualBox, and linked the storage direct to the image created by eggs. Now, I could log with live.
    The process appears to be a little better but with some errors loading some menu applets or some things. 
    I tried calamares via ALT + F2, but the installation failed.

6.  I poweroff the virtual machine.
    I took a chance with this in my system:
    mate-panel --reset --layout mint
    etc
    I took a chance with reversing or defaulting the "main menu" (mozo / alacarte)
    I lost some custom configuration on the panel... but...
7.  Restarted
8.  sudo eggs dad -d
9.  I recreated the egg
10. Repeated the # 5. Again I could log with live, but no success for the rest. (With Ventoy it brings me 1 personal user now, not live.  Clarifying that with Ventoy it is on another PC)
    I wish I could know if the produced egg is inheriting panel problems, or the customizations were not syncronized or not compatible; or it is dependent from a user data. But I can be totally wrong.

**Comment by pieroproietti** [comment]
>But I don't know why the system is bringing something from the users, but I cannot use the passwords assigned to them.

`sudo eggs produce` used without `--clone` completely exclude `/home` and its contents from the iso. Then remove, users and password from `/etc/passwd` and add an user live, the home of live is created on the first login from `/etc/skel`.

PS: perhaps give the command: `sudo eggs tools skel` can help a bit. This command simply copy the main .dotfiles on /etc/skel so they will be copied back to /home/live when you first login.

Why your system is taking users' home and not cleaning /etc/password is a mistery for me!

All the users from 1000 to 10000 are removed from function [cleanUsersAccounts()](https://github.com/pieroproietti/penguins-eggs/blob/38c0ff4c66c2a7d033abd45c3a01b6f629e776cb/src/classes/ovary.ts#L1108)

And of course nothing is copied under /home. 

Perhaps you users live in a non standard place like /opt or others?  Or maybe some link?

**Comment by jupgithub** [comment]
Good morning pieroproietti:
Updated the kernel from 5.19.0-40-generic to 6.3.2.  Deleted the others installed.
Results under other PC with Ventoy:
It brought me two personal users, the desktop folder problem, but It has the menu button.

Results under VirtualBox on this PC:
I could login with live and its password, the desktop folder problem, but missing menu button.

In general appears to be better fluidity, but I don't know what else to do right now.

I remember that some time ago, not so long, I executed a recommendation for my system.  This link tells about that interesting approach.
https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/

I followed the recommendations message from my system, and all went good.

**Comment by jupgithub** [comment]
I used this - sudo eggs tools skel , from VirtualBox, and logout using pkill -KILL -u live
And did login, and now I see some folders on the Desktop, but the Desktop folder is a file (the same problem for Desktop folder)
Inside that file (Desktop) there is:
![VirtualBox_Linux Mint_14_05_2023_11_22_20](https://github.com/pieroproietti/penguins-eggs/assets/84473445/6c3014c4-63dc-4f4b-88d2-3fe95441d128)

**Comment by jupgithub** [comment]
I logged out again (with pkill), and when login there are two more icons:  
![VirtualBox_Linux Mint_14_05_2023_11_28_29](https://github.com/pieroproietti/penguins-eggs/assets/84473445/33de36ab-8f10-4386-88b7-036769172484)

**Comment by jupgithub** [comment]
Although problems with applets not loading and Desktop folder problem, just for testing, I executed Install system, to see what would happen. I will upload the results later.

**Comment by pieroproietti** [comment]
OK, I will see you results... 

will be interesting if You can let me to connet on your system to see a bit in that consist it.

Another test you can do is simply create a new user on your old system and see that happen, at last the user live its exacly the same case.

**Comment by jupgithub** [comment]
No success:
![VirtualBox_Linux Mint_14_05_2023_12_32_06](https://github.com/pieroproietti/penguins-eggs/assets/84473445/4239362c-fc38-4aa7-af28-e8044cc6d453)

**Comment by jupgithub** [comment]
> OK, I will see you results...
> 
> will be interesting if You can let me to connet on your system to see a bit in that consist it.
> 
> Another test you can do is simply create a new user on your old system and see that happen, at last the user live its exacly the same case.

I deleted some unused folders from /opt and old grub backups on /...
Do you have Anydesk, or Teamviewer ?

**Comment by pieroproietti** [comment]
Perhaps is stupid, but there is enoght free space on the disk to unpack all the compressed filesystems?

**Comment by pieroproietti** [comment]
it's OK with anydesk, write me at piero.proietti@gmail.com

**Comment by jupgithub** [comment]
> Perhaps is stupid, but there is enoght free space on the disk to unpack all the compressed filesystems?

Not sure.... 40gb virtual size on virtualbox....

**Comment by pieroproietti** [comment]
OK, send me the request with anydesk

**Comment by pieroproietti** [comment]
Hi Luis,

for that i saw in the few moments we connet you have a system really big, I asked you to create a new user and see that happen, if the new user take desktop and configuration or not. 

That to say, I think its really hard to manage so big remasterization... 

>I remember that some time ago, not so long, I executed a recommendation for my system. <This link tells about that interesting approach.
>https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/

>I followed the recommendations message from my system, and all went good.

This is OK and don't think impact with eggs... 

Perhaps you can try to exclude something - that is under /home is not a problem becouse we are remastering not cloning - but if you can exclude that is mounted on /dev/sdb1 perhaps we can gain time and space on the iso image, and later you can move the remain.

To exclude things simply add dirs on `/usr/local/share/penguins-eggs/exclude.list`.

**Comment by jupgithub** [comment]
For now, no success on virtualbox, more or less the same, I could login with password only, because live was already by default.  The menu button was there, but when I logout and re-login to test, the menu button disappeared, but folders were created on  Desktop, but the Desktop folder remain, it is a file that go to your site.. I was seeing that, and testing it.

Problems - applets not loading, Desktop folder problem.

I am delayed because the ventoy drive has much isos, and yet is copying, for the test on the other pc.

I have to find a way to clean /etc and /usr/share...  But I don't know for now.

**Comment by jupgithub** [comment]
> I used this - sudo eggs tools skel , from VirtualBox, and logout using pkill -KILL -u live And did login, and now I see some folders on the Desktop, but the Desktop folder is a file (the same problem for Desktop folder) Inside that file (Desktop) there is: ![VirtualBox_Linux Mint_14_05_2023_11_22_20](https://user-images.githubusercontent.com/84473445/238195136-6c3014c4-63dc-4f4b-88d2-3fe95441d128.png)

Here is the code inside the file for Desktop

**Comment by pieroproietti** [comment]
It's look like you are not taking the right xdg-user-dirs values, same misconfigurations.

**Comment by jupgithub** [comment]
An update note:
Thanks to Piero for your time on past days, and testing some things. 
As I wrote him on these days, I have been working trying to fix problems mintmenu, and mate-panel applets, removing a pair of suspected conflicting packages, etc.  Also, as I said, the problem of the Desktop folder creation appears have been fixed some days ago, as I have not seen it again, thanks.  Beside that, I tried alternating some exclusions, cleaning my system, comparing my packages with the Live ISO from Linux Mint 21.1 MATE, and removing some packages or installing other things. I left the default exclusions from Penguins-eggs some days ago.

I hope mate-panel 1.26.3 can be included on Linux Mint 21.2 MATE, as I have 21.1 (and mate-panel 1.26.2-1) and I saw an update (1.26.3) to that fixing some things that I suspect some of that is affecting my installation.

I continued inspecting and trying to clean my system.  For now, I have a little better and more healthy system.  With the last ISO egg, though not perfect, is looking good, better and better, as the work continue to be done. The errors from mate-panel were alternates (varied) on virtualbox with the live ISO eggs, they appears, or not, on different Boot. On the other pc with Ventoy, more or less, good.

I could boot the live ISO egg on virtualbox and on the other pc (with a Ventoy pendrive), using live and its password, no more personal user(s).

The rest is to continue cleaning my installation and testing, to produce each time a better live ISO of my system, to be ready to install it on a different pc with much (or mayority) of my programs included.
Thank you very much.

**Comment by jupgithub** [comment]
Just a note:
Just in case, I did not want to update to the last  update from today (9.4.11), until I could finish the testings with the 9.4.10 version.  Then I updated it. If I remember well, all of the before notes were done before updating.

**Comment by jupgithub** [comment]
I tried today to install an ISO from 5-21-23 using 9.4.10, and I could install it, but again some applets loading problems, and the Desktop folder creation error.  Curious, because the file created (not folder) has permissions with the created user. The rest shows on right-click the availability to delete, but this file is grayed for deletion.  Deleted the file and created the folder (per Piero before) with the name (Desktop) as root, and changed to my user.  It showed an error from samba sharing permissions, and I added the user to sambashare. It is working, but I have to check things.

Found this: 
make the directory: "/var/lib/samba/usershares/" accessible by any program. So run:

`sudo chmod 777 /var/lib/samba/usershares`

Source: [https://askubuntu.com/questions/989064/net-usershare-returned-error-255-ubuntu-16-04-lts]

**Comment by jupgithub** [comment]
Today, I did some work to my installation.
I executed this:
`xdg-user-dirs-update`

Removed a folder on root with permissions with my regular user to mount disks.

I found some broken links on /etc/alternatives, then I executed the following to fix it:
`yes '' | update-alternatives --force --all`

Later, I booted unintentionally with my last kernel 6.3.2, and decided anyway to create a new egg, and the live ISO booted fine, but I did not tested again.  I booted from an earlier kernel, and I produced another egg.

Before and/or after, some updates, etc.

The live ISO booted, but the applets loading problems again, but the rest appears to be fine.  I reset panels, and installed on virtualbox.  It booted find on the first time, but on the second time, the applets loading problem again.  I am waiting for some update for the following applets (waiting for update mate-panel 1.26.3):

NotificationAreaAppletFactory::NotificationArea (Icons on bottom right)
MateXAppStatusAppletFactory::MateXAppStatusApplet (updates, network, sound)
MintMenuAppletFactory::MintMenuApplet (Menu button)
ClockAppletFactory::ClockApplet (clock at bottom right)
WnckletFactory::ShowDesktopApplet
WnckletFactory::WindowListApplet

I have to test the ISO with Ventoy on the other pc.
That's for now.

**Comment by jupgithub** [comment]
Booting with Ventoy:

Normal mode:
error: file '/boot/grub/x86_64-efi/ieee1275_fb.mod ...
error: file '/boot/grub/x86_64-efi/vbe.mod' not found
error: file '/boot/grub/x86_64-efi/vga.mod' not found

Grub mode:
error: file '/grub/font.pf2' not found
Apart from that, and some caching errors (maybe not related to eggs), the ISO booted fine on both modes.  It booted with user 'live', not the error before with personal user(s).  I have not tested with the last updates of eggs.
