### ISSUE TITLE
Calamares does not work on EndeavourOS Cassini - Plymouth module cannot be loaded

### ISSUE THREAD

**Issue by shah-newaz** [pieroproietti/penguins-eggs-legacy#233]
Hi,

I created a live USB out of my EndeavourOS Cassini installation. It boots properly and all, however, when I try to install the system using Calamares, I get the following error:

![plymouth_error](https://github.com/pieroproietti/penguins-eggs/assets/11506530/4dcac501-75ee-4e8f-b9ac-53a4674b9351)

Which says:
Calamares initialization failed.
Calamares was unable to load all configured modules. This is a problem with the way Calamares is being used by the distribution.
The following modules could not be loaded:
plymouthcfg@plymouthcfg

**Comment by pieroproietti** [comment]
Hi shah-nevez

I had this problem too,  don't remember in that way I solved. On sourceforge page of [penguins-eggs](https://sourceforge.net/projects/penguins-eggs/files/ISOS/endeavouros/) there are a lot of endeavourOS isos working.

**Comment by shah-newaz** [comment]
Mine is using t2 linux kernel. Would that cause a problem? I see in AUR that there are special builds of Calamares for EndeavourOS and T2 and.... none of them work :(

**Comment by pieroproietti** [comment]
Yesterday I tried for a long time to solve the problem, but after making numerous changes I finally ended up with the same.

The last git comment - in Italian - is pretty much "shit".

So, I avoided updating the PKGBUILD on aur, find the updated PKGBUILD on [penguins-eggs-pkgbuilds](https://github.com/pieroproietti/penguins-eggs-pkgbuilds). 

I don't remember what exactly I did with the isos in [endeavourOS](https://sourceforge.net/projects/penguins-eggs/files/ISOS/endeavourOS/), surely I used calamares with yay not EndeavourOS versions, maybe I simply removed plymouthcfg from `/etc/calamares/settings.conf`.

To be honest, yesterday I tried: `pacman -S plymouth` and comment `plymouthcfg` on `/etc/calamares/settings.conf`, but not one nor the other worked.

**Comment by pieroproietti** [comment]
Hi shah-nevez

it seems that with the latest changes and installing plymouth in endeavourOS `pacman -S plymouth` works. 

Be careful not to update calamares, stay with the version 
`calamares 3.2.61-1` installed with yay.

If I can I make an eggs-v9.4.11 package that should work on all versions: Debian /Devuan/ Ubuntu/ Arch/ EndeavourOS/ Manjaro/ RebornOS

**Comment by shah-newaz** [comment]
Latest changes in Penguins Eggs? Should I install it from source?

Thanks a lot for being so supportive btw!

**Comment by shah-newaz** [comment]
9.4.11 would be awesome

**Comment by shah-newaz** [comment]
If this helps:
- Installed plymouth
- Removed calamares
- Installed calamares from eggs (sudo eggs calamares --install)
- commented out plymouthcfg from settings.conf

It somehow started fine. But the installation failed saying "packagechooserq was not found in global storage".

**Comment by pieroproietti** [comment]
I did:
* install plymouth;
* remove calamares;
* install calamares 3.2.61-1 with `yay calamares`;
* sudo eggs dad -d
* sudo eggs produce 

I did'nt tryed `sudo eggs calamares --install` becouse endeavour from pacman will find calamares 22.x.x and will install it again.

**Comment by shah-newaz** [comment]
Did you  try going all the way with installation? For me it failed towards the end looking for that packagechooser thing..

**Comment by shah-newaz** [comment]
Going to try your way

**Comment by pieroproietti** [comment]
I just re-make all the steps:
* installed EndeavourOS_Cassini_Nova-03-2023_R1.iso
* `pacman -Syu linux plymouth` we need to install linux and plymouth
* `yay penguins-eggs` 
* `yay calamares`  we will install calamares 3.2.61-1
* `sudo eggs dad -d` just to configure
* `sudo eggs tools clean` remove packages cache
* `sudo eggs produce --max` created with max compression

![endeavour-installed](https://github.com/pieroproietti/penguins-eggs/assets/958613/ca45f54e-7c39-44a7-8e30-e70a6c5957a2)

I get `egg-of-endeavouros-rolling-xfce_amd64_2023-05-21_1743.iso` about 1,6 GB, now uploading on [EndeavourOS](https://sourceforge.net/projects/penguins-eggs/files/ISOS/endeavourOS/).

**Comment by shah-newaz** [comment]
The workarounds finally worked!
Thanks @pieroproietti 
We can close this but a permanent fix that can use the Endeavour Calamares would be great. Please close it if you want.

**Comment by pieroproietti** [comment]
Probably Is better to leave It open, someone can find that usefull and, in all the ways, remain a bit of noise...

**Comment by shah-newaz** [comment]
@pieroproietti Any idea if the endeavouros calamares (that gets updated automatically everyday) can be made compatible with Penguins Eggs?

**Comment by pieroproietti** [comment]
Perhaps a suitable idea is to use [Chaotic-AUR](https://aur.chaotic.cx/) and install calamares from there, I discover it with [blendOS](https://sourceforge.net/projects/penguins-eggs/files/ISOS/blendos/) but seem to work on Arch too, just tested!

```
sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key FBA220DFC880C036
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
```
Append (adding to the end of the file) to /etc/pacman.conf:

```
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
```
Then:
```
sudo pacman -Syu calamares
```
