### ISSUE TITLE
Kubuntu 22.04: Calamares system installer error while installing on NVMe M.2 SSD

### ISSUE THREAD

**Issue by MrShlotty** [pieroproietti/penguins-eggs-legacy#238]
Hi,
when trying to install a successfully produced egg from a Live-ISO of Kubuntu 22.04, the Calamares system installer unfortunately fails for me. But while this error only applies to installations on a NVMe M.2 SSD, the installation on a SATA SSD can be done without any problems. 
While I was looking for a solution to this I tried to install an egg of a Debian 11.7 system via Live-ISO in the same way, which strangely works without any issues on both hard drives. I just don't know the reason for it.
I produced the eggs as follows:
sudo eggs dad -d
sudo eggs calamares --install 
sudo eggs produce --clone

Here is a screenshot of the Calamares system installer error while installing from the Kubuntu 22.04 Live-ISO on my NVMe M.2 SSD:

<img width="284" alt="Screenshot_20230527_142017" src="https://github.com/pieroproietti/penguins-eggs/assets/98344293/01870f1c-9d12-4d54-a639-7dda2fd041f7">

Is there a way to solve this problem? Any kind of help would be highly appreciated. Thanks.

**Comment by pieroproietti** [comment]
At the moment I don't know the reasons why calamares is gettings problems installing on NVME on Ubuntu... I will try to check later. 

As workaround you can install it with: `sudo eggs install` 

Note: krill installer will completely format the first device.

**Comment by pieroproietti** [comment]
Unfortunately, cannot emulate a VM with a nvme hard disk on proxmox VE. I tryed creating a new VM with SCSI drive and after edit the configuration to nvme0n1 but it seem don't work.

So I can't complete the experiment!

![no-nvme-device](https://github.com/pieroproietti/penguins-eggs/assets/958613/d7780e8e-e745-47cd-a315-8598b32d0982)

Just noted on Kubuntu 22.04 there is not installed nvme-cli... perhaps you can try to install it.

**Comment by MrShlotty** [comment]
First of all, thank you so much for your immediate reply. :)
I just tired to use your workaround with the krill installer but it seems to freeze without any error message. The installation is stuck at 3 percent, even though I waited it out for about 25 minutes with a completely clean ISO. So this method fails as well.
As I mentioned, both installers work perfectly with Debian for me, which leads me to the believe that this problem occurs specifically in a (K)Ubuntu-NVMe-related scenario.

**Comment by MrShlotty** [comment]
Hi again, 
I would like to add some more information regarding this issue.
Doing some further testing with penguins-eggs in combination with other distributions (Linux Mint, Debian 12 RC4 and KDE neon) showed that the NVMe error mentioned above does not even occur when using KDE neon, which should be as close to Kubuntu as you can get. 
Kubuntu itself remains the only distribution among all the ones I tested to be problematic.
Perhaps this helps to identify the cause of this incompatibility and ideally resolve it.

**Comment by pieroproietti** [comment]
Perhaps jammy is problematic in general regarding calamares. I noted jammy gnome remastered with eggs don't show calamares show during installation. This is probably related to wayland but on 23.04 its OK the show work normal. 

Thanks for informations
