### ISSUE TITLE
After installation lightdm/sddm user gets removed

### ISSUE THREAD

**Issue by xmb9** [pieroproietti/penguins-eggs-legacy#249]
this causes it to not load lightdm or sddm at all

**Comment by pieroproietti** [comment]
Frankly I didn't understand the question, can you explain it better and point out which distribution/codename and which version of eggs are you using?

**Comment by xmb9** [comment]
Using the latest version of eggs on Debian bookworm. After installing the iso lightdm (or sddm) never starts up because the lightdm/sddm group and user are missing.

**Comment by pieroproietti** [comment]
Just reinstalled my usual colibri - the last version - and I don't see problem.

```
artisan@colibri:~$ cat /etc/group|grep li
list:x:38:
lightdm:x:115:
```

Im remastering it again and I will put on [sf page](https://sourceforge.net/projects/penguins-eggs/files/ISOS/debian/bookworm/) with the name `egg-of-debian-bookworm-colibri_amd64_2023-06-20_1513.iso`.

**Comment by pieroproietti** [comment]
After that I take a virgin `debian-12.0.0-amd64-netinst.iso` and installed it as CLI, without GUI, then add eggs and remastered as naked. 

Then, I did just: `sudo apt install kde-plasma-desktop plasma-nm firefox-esr` a minimal kde installation and I remastered again it as plasma.

![plasma](https://github.com/pieroproietti/penguins-eggs/assets/958613/30c32a36-40c7-4199-a1c8-be783e022a62)

I'm uploading them naked and plasma on [sf](https://sourceforge.net/projects/penguins-eggs/files/ISOS/debian/bookworm/) and as I cannot replicate your bug.

**Comment by pieroproietti** [comment]
Here I'm installing with calamares (I used the terminal and the command: `sudo calamares -d` to launch it...

![installing](https://github.com/pieroproietti/penguins-eggs/assets/958613/7ddb4cf2-92a2-4852-b456-5051e5c403b5)

And in the resulting installed system, we have:

![sddm-present](https://github.com/pieroproietti/penguins-eggs/assets/958613/795883fd-fe1d-4e4a-a259-70ccc90205da)
