### ISSUE TITLE
No password on live account?

### ISSUE THREAD

**Issue by xmb9** [pieroproietti/penguins-eggs-legacy#257]
i've edited /usr/lib/penguins-eggs/conf/eggs.yaml and /etc/penguins-eggs.d/eggs.yaml to have no password yet it still shows evolution

**Comment by pieroproietti** [comment]
Hallo 

cannot have `no-password` just editing eggs.yaml, this is something you must configure on the system and it's a bit boring, for that I prefere to have password.

In all the ways, I configure live naked systems (CLI only) in this way to not need passwork at login and to suggest user/password and root password with motd. You can get a look at [cli-autologin.ts](https://github.com/pieroproietti/penguins-eggs/blob/master/src/lib/cli-autologin.ts).

**Comment by xmb9** [comment]
i need no password because sddm autologin didnt work at all, it worked on the iso but after installing sddm never showed up.

**Comment by pieroproietti** [comment]
@EnterTheVoid-x86 

I hope you solved your problem, I was on holidays for a while. 

That to say, I use sddm, it work for me. 

If you are on Arch or derivatives; did you create autologin group and included your user in autologin?

```
groupadd autologin
gpasswd -a your-user-name autologin
```

Hope this can help.
