### ISSUE TITLE
Clarification on whether or not configuration files are included without --clone

### ISSUE THREAD

**Issue by ranenvious** [pieroproietti/penguins-eggs-legacy#258]
What is included and isn't included with and without the --clone flag activated? Specifically I'm curious if configuration files are included without the --clone flag. I'm considering trying to mirror my main system over to my laptop (that installation is around a year old at this point and it was one of my first linux installs so it's no longer something I'm super happy with) and, while I definitely don't want my >Tb entire root partition copied over, I would want all of my configuration files copied over since those are a significant part of my system working the way it does. 

From what I can tell wtih --clone **_everything_** does get copied, but without --clone I'm not sure whether config files would or wouldn't be. I'm sure there will always be exceptions of some random program choosing to store it's config files in a weird place, but would my .kwinrc for instance be moved over? What about my installed widgets? Plymouth boot animations? etc. I could see an argument for some or all of these being user data, but I also feel like they occupy a different type of user data to everything else. The files you keep in your documents folder for instance don't really change how your computer "feels" to use, meanwhile the accent colour your DE is using very much does.

**Comment by pieroproietti** [comment]
HI @Churchexe 

with `--clone` all `/home/*` is saved like the others dirs, and `/etc/passwd`  and `/etc/groups` remain untouched.

Without `--clone` option, all `/home` is excluded, `/etc/passwd` and `/etc/groups` are purged, so when you have a new user, it take the configurations from `/etc/skel`.

There is a command: `sudo eggs tools skel` who save or try to save, various desktop environment files from an user home to `/etc/skel` to let to get your configuration to new users.

`sudo eggs tool skel` It work well enought with main DE, you can see the logic on [xdg.ts](https://github.com/pieroproietti/penguins-eggs/blob/3f2df1d3fe47b5c5fe5b7bb5d0427a6694e4b445/src/classes/xdg.ts#L190). If you need to safe more on /etc/skel you can do it manually, before to produce ISO.

I hope I was clear, and my english good enought. 

Have nice time
