### ISSUE TITLE
Calamares cant load users@users module

### ISSUE THREAD

**Issue by xmb9** [pieroproietti/penguins-eggs-legacy#259]
When I load Calamares after installing it on Arch Linux, it says "cannot load module users@users"

**Comment by pieroproietti** [comment]
Yes,

the actual [calamares on aur](https://aur.archlinux.org/calamares.git)  give this problem and I don't know why.

To mitigate I created as workaround in my repository [eggs-pkgbuilds](https://github.com/pieroproietti/eggs-pkgbuilds)  a **calamares-eggs**.

You can use it:

* `git clone https://github.com/pieroproietti/eggs-pkgbuilds`
* ` cd eggs-pkgbuilds/aur/calamares-eggs`
* `makepkg -si`

It's also possible to save the resulting file `calamares-eggs-3.3.0.r10616.11e1659ca-1-x86_64.pkg.tar.zst` and use it later: `pacman -U /path/to/calamares-eggs-3.3.0.r10616.11e1659ca-1-x86_64.pkg.tar.zst`.

I'm uploadind mine, on mine sourceforge page at [PKGBUILD](https://sourceforge.net/projects/penguins-eggs/files/PKGBUILD/) 

Until now I not proposed `calamares-eggs` on **aur** and in **chaotic** to not have duplicate.

**Comment by xmb9** [comment]
Thanks, that worked great, however now it asks me for a password everytime i want to run calamares.

**Comment by xmb9** [comment]
Fixed by editing  /usr/share/polkit-1/actions/com.github.calamares.calamares.policy.
