### ISSUE TITLE
ManjaroLinux is not yet recognized

### ISSUE THREAD

**Issue by pbl0** [pieroproietti/penguins-eggs-legacy#260]
Hi, reproduced this error in two machines and a VM. Installed from Manjaro's repo.

`This distro ManjaroLinux/Uranos is not yet recognized!`

![image](https://github.com/pieroproietti/penguins-eggs/assets/42704788/63d5dec9-4011-4238-820f-c46f05ee7193)

**Comment by xmb9** [comment]
penguins-eggs probably needs to be updated

**Comment by xmb9** [comment]
The developer just added support for Manjaro Uranos 4 hours ago.

**Comment by pbl0** [comment]
00b503cae296ee27966338d709537a2aa35a620a

It works now as expected. Thanks!!
