### ISSUE TITLE
support rpm packages for oracle linux , fedora etc.

### ISSUE THREAD

**Issue by saurabhahuja71** [pieroproietti/penguins-eggs-legacy#262]
Really liked this project, but would be good if we can also support rpm packages installation and those linux distros in general

**Comment by pieroproietti** [comment]
Add Redhat family and SUSE was on my original plans, but to do that I need collaborations, I can assist and suggest the way.

**Comment by saurabhahuja71** [comment]
Alright, let me connect with my company to have approval in place in order to collaborate on this,

**Comment by pieroproietti** [comment]
This will be great! :+1:

**Comment by pieroproietti** [comment]
I wrote something about, that is your idea? 

https://penguins-eggs.net/blog/un-punto-morto
