### ISSUE TITLE
Parrot os Support ??

### ISSUE THREAD

**Issue by andi-mache** [pieroproietti/penguins-eggs-legacy#263]

**Comment by pieroproietti** [comment]
Hi @andi-mache 

I have no experience with Parrot OS, just now I saw it's a Debian derivated... I think we can include it... let me to try.

**Comment by pieroproietti** [comment]
Well, 

at last I discovered [ParrotOS](https://www.parrotsec.org/) and the history of his name: "__every pirate of the seven seas needs a parrot on his shoulders__".

## Remaster Parrot ara
Remaster Parrot with eggs is really simple, I just installed Parrot security and installed eggs.

![parrot-ara](https://github.com/pieroproietti/penguins-eggs/assets/958613/0a3db1b5-3bdc-4598-9f6b-73b8b1aeb35a)

### Add ara in derivatives
At this point I need to edit `derivatives.yaml` and add ara.
![parrot-ara-derivatives](https://github.com/pieroproietti/penguins-eggs/assets/958613/24731a04-d46f-42c5-ad6f-60b3b1d8e6f1)

### remaster it
Then we can remaster it!
![parrtot-ara-remastering](https://github.com/pieroproietti/penguins-eggs/assets/958613/c2fb8a5d-2ff8-42d5-9383-ca259c44fc2d)

### Install parrot

![parot-installing](https://github.com/pieroproietti/penguins-eggs/assets/958613/f2d78a7f-37a0-4b4c-a6c4-2700965e83f4)


# Conclusion

Parrot ara will be included on the future versions of eggs and I'm preparing to upload the resulting is on https://sourceforge.net/projects/penguins-eggs/files/ISOS/parrotos/

**Comment by andi-mache** [comment]
thanks
