### ISSUE TITLE
Installation fails on BIOS/MBR partitioning (grub-pc issue?)

### ISSUE THREAD

**Issue by JamesShriner** [pieroproietti/penguins-eggs-legacy#264]
First and foremost...KUDOS on the PenguinsEggs project!  As a former Remastersys and Systemback user, I have been searching for a viable replacement ever since they were both abandoned.  The linux ecosystem DESPERATELY needs a tool to clone a currently existing installation to an ISO, for deployment of a homogeneous OS across a small network of computers.  And Clonezilla is NOT that tool, for various reasons.  I LOVE your PenguinsEggs project, which I have only recently discovered and have utilized to create a customized remix of my new favorite distro, to be deployed across my home network of computers, laptops, set-top boxes, etc...

I have downloaded the most recent DEB file from your page and installed to Debian 12 Bookworm.  I have been able to use PenguinsEggs to successfully create the ISO, and have copied that ISO to USB for use as a Live-Media using dd.  The Live-Media successfully boots in a VM, as well as actual computer hardware.  Testing in VMs and hardwares has provided me with successful installations to UEFI/GPT systems, with no issues.  But I have ONE machine with a BIOS that requires MBR partitioning that fails at the Calamares step of removing grub-efi and installing grub-pc.  I have tried creating ISO with Calamares using "eggs produce --calamares"; i have tried removing calamares and installing through Debian (12 Bookworm) repos and creating ISO with eggs dad.  I have tried using the krill installer, which also fails (not sure if that matters, or if its a clue), but I'm really only interested in the Calamares installer, as this custom remix will also be an installation candidate for family & friends who use Linux, but lack the technical expertise to use Krill (seems like maybe I lack that expertise also?).

I'm not sure if I'm doing something wrong in the process, or if I've found a bug in the process.  I note the YAML file for eggs references "make_efi=true".  Could this be the source of issue with Calamares failing to install to a BIOS/MBR system?  I have the calamares log from a "calamares -d" installation, with terminal messages available at the failure point, and it does fail at the same point each time (see attached text file).  

Please advise how to install to a BIOS/MBR machine.  If I'm doing something wrong in the process, please correct me.  If I have found a bug, please fix.  I am anxious to use PenguinsEggs to deploy my remix across ALL my machines, as well as family & friends.  If this issue can be resolved, PenguinsEggs will be the PERFECT tool for that use-case scenario, so THANK YOU for this wonderful tool!
[Calamares log](https://github.com/pieroproietti/penguins-eggs/files/12359766/Calamares.log)

**Comment by pieroproietti** [comment]
Moved on [discussions](https://github.com/pieroproietti/penguins-eggs/discussions/265)
