### ISSUE TITLE
GRUB config error (?)

### ISSUE THREAD

**Issue by GyulTips** [pieroproietti/penguins-eggs-legacy#268]
I'm a newbie linux user. when I produce an egg, this error happens. 
![1](https://github.com/pieroproietti/penguins-eggs/assets/70993344/5a01430b-fc94-43fe-a77b-9f330a7306a3)
Although booting into the live system and installing using calamares seems to be working fine, after install GRUB shows nothing but UEFI Firmware Settings.
![2](https://github.com/pieroproietti/penguins-eggs/assets/70993344/bfc546c5-fb91-4b13-8131-35792a500d15)

OS: Arch
DISK: ext4
Command: `eggs produce --release` , `eggs produce --clone --max` (same goes for with this command too)

built using the virtual machine.
edit: I tried this with Lubuntu, and it worked!(with no errors) maybe arch problem? or my setup ruined a bit?

**Comment by pieroproietti** [comment]
I don't know, today - just an hour or two ago - I make an Arch naked iso without problems. 

I used the actual testing eggs, you can find it on [testing](https://sourceforge.net/projects/penguins-eggs/files/DEBS/testing/), just download  penguins-eggs-9.5.20-1-any.pkg.tar.zst and give `sudo pacman -U  penguins-eggs-9.5.20-1-any.pkg.tar.zst` to install.

I see an `'` at the end of the command, but not an `'` at the end...

**Comment by GyulTips** [comment]
> I don't know, today - just an hour or two ago - I make an Arch naked iso without problems.
> 
> I used the actual testing eggs, you can find it on [testing](https://sourceforge.net/projects/penguins-eggs/files/DEBS/testing/), just download penguins-eggs-9.5.20-1-any.pkg.tar.zst and give `sudo pacman -U penguins-eggs-9.5.20-1-any.pkg.tar.zst` to install.
> 
> I see an `'` at the end of the command, but not an `'` at the end...

I tried, but same error happens again..
![스크린샷 2023-08-29 010206](https://github.com/pieroproietti/penguins-eggs/assets/70993344/bb4fa5a9-efc4-4747-826e-c96a6dc846d4)

This command even doesnt work on regular terminal. (says `invaild file system format, bad option, bad superblock on overlay(?), code page or support program missing(?), or other error`.)
![스크린샷 2023-08-29 010339](https://github.com/pieroproietti/penguins-eggs/assets/70993344/0c946957-e331-497a-b553-3a23b2c13ba6)

I used Arch(installed with `archinstall`) and installed KDE Plasma following https://itsfoss.com/install-kde-arch-linux/ this guide, and did almost nothing  exapt installing themes.

**Comment by pieroproietti** [comment]
Today I used a lot archistall, after enought long time.

It became really powerfull, and I like It very much, but I had the same your problem.

In my case /boot was formatted as vfat and this make It impossible to be mounted overlay, so I must convert It in ext4.

Probably I will change something in the future: /boot Is a really little partition and it's better to copy It than to have this limitation, expecially to can use btrfs.

**Comment by GyulTips** [comment]
It fixed after 9.5.25 update. Thanks a lot!
