### ISSUE TITLE
Unhandled Error event during Krill installation

### ISSUE THREAD

**Issue by ChrisJackHowe** [pieroproietti/penguins-eggs-legacy#269]
Hello, **this issue may be fixed as it occurred in version 9.5.3.** Feel free to remove it if so.
I made an installable iso using `sudo eggs produce --clone --release --nointeractive`.
The machine being cloned is a VirtualBox VM running Ubuntu 22.04.
After creating the iso and making it a bootable device using rufus.
I try installing it using `sudo /usr/bin/eggs install -un`
When I install the iso onto another VM there is no error.
I will be testing with version 9.5.19 on monday.
During the installation process I am getting this error.
The error occurs at 46%, once with step `machineid` and once with step `fstab`
```
Node.js v18.16.0
node:events:491
    throw er; // Unhandled 'error' event
eggs >>>  {"errno"-28, "syscall":"Write","code":"ENOSPC","name":"ShellJSInternalError"}
```

The eggs.yaml, krill.yaml and actual hardware are the same as seen in this issue #245

**Comment by pieroproietti** [comment]
Hi @ChrisJackHowe 

I suppose we have again a problem with nvme... and I have again the problem to test it on real hardware.

For now, I can't go to the shop of mine friends to test.

**Comment by ChrisJackHowe** [comment]
Actually this machine is a little different, it actually does have sda instead of nvme
```
live@machine:~$ df
Filesystem 1k-blocks Used Available Use% Mounted on
tmpfs ...
/dev/sda1...
tmpfs...
```

**Comment by pieroproietti** [comment]
Try using last version, take time for me replicate.

If work, reply to this issue and close it, if not work, give me informations to replicate.
