### ISSUE TITLE
NODE_PATH gets changed to /var/tmp/.../penguins-eggs

### ISSUE THREAD

**Issue by shahnewazrifat** [pieroproietti/penguins-eggs-legacy#270]
Hi,
It seems, penguins somehow changes the default node global packages path to /var/tmp/.../penguins-eggs... 
Can this be reversed/fixed?

Try: 
npm get prefix
or 
npm root -g

Thanks

**Comment by pieroproietti** [comment]
Debian version or Arch?

**Comment by shah-newaz** [comment]
Arch (EndeavorOS)

**Comment by pieroproietti** [comment]
OK, I must to look to PKGBUILD.

This is actually, if you want get a look: [PKGBUILD](https://github.com/pieroproietti/eggs-pkgbuilds/tree/master/aur/penguins-eggs).
