### ISSUE TITLE
/etc/resolv.conf is a copy and not linked 

### ISSUE THREAD

**Issue by freisei** [pieroproietti/penguins-eggs-legacy#286]
Hello!

And thanks again for this great project!

on my source-system it looks as follows:
```
root@tc-remaster3:/etc/systemd# ls /etc/resolv.conf  -la
lrwxrwxrwx 1 root root 39 Sep 20 20:26 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf
```

when i boot a live-system from my egg it looks like

```
root@XP142:~# ls -la /etc/resolv.conf
-rw-r--r-- 1 root root 54 Sep 21 12:46 /etc/resolv.conf
```

its not like in #122 when i use the installer, its in the live-system.

How to fix that?

Greets from Bavaria

**Comment by pieroproietti** [comment]
Hi freisei,

etc Is mounted binded RO, then RW with overlay, during the creation of the live file system. 

Probably this cause the problem. 

We need to indagate.

**Comment by pieroproietti** [comment]
Always eggs rm /etc/resolv.conf on the filesystem live during the production of the ISO, actually I removed all the instructions to create it, so it's completely responsability of the distro. 

On Ubuntu focal we have: `/etc/resolv.conf -> /run/systemd/resolve/stub-resolv.conf` on the original installed, but reinstalling the created ISO we have a simple file `/etc/resolv.conf`, that actually work in focal and jammy, but not on mantic. On Ubuntu mantic, actually we have a problem: not exists systemd-resolve service.
