### ISSUE TITLE
SDDM not loading after installing with Arch Linux based distro, and tty's keep trying to autologin to live account

### ISSUE THREAD

**Issue by xmb9** [pieroproietti/penguins-eggs-legacy#288]
After installing an iso made with eggs based on arch, SDDM does not load and when switching to tty it is stuck in a loop of trying to  log into the live account.

![SDDM not loading](https://github.com/pieroproietti/penguins-eggs/assets/64978924/de3c20d8-ffcc-4397-a4ec-cd4f9ed4bb32)
SDDM not loading
![TTY stuck in autologin loop](https://github.com/pieroproietti/penguins-eggs/assets/64978924/49fdcd19-d3eb-4c51-8162-7ebe25b08c2d)
TTY stuck in autologin loop

I cannot do any further troubleshooting because of the autologin loop.

**Comment by pieroproietti** [comment]
I noted this problem, actually i don't know why happen.  

I use auto login just for naked (CLI) and usually remove It after CLI installation. 

We must analyze that happen.

**Comment by pieroproietti** [comment]
Today I'm uploading a new arch kde based, I  will call it albatros in the future... it's  automatically made with eggs wardrobe. 

In all the way during the build I checked if there was same issues with CLI autologin, I found it OK. 

If you want can test this version. 

You can also start with a naked iso then:
* `eggs wardrobe get`
* `sudo eggs wardrobe wear albatros`

**Comment by pieroproietti** [comment]
You can try: ` sudo rm /etc/systemd/system/getty@.service.d/override.conf ` to remove my cli-autologin if it is present.

**Comment by xmb9** [comment]
> sudo rm /etc/systemd/system/getty@.service.d/override.conf

Is there a way I can prevent penguins-eggs from making changes to this file? Thanks
