### ISSUE TITLE
Come preservare le impostazioni di rete durante la creazione di un uovo?

### ISSUE THREAD

**Issue by Pachialone** [pieroproietti/penguins-eggs-legacy#290]
Salve e complimenti per questo strumento,è veramente grandioso!Ho cercato nei tutorials ma non ho trovato una risposta a :come mantenere le mie impostazioni di rete agendo sul file delle esclusioni.Un aiuto sarebbe apprezzato,grazie.Nel mentre,mi preparo a nascondermi per almeno un mese perchè sono quasi sicuro che la soluzione è sotto i miei occhi ma non la vedo.:-)

**Comment by pieroproietti** [comment]
Ciao,

che distribuzione utilizzi, hai una rete statica? 

Comunque, ho provato a dare una occhiata, sembra che vada a rimuovere le impostazioni di rete [vedi codice](https://github.com/pieroproietti/penguins-eggs/blob/14f8d6e3c78b309becaf6548db4032380699de68/src/classes/ovary.ts#L547) e, d'altra parte, è anche normale perchè in origine era pensato per la rimasterizzazione.

**Comment by Pachialone** [comment]
Ciao,ho fatto alcuni test:il primo su Arcolinux ed il secondo su Debian 12 (sempre con XFCe)ed in entrambi i casi la iso è perfetta tranne che per questo aspetto,sono in dhcp e quando vado a testare la live installabile noto che nell'elenco delle reti memorizzate visibili nell'applet Network Manager non c'è nulla.La mia è una curiosità perchè all'atto dell'utilizzo della live mi basta impostare la passwd del wifi e navigo senza difficoltà(immagino che lo stesso accadrebbe in eth,che non uso).C'è un modo per editare questa impostazione?

**Comment by pieroproietti** [comment]
Allora, se guardi il codice che ti ho passato, vedrai che alla riga 528 sino alla 531 si esegue una pulizia delle eventuali connessioni wifi.

Probabilmente se ti salvi il contenuto e lo reimmetti prima di connetterti, potresti reimpostarlo, ma non ne sono sicuro. 

Non ho mai pensato a fare una opzione del tipo --trattieni-le-password-di-rete

**Comment by Pachialone** [comment]
Va bene,farò un tentativo in questo senso.Grazie!
