### ISSUE TITLE
vmlinuz naming error with eggs-9.6.1 deb64-package from sourceforge

### ISSUE THREAD

**Issue by mr-transistor** [pieroproietti/penguins-eggs-legacy#297]
I got an error during 
eggs produce --clone --standard     ( on linux mint, debian12 edition, lmde6) 

Cannot find  /boot/vmlinuz--6.5.5

My self-compiled kernel is 'vmlinuz-6.5.5'  without a double "-").
But a symlink did help as workaround.

**Comment by pieroproietti** [comment]
Hi @mr-transistor ,

perhaps it's just the case - after you add your kernel - to give a: `sudo eggs dad -a` to renew the configuration?

**Comment by mr-transistor** [comment]
Hi Piero,

 

now, with linux-6.5.6your eggs-9.6.3 everything works on LMDE6.

And yes, I did not use 'eggs dad -a' before.

But now, i configure eggs.yaml (and krill.yaml).

 

As next step I will try it with arch linux derivate "endeavouros".

 

I`ve used many remaster-tools (suse linux with kiwi, mylivecd from

pclinuxos, remastersys, refracta-snapshot with debian bookworm(works fine too) and

systemback with lmde6 (a refracta-snapshot-image did not boot).

I`m building huge iso images(sometimes up to 40GB)


 

Maybe linux.exton.net  is also interested on your work. Normaly he is using refracta.

 

Thanks for your good work and the fast updates.

 


--

Bruno

 
 

Gesendet: Mittwoch, 04. Oktober 2023 um 22:07 Uhr
Von: "Piero Proietti" ***@***.***>
An: "pieroproietti/penguins-eggs" ***@***.***>
Cc: "mr-transistor" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [pieroproietti/penguins-eggs] vmlinuz naming error with eggs-9.6.1 deb64-package from sourceforge (Issue #297)


 

Hi @mr-transistor ,

perhaps it's just the case - after you add your kernel - to give a: sudo eggs dad -a to renew the configuration?

**Comment by pieroproietti** [comment]
Fine, 

you can be usefull for me and others, with suggestions and help, I see you are an expert.

Eggs started from refracta-installer, I used very few it, more take it as sample and guide.

Always thought to extend out of Debian/Devuan/Ubuntu, so when the tools was enoght well on Debian with the help of Stefano Capitali - from manjaro - was able to work with manjaro. Soon later come of course Arch and then same dervatives: garuda, endeavour, etc.

Happy to be appreciated

Piero

**Comment by pieroproietti** [comment]
Yes, linux.exton.net use eggs at least sometime.

DebEX Gnome/Enlightenment – Build 230411 – with Gnome 43.4, Enlightenment 0.25.4, penguins-eggs (a remaster tool), Refracta Snapshot and kernel 6.3.0-rc4-amd64-exton

https://linux.exton.net/debex-gnome-enlightenment-build-230411-with-gnome-43-4-enlightenment-0-25-4-penguins-eggs-a-remaster-tool-refracta-snapshot-and-kernel-6-3-0-rc4-amd64-exton/

**Comment by mr-transistor** [comment]
Hello Piero,

 

a short feedback:

 

I did build two eggs on enveavouros with a preinstalled archiso package.

The live-images are running well, but until now

I did not try to installation from it. 

--

Bruno

 
 

Gesendet: Montag, 09. Oktober 2023 um 21:12 Uhr
Von: "Piero Proietti" ***@***.***>
An: "pieroproietti/penguins-eggs" ***@***.***>
Cc: "mr-transistor" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [pieroproietti/penguins-eggs] vmlinuz naming error with eggs-9.6.1 deb64-package from sourceforge (Issue #297)


 

Fine,

you can be usefull for me and others, with suggestions and help, I see you are an expert.

Eggs started from refracta-installer, I used very few it, more take it as sample and guide.

Always thought to extend out of Debian/Devuan/Ubuntu, so when the tools was enoght well on Debian with the help of Stefano Capitali - from manjaro - was able to work with manjaro. Soon later come of course Arch and then same dervatives: garuda, endeavour, etc.

Happy to be appreciated

Piero
