### ISSUE TITLE
Linux Mint 21.2 (Victoria) This distro / is not yet recognized! Due the lacks of calamares package set force_installer = false

### ISSUE THREAD

**Issue by zDEFz** [pieroproietti/penguins-eggs-legacy#301]
iso: https://www.linuxmint.com/download.php

Steps done

1. sudo apt-get install eggs
2. sudo apt-get install calamares
3. eggs --version
4. penguins-eggs/9.6.3 linux-x64 node-v16.20.2
5. sudo eggs calamares --install
6. sudo eggs dad -d

Due the lacks of calamares package set force_installer = false
This distro / is not yet recognized!

1. cat /etc/os-release

```
NAME="Linux Mint"
VERSION="21.2 (Victoria)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.2"
VERSION_ID="21.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=victoria
UBUNTU_CODENAME=jammy
```

2. cat  /etc/lsb-release 
```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.2
DISTRIB_CODENAME=victoria
DISTRIB_DESCRIPTION="Linux Mint 21.2 Victoria"
```

3. sudo nano /usr/lib/penguins-eggs/conf/derivatives.yaml
4. append
```
- id: linuxmint
  distroLike: ubuntu
  family: debian
  ids:
    - victoria # Linux Mint
```
5.  sudo eggs dad -d

```
This distro / is not yet recognized!

You can edit /usr/lib/penguins-eggs/conf/derivatives.yaml to add it -
after that - run: sudo eggs dad -d to re-configure eggs.
If you can create your new iso, you can contribute to the project
by suggesting your modification.
```

**Expected**

1. Calamares is found
2. Distro is recognized

**Comment by zDEFz** [comment]
Not sure what solved my issue. 
Might been related with running  addaura.sh from https://github.com/pieroproietti/addaura

But it was weird - first it said it had no conf yaml anymore and then it went ahead and generated one and then it worked.

**Comment by pieroproietti** [comment]
Steps to do to remaster something:

1)  sudo apt-get install eggs
2)  sudo eggs dad -d                        # configure eggs with default
3) sudo eggs calamares --install   # install calamares and others libs for calamares
4) sudo eggs produce                    # create the iso, you can add varius parameters
