### ISSUE TITLE
Wrong error handling when running from sshfs-mounted folder in unprivileged context "This distro / is not yet recognized!"

### ISSUE THREAD

**Issue by zDEFz** [pieroproietti/penguins-eggs-legacy#302]
**Reproduction**

1. `sudo mkdir /sshfsfolder; cd /test123; sudo chown -R user:user /test123`
2. mount folder in user context 

```
SOURCE="test@192.168.178.32:/here/could/be/your/path"
TARGET="/sshfsfolder"

/usr/bin/sshfs -o kernel_cache -o auto_cache -o reconnect \
        -o compression=no -o cache_timeout=600 -o ServerAliveInterval=15 \
        "$SOURCE" "$TARGET"
```

4. sudo eggs export iso

**Expected**
No error message about a config pops up, instead we are notified about a limitation.

5. Inspect target folder

```
stat sshfsfolder
  File: sshfsfolder
  Size: 360       	Blocks: 8          IO Block: 4096   directory
Device: 41h/65d	Inode: 1           Links: 1
Access: (0775/drwxrwxr-x)  Uid: ( 1002/ UNKNOWN)   Gid: ( 1003/ UNKNOWN)
Access: 2023-05-04 08:19:35.000000000 +0200
Modify: 2023-10-06 20:17:45.000000000 +0200
Change: 2023-10-06 20:17:45.000000000 +0200
 Birth: -

ls -la .
total 12
drwxr-xr-x  3 root root 4096 Oct  8 19:18 .
drwxr-xr-x 21 root root 4096 Oct  8 22:20 ..
drwxrwxr-x  1 1002 1003  360 Oct  6 20:17 sshfsfolder
```

**Actual**
This distro / is not yet recognized!

**Comment by pieroproietti** [comment]
Hi @zDEFz ,

to be honest I don't understand the question.

Just I want to say: the command `eggs export iso`  take the his informations from  `etc/penguins-eggs.d/tools.yaml`

so, for now, it's not related to your problem.

If I don't understood the question, please explain again.

Thanks Piero

**Comment by zDEFz** [comment]
> Hi @zDEFz ,
> 
> to be honest I don't understand the question.
> 
> Just I want to say: the command `eggs export iso` take the his informations from `etc/penguins-eggs.d/tools.yaml`
> 
> so, for now, it's not related to your problem.
> 
> If I don't understood the question, please explain again.
> 
> Thanks Piero

The issue is that when the terminal has changed directory to a folder which is mounted by sshfs, and then the user wants to write through eggs, e.g by the iso export or `sudo eggs produce`, it would always say the distro is not recognized, and if the output folder is changed to the sshfs one, it says 0GB space available.

The workaround is to cd to a non sshfs folder, like ~/
Then the program runs properly.

**I will post a video of it in a fresh VM later.**

**Comment by pieroproietti** [comment]
OK, 
I tried a bit, I did from my VM: 
* `mkdir eggs`
* `sudo sshfs root@192.168.1.2:/eggs eggs`
* `sudo su`
* `cd eggs`
* `eggs export deb`

All OK

Then
* `mkdir eggs`
* `sshfs artisan@192.168.1.2:/home/artisan eggs/`
* `cd eggs`
* `eggs export deb`

All OK the same...

Anyway, I will check again, after your video.

**Comment by zDEFz** [comment]
> Anyway, I will check again, after your video.

I can still do it - and I tried to copy the acls. 
Turns out I cant really - and its only a problem when its mounted...
But I cannot copy the folder, exactly how it is!

The closest I got was `mkdir -m 0775 -p -v -Z system_u:object_r:default_t:s0 ~/test; sudo chown 1002:1003 ~/test`

Is it possible it somehow recognizes the remote system? 
Because the mounted sshfs folder is from 
```
NAME="Arch Linux ARM"
PRETTY_NAME="Arch Linux ARM"
ID=archarm
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinuxarm.org/"
DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
SUPPORT_URL="https://archlinuxarm.org/forum"
BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"
LOGO=archlinux-logo
```

https://github.com/pieroproietti/penguins-eggs/assets/24463722/c0a5b3c0-c775-43cd-8ff7-e46a52b9af5e

**Comment by pieroproietti** [comment]
Great video, I will study it!

**Comment by pieroproietti** [comment]
I'm really sorry, surely depend on me, but I can't replicate. 

I imagine your original problem is to get space to create an ISO from  a too full machine. 

Then:

* create a mountpoint on the janitor: `sudo mkdir /home/eggs/mnt -p`
* mount on the janitor the remote space you need: `sudo sshfs root@192.168.1.2:/path/to/share /home/eggs/mnt`
* `sudo eggs produce `

If you want can contact me on telegram @PieroProietti

**Comment by zDEFz** [comment]
> I'm really sorry, surely depend on me, but I can't replicate.
> 
> I imagine your original problem is to get space to create an ISO from a too full machine.
> If you want can contact me on telegram @pieroproietti

1. No that is not the issue. I have plenty of space
For that issue, please look into #303 

You could also simply enforce to only start when the user changed directory to `~/`
That would save both of us time, although this is not a 'real' fix.

If you want to invest time into it, let me know because I think this will take a bit.
We could investigate together. I do not have Telegram.
Maybe via https://jitsi.org/ ? Less hassle setting things up.

Or we could also use IRC - I have that. I'm known under the username "bluetail".
Currently at https://libera.chat/
