### ISSUE TITLE
"Space insufficient" of newly made mount - but proceeds without issues

### ISSUE THREAD

**Issue by zDEFz** [pieroproietti/penguins-eggs-legacy#303]
**Preparation**

1. Run gparted
2. Make a new partition (I used ext4)
3. Apply changes

**Steps to reproduce:**

1. `cd ~/`
4. `sudo mkdir /mnt/other`
5. `sudo chown -R user:user /mnt/other`
6. `sudo mount /dev/nvme0n1p3 /mnt/other`
7. `sudo nano  /etc/penguins-eggs.d/eggs.yaml`
8. `snapshot_dir: /mnt/other`
9. CTRL+X, CTRL+Y, Enter
10. `sudo eggs produce`

**Expected:** 
result is comparable with `df -BG` 
/dev/nvme1n1p3                                                   984G   138G      796G  15% /mnt/other

**Actual**
0GB Free. "Space insufficient" 

Note: This is a empty / new partition.
Happens only on first run. At the second run, it proceeds with the proper disk readings.

Fortunately, can proceed to make the eggs.
But under 'normal' circumstances, program should abort due to insufficient space.

**Comment by pieroproietti** [comment]
I did this test, on a VM 32 GB, I reduced to about 16 to have another partition of 16GB.

This is the result!

![this-is-the-result](https://github.com/pieroproietti/penguins-eggs/assets/958613/599d4956-de97-40ba-8bad-2598c0fd2951)

```
version: 9.6.3
snapshot_dir: /mnt/other
snapshot_prefix: egg-of-debian-bookworm-
snapshot_excludes: /usr/local/share/penguins-eggs/exclude.list
snapshot_basename: colibri
user_opt: live
user_opt_passwd: evolution
root_passwd: evolution
theme: eggs
force_installer: true
make_efi: true
make_md5sum: false
make_isohybrid: true
compression: fast
ssh_pass: true
timezone: America/New_York
locales_default: it_IT.UTF-8
locales:
  - it_IT.UTF-8
  - en_US.UTF-8
pmount_fixed: false
machine_id: 4eee3a7c7ca94b13a33778c5525a766d
vmlinuz: /boot/vmlinuz-6.1.0-13-amd64
initrd_img: /boot/initrd.img-6.1.0-13-amd64
snapshot_mnt: /home/eggs/mnt/

```

**Comment by pieroproietti** [comment]
# I repeat again the test:

![test-2-1](https://github.com/pieroproietti/penguins-eggs/assets/958613/678a13ad-22c0-4e15-897e-e4993aee8c9f)

# Partition
using a 4GB second partition size
![test-2-2](https://github.com/pieroproietti/penguins-eggs/assets/958613/7a69d810-e28c-4297-b425-37e475e8542e)

# Results
Production of the ISO was OK, but for some reasons the various folders of filesystem remain mounted! (They are mounted RO binded not really copied, then where we need, we remount with overlay).

![test-2-3](https://github.com/pieroproietti/penguins-eggs/assets/958613/98a22994-a952-4574-a757-0738a112ed1e)

**Comment by pieroproietti** [comment]
Probably I will try to move the eggs mountpoint from `/home/eggs/mnt` to `/mnt/eggs` more logic and clean.

**Comment by zDEFz** [comment]
**Edit** I forgot to above list the most important step to list - to cd in the mounted folder...

I will make another recording. I try in the VM now too.
Could reproduce. Uploading to my domain. 

Including the installation. Could couple of couple min if wanted.
Here you go:

https://up.tail.ws/2023-10-10%2019-56-37.m4v

Btw, the reason I didnt use your github page is because I don't know where the installation part for ubuntu is on your page. But anyways, the software is really useful.

**Comment by zDEFz** [comment]
Hey :) Did you find time to reproduce? I mean I just did in the VM. 
But >maybe< I should start to dig into your code and come up with a solution on my own.

**Comment by pieroproietti** [comment]
Hi @zDEFz 

sorry for the delay, I am very busy these days and, I think you can understand me, with porting eggs on arm64 architecture and using it on Raspberry hardware.

I am well on my way and have managed to generate some ISOs on my raspberry, I talk about them [here](https://penguins-eggs.net/blog/triple-somersault).

If you found the solution, anyway share it, I will definitely make use of it.

Have nice week end
