### ISSUE TITLE
Ubuntu Lunar 23.04 - broken update - easy fix var could not be initialized USER USER USER USER USER USER USER

### ISSUE THREAD

**Issue by zDEFz** [pieroproietti/penguins-eggs-legacy#306]
Breaks sources.list install software and creates a yolk file thats not helpful.

Fix is as follows after installation:

```
sudo rm /var/lib/apt/lists/partial/*
sudo mv /etc/apt/sources.list.backup /etc/apt/sources.list
sudo apt update -y && sudo apt upgrade -y
```

**Comment by pieroproietti** [comment]
Just making an egg-of-ubuntu-mantic-naked and installing it with krill to look that happen.

It seem all is OK!

![under-etc-apt](https://github.com/pieroproietti/penguins-eggs/assets/958613/68e44d2b-c57d-41da-bcfe-dd9ddfb76374)
