### ISSUE TITLE
.iso created with "sudo eggs produce --clone" does not copy the user's ".wine" folder

### ISSUE THREAD

**Issue by rodrigocabraln** [pieroproietti/penguins-eggs-legacy#314]
Most of the configurations were copied but the .wine folder  not

**Comment by pieroproietti** [comment]
Hi @rodrigocabraln 

just testing... with the new version eggs-9.6.14 the problem is solved, was caused on a too restrictive exclude.list.

**Comment by williamblair333** [comment]
On version 9.6.21, using ubuntu 22, all of my wine applications were broken after the transfer.  The .wine folder was missing.  Your product seems to be fine (yes, it's a little weird too :-) ), otherwise.

**Comment by pieroproietti** [comment]
OK, I think with the version 9.6.22  and more again with 9.6.23 I just published this problems are overcome.

I divided the exclude.list  in 3 parts: exclude.list.template, exclude.list.custom, exclude.list.homes and exclude.list.usr.

Default eggs don't use them if not that is inside the exclude.list.template itself, to add the others just add `--filters custom` or `--filters custom homes` and so on.

The problem for wine is we filter it on homes the line, you can also remove it on the exclude.list.homes or comment it.

`home/*/.wine`

Happy hacking
Piero
