### ISSUE TITLE
Add Nixos Support?

### ISSUE THREAD

**Issue by nixinator** [pieroproietti/penguins-eggs-legacy#318]
Cool project.

Any nixos support on the future road map?

**Comment by pieroproietti** [comment]
Hi @nixinator ,

if someone from nixos come, why not?

The biggest problems about differents distros are package managers: apt, pacman, rpm, etc. Then in some cases differents packages names and differents paths.

Here I'm organized with class [distro.ts](https://github.com/pieroproietti/penguins-eggs/blob/master/src/classes/distro.ts), where assign same variables depending on the distro, then in [family](https://github.com/pieroproietti/penguins-eggs/tree/master/src/classes/family) there are differents scritps:  [debian.ts](https://github.com/pieroproietti/penguins-eggs/blob/master/src/classes/family/debian.ts), [archlinux.ts](https://github.com/pieroproietti/penguins-eggs/blob/master/src/classes/family/archlinux.ts) but also `fedora.ts` and `suse.ts` (they are actually NOT used and probably not working).

To extend eggs to nixos - but also to other distributions - what we should do is to add a `nixos.ts` script in family - perhaps will be better to rename to families - and check on the sources where we must call it.

This can be an example, from [pacman.ts](https://github.com/pieroproietti/penguins-eggs/blob/1a9a2feacc49e5c36423facd5ba76b7aae23910c/src/classes/pacman.ts#L102).

Of course the same can apply to fedora and suse, they are present just from the start, but never used.

I hope someone come to help.

**Comment by nixinator** [comment]
thank you for a kind and welcoming reply!

i will delve into the repo and deploy it on one of the imperative linux distributions.

I will check if we have all the dependencies in nix  and see if the package you use are there.

nix is a build system, so it's very good at building images for all sorts or purposes from a single 'configuration.nix' file, so i may be able to leverage this depending on how you 'build bootable' images.

i don't have much time left, but hopefully i can allocate some time soon.

I'd love see a nixos lay a egg.
