### ISSUE TITLE
Will This Work With A VM Installation

### ISSUE THREAD

**Issue by williamblair333** [pieroproietti/penguins-eggs-legacy#321]
I have a qcow2 installed via virt-manager and was wondering if I can create a live installer on usb stick with eggs.  So far not having any luck.  I wanted to ask before submitting a detailed issue.  Thanks.

**Comment by pieroproietti** [comment]
I work on a Proxmox VE workstation, and usuall I can add an USB card from the host and use it on the VM, but I'm not too expert on KVM, generally I did that with the Proxmox GUI .

![installing-usb key-on-vm](https://github.com/pieroproietti/penguins-eggs/assets/958613/1846dd21-6823-4995-b1ec-1863720cd9fc)

**Comment by williamblair333** [comment]
I got it to work and pushed an install to a desktop computer from the usb stick.  Thanks.
