### ISSUE TITLE
[BUG] kernel not found on `/live/initrd-img-xxxx

### ISSUE THREAD

**Issue by sunuazizrahayu** [pieroproietti/penguins-eggs-legacy#326]
v 9.6.24: kernel not found when try using live, it seems that kernel not copied to `/live` dir on ISO

i try to build with debian netins on virtualbox

**Comment by pieroproietti** [comment]
It seem your system have initrd.img-6.1.0-16-amd64 not under /boot, but under /boot/grub.

I don't know why, for example your /initrd.img is a link on /boot/initrd.img-6.1.0-16-amd64.

In all the ways, probably a simple `sudo cp /boot/grub&initrd.img-6.1.0-16-amd64 /boot` will solve the problem.

**Comment by pieroproietti** [comment]
![sunu](https://github.com/pieroproietti/penguins-eggs/assets/958613/3fb3dd00-b1ce-4650-aee4-43a2b899b9e4)

It seem your system have initrd.img-6.1.0-16-amd64 not under `/boot`, but under `/boot/grub`.

I don't know why, for example your `/initrd.img `is a link to `/boot/initrd.img-6.1.0-16-amd64`.

In all the ways, probably a simple `sudo cp /boot/grub/initrd.img-6.1.0-16-amd64 /boot` will solve the problem.
