### ISSUE TITLE
EndeavourOS with dracut, penguin-egss install mkinitcpio and create conflicts

### ISSUE THREAD

**Issue by GjMan78** [pieroproietti/penguins-eggs-legacy#328]
On an EndeavorOS system with btrfs+luks, dracut and grub installing penguin-eggs also installs mkinitcpio which creates conflicts in kernel updates.

More details: https://forum.endeavouros.com/t/black-screen-when-kernel-update/49649/4

**Comment by pieroproietti** [comment]
Yes, 

you are right, at the moment eggs support just mkinitcpio, not yet dracut.

So, if you need eggs, you can choose:
* remove dracut;
* remove eggs;
* collaborate on the project.

Sorry for inconveniences.
