### ISSUE TITLE
eggs >>> Cannot find: /etc/penguins-eggs.d/exclude.list.d/exclude.list.template.

### ISSUE THREAD

**Issue by xmb9** [pieroproietti/penguins-eggs-legacy#334]
happened after updating eggs for the first time since december

**Comment by xmb9** [comment]
on debian 12

**Comment by xmb9** [comment]
nevermind, i think i fixed it by copying the appropriate files from /usr/lib/penguins-eggs/conf

**Comment by pieroproietti** [comment]
Just remove `/etc/penguins-eggs.d` and reconfigure eggs with `sudo eggs dad -d`.

Just now I saw you solved the problem alone. Great!
