### ISSUE TITLE
Does this work on Gentoo?

### ISSUE THREAD

**Issue by ghost** [pieroproietti/penguins-eggs-legacy#337]

**Comment by pieroproietti** [comment]
@NokoPlays unfortunately no. 

Will be probably possible to same gentoo developer to bring eggs on gentoo, the same for others distros, but at the moment we are limited to Arch/Debian/Devuan/Majaro and Ubuntu.

**Comment by ghost** [comment]
ok should i close this?

**Comment by pieroproietti** [comment]
Ok
