### ISSUE TITLE
Manjaro failed to start load kernel modules

### ISSUE THREAD

**Issue by shah-newaz** [pieroproietti/penguins-eggs-legacy#340]
Hi, since the latest upgrades (starting from 9.6.34), I'm getting "Failed to start Load Kernel Modules" See 'systemctl status systemd-modules-load.service' on live USB.

Note: I upgraded my kernel to 6.7 (was 6.6 LTS on fresh Manjaro install).
Note: I have an Nvidia graphics card. 

Is there a way I can build a generic ISO without proprietary drivers? If you know how I can remove proprietary drivers from kernel, I'll do that if needed.

As always, thank you so much for the continued great work!

**Comment by shah-newaz** [comment]
P.S. I was facing the same issue with Garuda Linux

**Comment by shah-newaz** [comment]
Update: The load kernel modules error is gone after
 I removed nvidia drivers (proprietary) but the boot is still stuck after "[started] Modem Manager" forever. No errors ( I removed quiet splash to see the logs).

Also, tried with ibt=off flag in kernel params.

No luck yet.

**Comment by pieroproietti** [comment]
Hi @shah-newaz 

A temporary work around can be remove nvidia from your system, create the ISO and put yours drive back. Eggs use the configuration of the janitor at last.

Of course will be better to have Is owen configuration.

**Comment by shah-newaz** [comment]
@pieroproietti Thanks for the reply! Tried that with no luck as well.. How do I know exactly what is failing?

**Comment by shah-newaz** [comment]
It does not let me into another tty by pressing ctrl + alt + F2,3 etc

**Comment by shah-newaz** [comment]
I'm suspecting it could be the window manager. Just tested that it's booting fine on VirtualBox..

**Comment by shah-newaz** [comment]
So, turns out, it's finding one of the network devices down. It says enp3s0 link is down and then the kernel panics. The original Manjaro image doesn't have this issue. Reading from different sources, one of the guys said it's related to nvidia GPU fans not turning on automatically. I remember Manjaro runs mwhd during the boot process to auto detect graphics hardware and initiate them. Maybe I need to do similar?

![20240312_180036](https://github.com/pieroproietti/penguins-eggs/assets/11506530/88445630-9c21-48b4-b9c0-4c2293fe33c4)

**Comment by shah-newaz** [comment]
So, I figured out.. It was my latest kernel that didn't have the driver for my network adapter.

For people facing similar issue in the future where your boot is stuck without any error, do these steps to identify the issue:
- Edit boot option (press e at the Penguins Eggs boot menu and edit the entry.
- Remove "quiet splash" from the boot flags and edit loglevel=7 instead of 0 to make logs verbose.
- Check the logs to the end and see what's making your kernel panic.
- On Manjaro, you can easily change kernels. Choose the LTS kernel to be on the safe side and install necessary drivers. Check Hardwarw Configuration section of Manjaro Settings manager to check what drivers you are missing.

Hope this helps someone!

This is not a Eggs specific problem. Closing it.

Thanks a lot @pieroproietti for the help and excellent project.
