### ISSUE TITLE
Cryptedclone does not copy luks file into ovarium

### ISSUE THREAD

**Issue by markoceri** [pieroproietti/penguins-eggs-legacy#341]
I'm using the version _9.6.34_ and I'm encountering the following issue while creating an egg with the following prameters:

`sudo eggs produce --cryptedclone --verbose`

![cryptedclone-luks-issue](https://github.com/pieroproietti/penguins-eggs/assets/16639103/f479f8fc-b679-4d44-b5fb-0a708325eb8d)

The LUKS file is being moved to a path that does not exist.

Upon examining the code, I noticed that the destination path where the code intends to move the LUKS file is incorrect (specifically, _iso/live_). In fact the destination path is concatenated with the value of the variable _this.ovarium_ , which is never assigned and initially an empty string.

Reviewing the commit history, I observed that in this commit [579be32](https://github.com/pieroproietti/penguins-eggs/commit/579be326ced92a6a7c6ba469f088ca19ddc21ab9) the _this.ovarium_ variable was introduced, replacing the variable _this.settings.work_dir.ovarium_ 

I’m not sure why the variable _this.ovarium_ is used instead of _this.settings.work_dir.ovarium_, and in what scenarios the _this.ovarium_ variable is intended to be useful.

Can someone who has a broader idea of ​​the project help me?

Thanks

**Comment by pieroproietti** [comment]
Hi Marco,
It's a bit I don't use cryptedclone, sencerelly not remember well the code, if not in general way. 

That you say sound like, I duplicate the variable, and can be possible becouse 3/4 months ago, when introduced the possibility of remote mount to build the ISO, I changed the "nest" in the way now is.

That to say, during the week I'm too busy and don't have way to check it, but on the week end I will give a look and tell you or change it.

Thanks

**Comment by pieroproietti** [comment]
https://github.com/pieroproietti/penguins-eggs/blob/959d96d562d6b44a5c9df51a73c3106a43d5fa3c/src/classes/ovary.ts#L338

LUKS file must to go on /home/eggs/.mnt/iso/live

**Comment by markoceri** [comment]
Thanks for your effort @pieroproietti, I made you a pull request [#343](https://github.com/pieroproietti/penguins-eggs/pull/343) to fix this issue

**Comment by pieroproietti** [comment]
Grazie Marco l'ho già inclusa. 

Mi sembra che va bene, non ho rifatto il pacchetto  ma credo che tu non abbia problemi, in ogni caso basta che usi: pnpm deb.

**Comment by markoceri** [comment]
Si oramai `pnpm deb` è fisso nella mia bash hystory :smiley:

Grazie a te Piero
