### ISSUE TITLE
eggs produce --clone always resets exlude.list

### ISSUE THREAD

**Issue by shah-newaz** [pieroproietti/penguins-eggs-legacy#342]
My /etc/penguins-eggs.d/exclude.list gets reset as soon as I run eggs produce --clone.
Version: 9.6.36

**Comment by shah-newaz** [comment]
Update: this problem occurs even when the file is kept at a custom directory! I placed it to /home/user/.confg/eggs/exclude.list and it still reset that file :D

**Comment by pieroproietti** [comment]
I Will check, thanks.

**Comment by markoceri** [comment]
I try to guess @shah-newaz 

The _exclude.list_ file is assembled every time you run the _produce_ command. It is a merge of the files that are inside the directory _/etc/penguins-eggs.d/exclude.list.d_

If you want to put your custom path to ignore and if you want to make the changes permanent you should use the file _exclude.list.custom_

I hope this can be helpful to you

**Comment by shah-newaz** [comment]
Thanks @markoceri ! Going to try that!

**Comment by markoceri** [comment]
Remember to use the command in this way to include custom excludes in the final file, otherwise the custom exclude file will not be included.

`sudo eggs produce --filters=custom`

**Comment by shah-newaz** [comment]
Thank you so much @markoceri ! That was it! Maybe I missed the doc. Apologies.

Works perfectly.
Non-issue.
