### ISSUE TITLE
Eggs is not removed from release installs

### ISSUE THREAD

**Issue by code8buster** [pieroproietti/penguins-eggs-legacy#345]
When installing from an egg produced with the --release switch, eggs krill only removes calamares from the installed system and not penguins-eggs.

version: 9.6.36

**Comment by pieroproietti** [comment]
This was intended, but we can change the politics.

**Comment by code8buster** [comment]
> This was intended, but we can change the politics.

eggs produce -h indicated otherwise

https://github.com/pieroproietti/penguins-eggs/blob/master/src/commands/produce.ts#L32

**Comment by pieroproietti** [comment]
Actually penguins-eggs is removed.
