### ISSUE TITLE
Unattended noninteractive installation does not read krill.yaml

### ISSUE THREAD

**Issue by code8buster** [pieroproietti/penguins-eggs-legacy#349]
Edit your yaml users section to be something other than artisan/evolution
Invoke `eggs krill -un` and watch the installer totally ignore that section

If you don't fix it, I will when I can get around to it. Just filing issues as they crop up while I use eggs and get familiar with it.

**Comment by pieroproietti** [comment]
OK, 

I fixed it on the branch [syncto](https://github.com/pieroproietti/penguins-eggs/tree/syncto).

I removed some stuffs intended to get configurations on internet, inside penguins-wardrobe, but really is better to work in plain way.
