### ISSUE TITLE
cryptdevice parameter is not dropped on new install

### ISSUE THREAD

**Issue by code8buster** [pieroproietti/penguins-eggs-legacy#350]
cryptdevice parameter is not dropped when doing a "standard" type installation

egg was produced from an encrypted-root Arch Linux, so it's just carrying the parameter over. It was necessary for mkinitcpio to boot properly on that machine, but no longer.

The new root is still found via UUID, it's just odd that grub kept this parameter

**Comment by pieroproietti** [comment]
Hi @code8buster 

I'm just working on syncto and syncfrom on the branch [syncto](https://github.com/pieroproietti/penguins-eggs/tree/syncto).

I rewrote completely syncto, but again don't solve same problens:
* rebooting the system and giving `sudo eggs syncto`, work and produce `luks-eggs-data`. 
* rebooting the system and giving `sudo eggs --crypted clone` who simply call `eggs syncti` to create the same `luks-eggs-data` to save users' home and /etc/group, /etc/passwd and /etc/shadow breack during mksquashfs.

Actually I will give up, for two days, but want to implement the new version, before I forgot that I did.

**Comment by pieroproietti** [comment]
OK, 

> cryptdevice parameter is not dropped when doing a "standard" type installation
> 
> egg was produced from an encrypted-root Arch Linux, so it's just carrying the parameter over. It was necessary for mkinitcpio to boot properly on that machine, but no longer.
> 
> The new root is still found via UUID, it's just odd that grub kept this parameter

That's the way to remove it? eggs just use the same configuration of the janitor... so, that I must to delete/add?

**Comment by code8buster** [comment]
Yes I imagine so.
Eggs must do some replacement after the fact during the bootloader step, right? Otherwise it would be stuck with the same UUID for root from the old machine that produced the egg. Then it would never boot.

Probably in that step, do a check if installation type != fullencrypt and if yes, drop cryptdevice from the configuration.
