### ISSUE TITLE
DNS Settings

### ISSUE THREAD

**Issue by ghost** [pieroproietti/penguins-eggs-legacy#351]
Hello,
i use the Version 9.6.37 on Debian without calamares (only cli).
The DNS Settings are not correctly applied.
It defaults to 127.0.0.53.
I tried this workaround:
`
sudo rm /etc/resolv.conf
`
`
sudo ln -s usr/lib/systemd/resolv.conf /etc/resolv.conf
`
Any other workaround or solution? Or am I making a mistake here?

Thanks :)

**Comment by pieroproietti** [comment]
Hi @lyca-knight 

perhaps I can include your workaround on krill, just for distros using systemd

This is the [code](https://github.com/pieroproietti/penguins-eggs/blob/syncto/src/krill/modules/network-cfg.ts), seem I used your workaround before to know it, but was not sure to apply it.

**Comment by ghost** [comment]
Hey :)
thank you.
I have been very busy these days and have only now had time to test the changes
should it not be the following?
`
if (this.network.addressType !== 'dhcp')
`
At least that works for me 

This is the code from version 9.6.9:

`
  if (this.network.addressType !== 'dhcp') {
    const file = this.installTarget + '/etc/resolv.conf'
    let content = '# created by eggs\n\n'
    content += 'domain ' + this.network.domain + '\n'
    for (const element of this.network.dns) {
      content += 'nameserver ' + element + '\n'
    }
    Utils.write(file, content)
  }
`
