### ISSUE TITLE
Feature Request: Specify compression command/parameters

### ISSUE THREAD

**Issue by code8buster** [pieroproietti/penguins-eggs-legacy#353]
This is low priority, maybe it is interesting to have some customize ability with compression?
For instance, maybe you don't want almost uncompressed zstd level 1 but are too impatient for the max, or maybe you want to compress even higher than what xz --max allows.

I'd like it to be somewhere in the middle, around zstd 8, but being able to change it based on my mood would be very nice.

Thanks for your responsiveness to other issues Piero

**Comment by pieroproietti** [comment]
Just added a new flag to: `sudo eggs produce --pendrive`, in this way we use zstd 1M Xcompression-level 1

I think in this way, we can have an accettable balance from complety and versatibility.

When you need to use the ISO with a pendrive, just produce it with this option: `sudo eggs produce --pendrive`
