### ISSUE TITLE
Missing exclude list, ppa fail on Devuan 5

### ISSUE THREAD

**Issue by Paculino** [pieroproietti/penguins-eggs-legacy#356]
Hello, today I tried to make an iso of my Devuan 5 system for the first time after migrating from Debian 12. I ran `sudo eggs produce` both with and without --clone, but each time, the list for excluded directories was missing. So, I initially ran `sudo apt reinstall eggs` and it reinstalled, but I had the same issue, and then I tried to purge eggs and reinstall. I was able to purge, but have not been able to reinstall since then. At first, I ran `curl -fsSL https://pieroproietti.github.io/penguins-eggs-ppa/KEY.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/penguins-eggs.gpg
echo "deb [arch=$(dpkg --print-architecture)] https://pieroproietti.github.io/penguins-eggs-ppa ./" | sudo tee /etc/apt/sources.list.d/penguins-eggs.list > /dev/null`, but /etc/apt/sources.list.d was not found, then I tried again and there was issue with two signs for the ppa, so I cleared /etc/apt/sources.list/d/ and tried again. I tried the clone method next, but running get-eggs.sh did nothing (even after updating apt) and then line 93 of ppa.sh failed as command eggs was not found. Each time output came, the original gpg was overwritten.

**Comment by pieroproietti** [comment]
Hi @Paculino 

Honestly, it's hard to give you an answer, the versions of eggs follow each other quite rapidly, and--personally--I tend not to remember the problems with each specific version.

Although I have not tested eggs on Devuan for some time, I am not aware of any particular problems

A word of advice, try from scratch with an updated version.

**Comment by Paculino** [comment]
I was attempting to do that but adding the ppa failed.

**Comment by pieroproietti** [comment]
Ok,
I'm trying to create a naked devuan version, starting from `devuan_daedalus_5.0.1_amd64_netinstall.iso`.

Once installed, minimal version, I just:
* su 
* apt install sudo git
* /usr/sbin/adduser [myuser] sudo

Then reboot and:
* git clone https://github.com/pieroproietti/get-eggs
* cd get-eggs
* sudo ./get-eggs

and all seem working!

In a while I will publish the naked result ISO on [sourceforge](https://sourceforge.net/projects/penguins-eggs/files/ISOS/devuan/daedalus/)

**Comment by pieroproietti** [comment]
OK @Paculino 

stimulated from You I did all Devuan 5 daedalus versions, both [amd64](https://sourceforge.net/projects/penguins-eggs/files/ISOS/devuan/daedalus/amd64/) and [i386](https://sourceforge.net/projects/penguins-eggs/files/ISOS/devuan/daedalus/i386/), with not issues. I hope this can help you and many others passionate about [Devuan](https://www.devuan.org/).

Cheers

BTW: 

You can install them in naked version, without any GUI and customize later in the way you want. To install the naked versions just boot the ISO and run: `sudo eggs install -un`, Do this only in clean computers or in VMs, becouse this will erase all the installation disk.

If you see this too difficult or too risky, you can install colibri versions using calamares, then customize it.

**Comment by Paculino** [comment]
Thank you for the rapid help, but I just found a work-around; the sourceforge .deb seems to work for me (I have made it to the filesystem generation step). The only thing I did not try was deleting the old eggs folder, but that is no issue when installing from sourceforge. Maybe my apt is messed up and that is why I had trouble; I was unable to change the pin priority for one repo recently.

**Comment by GuestSneezeOSDev** [comment]
What Kind Of Distro Is It Derived From?

**Comment by Paculino** [comment]
Devuan is debian-based, GuestSneezeOSDev. According to [debdistdiff](https://gitlab.com/debdistutils/debdistdiff), 62827 packages were the same, 113 were missing, 464 were altered, and 1288 were added between [bookworm and daedalus](https://debdistutils.gitlab.io/debdistdiff/devuan-vs-debian/diff-bookworm-daedalus.txt).

I'll also close with this comment since it appears to be a problem with my apt config or something, as it was not a reproduced issue.
