### ISSUE TITLE
No new release for Arch since 9.6.41

### ISSUE THREAD

**Issue by shah-newaz** [pieroproietti/penguins-eggs-legacy#361]
Hi, there is no new release since 9.6.41 which seems to be a broken version. It has changed exclude/filter architecture but the help commands still show old ones. Unfortunately, none works and image creation fails without any helpful output. Really need to use the latest 9.7.4 but nothing on yay/aur etc after waiting last few weeks.

**Comment by pieroproietti** [comment]
Hi @shah-newaz 

you're right, unfortunately I haven't had time and way to deal with arch lately and I think there was also a problem. 

I will try to make the release for arch.

**Comment by pieroproietti** [comment]
Just released. 

https://aur.archlinux.org/packages/penguins-eggs

**Comment by shah-newaz** [comment]
Thank you so much! :heart:
