### ISSUE TITLE
ubuntu 24.04 user profile deleted when installing using a produce --clone iso

### ISSUE THREAD

**Issue by sldfrk** [pieroproietti/penguins-eggs-legacy#362]
hello all, I tried using eggs produce --clone and then booted the created image and all works well up to that point then when I run eggs install -u the cloned user gets deleted and replaced with the krill user. the data I have in the home folder gets copied over just fine. I have also tried eggs install with the same result.

**Comment by sldfrk** [comment]
for future reference I downloaded the 9.7.4 .deb package version from sourceforge and manually installed any missing packages through apt. that seems to have fixed my issue on ubuntu 24.04 server.

**Comment by pieroproietti** [comment]
I few tested eggs on the last Ubuntu - really busy latelu - but it's nice to know it work.  Thanks
