### ISSUE TITLE
error producing eggs after apt update / upgrade

### ISSUE THREAD

**Issue by casousavng** [pieroproietti/penguins-eggs-legacy#363]
Good afternoon, I'm building a live distribution of Linux Debian 12 for a college project. When installing penguins eggs everything went well and I was able to do the first iso without any problems. After that I adapted my system with the software I wanted and did an apt update and upgrade where it updated the latest version of the kernel. When trying to create the iso I get several chroot errors in several files and I noticed that both initrd and vmlinuz have different names, even after eggs produce --default I can't get around the problem. I tried manual editing of the yaml but it still gives an error when creating and the iso file is left without a kernel so it won't start even in live mode

**Comment by casousavng** [comment]
my yaml look like the one you post on another issue and its all ok but i get erros like "error on command: chroot /home/eggs/.mnt filesystem.squashfs rm /home/live -rf, code 1 (this is one of them), the other ones are all related do filesystem.squashfs
it still creates da distro but i'm unable to boot it

**Comment by casousavng** [comment]
i'm using vmware on windows, tried in a vmware on Mac m1 and works fine

**Comment by casousavng** [comment]
i open the iso made on windows vm machines and they dont have the inittrd file on live folder, thats strange because i already have done some in that system

**Comment by pieroproietti** [comment]
Hi, sorry to be so much on delay, probably not noted your issue.

The only problem of eggs with update, can come from the kernel, when you add a new kernel, you must reboot and renew the configuration: sudo eggs dad -d

I don't know if this Is your case, and hope you already solved the problem.

**Comment by casousavng** [comment]
HI pierro, already tried it with the same result. I was building a distro for my college as a project and started another one. This was the easy way to do. thanks anyway
________________________________
De: Piero Proietti ***@***.***>
Enviado: 26 de maio de 2024 21:45
Para: pieroproietti/penguins-eggs ***@***.***>
Cc: Carlos Sousa ***@***.***>; Author ***@***.***>
Assunto: Re: [pieroproietti/penguins-eggs] error producing eggs after apt update / upgrade (Issue #363)


Hi, sorry to be so much on delay, probably not noted your issue.

The only problem of eggs with update, can come from the kernel, when you add a new kernel, you must reboot and renew the configuration: sudo eggs dad -d

I don't know if this Is your case, and hope you already solved the problem.

**Comment by pieroproietti** [comment]
Same time ago  @aosucas499 make a Linux for school using always eggs, he was one of the first to collaborate. This is his git page: [guadalinex](https://github.com/aosucas499/guadalinex). Have good luck!
