### ISSUE TITLE
Accidently tried to delete the /home/eggs/.mnt dir and broke my install

### ISSUE THREAD

**Issue by ZanzyTHEbar** [pieroproietti/penguins-eggs-legacy#370]
I was making a new iso, used this tool many times before and was fine, and i hit complete on the terminal completion without thinking (was late) - and ended up breaking the symbolic links to pretty much everything eggs was managing. I have no idea how, but when i attempted to remove the `/home/eggs/.mnt` directory everything borked and now my pc won't post. 

Of course, i can boot from a backup - but i am wondering if there is a mechanism to fix this without having to reimage my machine. I have checked via a live cd - my disk is fine, partition is intact, and all of my files are present. It seems just hard links and symbolic links have been broken. Way too many to fix manually.

**Comment by pieroproietti** [comment]
Hi @ZanzyTHEbar 

When eggs produces abn ISO, the entire filesystem is mounted --bind under /home/eggs/.mnt/filesystem.squashfs, deleting ./mnt risks deleting the disk as well. Normally the system rejects, displays mounts and exits. 

To tell you more I would have to repeat the experiment on a VM.

Holy backup!

**Comment by pieroproietti** [comment]
Hi @ZanzyTHEbar 

I tried to repeat your case: 

I ran the command: `sudo eggs produces`, and waited until the entire filesystem was mounted under `/home/eggs/.mnt/filesystem.squash`.

At this point I ran - in another terminal - the command: `sudo rm /home/eggs -rf`.

The first time I aborted immediately after the first errors appeared, the second time I waited for the process to finish.

![results](https://github.com/pieroproietti/penguins-eggs/assets/958613/f55d8ce8-f992-4e78-bf85-03841cb5c911)


Both the first time and the second time, I successfully rebooted the system.

## Warning: if you want to repeat the experiment do it exclusively on a virtual machine where you do NOT have data: the experiment can corrupt the whole system.

**Comment by ZanzyTHEbar** [comment]
I believe you - but that's not what happened for me. I spent the better part of today getting a new image up to speed.

**Comment by pieroproietti** [comment]
Of course,  I just tried to replicate it and, I really was waiting to break
the system.

I'm sorry for your problem.

Il dom 7 lug 2024, 20:29 DaOfficialWizard ***@***.***> ha
scritto:
