### ISSUE TITLE
Force Live ISO to boot into desktop without options?

### ISSUE THREAD

**Issue by memory-colors** [pieroproietti/penguins-eggs-legacy#371]
Hello!

Been a while since I've upgraded, so maybe I am mistaken, but on the older (9.xx) version I was using, booting with the newly created Live ISO would simply bring you to the desktop. The current version takes you to a page where you can select to install or boot the live ISO. 

I would much rather just boot into the desktop automatically. Is there a way to specify this during creation?

Thanks for your work!!

**Comment by pieroproietti** [comment]
Hi @memory-colors 

From this point of view nothing Is changed from 9.x to 10.x. I suppose the difference Is coming from the differenti distros you are remastering. 

Thanks
