### ISSUE TITLE
calamares issue (waiting  a reply)

### ISSUE THREAD

**Issue by LeGamermc** [pieroproietti/penguins-eggs-legacy#375]
on my distro im making i did
sudo eggs calamres --install 
and it fail at 
theme: eggs
eggs >>> Installing calamares.
eggs >>> Configuring calamares.
    Error: ENOENT: no such file or directory, open '/etc/calamares/modules/partition.conf'
    Code: ENOENT

**Comment by LeGamermc** [comment]
tiny side noteven if i add the modules it fail at mount 
![Capture d’écran du 2024-07-21 12-20-54](https://github.com/user-attachments/assets/416f2af4-f209-4785-8542-461ac810fe70)

**Comment by pieroproietti** [comment]
Please, add the distro and the version...  it's difficult to answer.

**Comment by LeGamermc** [comment]
welp its my own distro and its based of debian so its normaly supose to work as on a previous version of eggs it worked whitout any issue



> Please, add the distro and the version... it's difficult to answer.

welp its my own distro and its based of debian so its normaly supose to work as on a previous version of eggs it worked whitout any issue

so here the distro 

KernelOS 1.3 (supernova)

**Comment by pieroproietti** [comment]
Hi @LeGamermc 

sorry I don't answer soon, wirh KernelOS supernova I found this link https://github.com/droidzone/Supernova-Kernel, I think some special, customized kernel,

I hope you solved already the problem, but eggs base his recognition of the system on the command `lsb_release -a`, and me too... so, again can't answer you! 

Pardon
