### ISSUE TITLE
bug arch linux

### ISSUE THREAD

**Issue by coldfire03** [pieroproietti/penguins-eggs-legacy#380]
sudo eggs produce --clone
sudo: eggs: command not found, there was no package problem. after the update it gives this error.

**Comment by pieroproietti** [comment]
Hi @coldfire03  just solved on penguins-eggs 10.0.28-2, I uploaded same minutes ago.

I'm getting crazy with APKBUILD and PKGBUILD ... but survive!

**Comment by coldfire03** [comment]
Thank you, the problem is gone with the update. I wish you success in your work.
