### ISSUE TITLE
root/boot/vmlinuz-linux not exists!

### ISSUE THREAD

**Issue by hartmark** [pieroproietti/penguins-eggs-legacy#387]
I'm on arch linux.

How do I specify where to look for the files? I expected it to try look under `/boot` and not `root/boot`

Reproducing steps:
1. `yay penguins-eggs`
2. `sudo eggs produce`

output:
```
 E G G S: the reproductive system of penguins

      penguins-eggs       Perri's Brewery edition        ver. 10.0.33       
command: produce 

eggs >>> Config: you are on a graphic system, I suggest to install the GUI installer calamares.
? Want You install calamares? No
- creating configuration's files...
Due the lacks of calamares package set force_installer = false
root/boot/vmlinuz-linux not exists!

```

**Comment by pieroproietti** [comment]
I think yesteday I did same troubles with arch with v10.0.33, soon I will check better. 

As I remember 10.0.32 was OK.

**Comment by pieroproietti** [comment]
Today I update penguins-eggs-10.0.34-3 on [AUR](https://aur.archlinux.org/packages/penguins-eggs), seem to work, I use `makepkg -si` to create the package and in one hour or two the package will be build on [chaotic-aur](https://aur.chaotic.cx/)

On Arch I renew also calamares, now is calamares-v3.3.9,  you can install it with the command:
```
sudo eggs calamares --install
```

Sources for packages are on : [penguins-eggs-pkgbuilds](https://github.com/pieroproietti/penguins-eggs-pkgbuilds).

**Comment by hartmark** [comment]
It seems to still be same issue. I'm also ssh:ing into the host and there's no graphic system on that host.

```
eggs >>> Config: you are on a graphic system, I suggest to install the GUI installer calamares.
? Want You install calamares? No
- creating configuration's files...
Due the lacks of calamares package set force_installer = false
root/boot/vmlinuz-linux not exists!
markus@staropramen ~ % eggs --version
penguins-eggs/10.0.34 linux-x64 node-v22.7.0
markus@staropramen ~ % 


```

**Comment by pieroproietti** [comment]
OK,
I installed `archlinux-2024.09.01-x86_64.iso`, using archinstall, just added: `git` and `lsb-release`

After the installation, I:

* `git clone https://github.com/pieroproietti/get-eggs`
* `cd get-eggs`
* `sudo ./get-eggs`

Then:
* eggs love

And I get the ISO build.

After I tryed with yay, installed  `archlinux-2024.09.01-x86_64.iso`, using archinstall, just added: `git` and `lsb-release`

after reboot installed yay:

* `git clone https://aur.archlinux.org/yay.git`
* `cd yay`
* `makepkg -si`

then using yay, I installed penguins-eggs

At this point I installed calamares too, installing before  a stupid dependencies, you can check.

All go ok, and I get the ISO too... 

After that I read again your post and realize you was not using calamares.

Retry again, installing a new VM, installing yay and with yay installing penguins-eggs

**Comment by pieroproietti** [comment]
![this-is](https://github.com/user-attachments/assets/759050b9-b975-4bd9-be8a-3c82087e5bda)

This was the result.

Sorry, but can't replicate...

**Comment by hartmark** [comment]
I was using the AUR package
https://aur.archlinux.org/packages/penguins-eggs

So the reproducing steps would be this:
1. git clone https://aur.archlinux.org/penguins-eggs.git
2. cd penguins-eggs
3. makepkg -si
4. take a coffee
5. sudo eggs produce

**Comment by pieroproietti** [comment]
Hi @hartmark , 

good mornig, just drinking coffe!

Again I installed with archinstall, this are my configuration files:
* [user_credentials.json](https://github.com/user-attachments/files/16843605/user_credentials.json)
* [user_configuration.json](https://github.com/user-attachments/files/16843606/user_configuration.json)

then I cut and copy your commands.

## creating package
![Schermata del 2024-09-03 06-47-24](https://github.com/user-attachments/assets/15343004-b13f-4fe3-aa25-1299367ebb5c)

## producing
![Schermata del 2024-09-03 06-49-46](https://github.com/user-attachments/assets/ca42ee8c-dc92-4378-b318-baa5e7f54a4a)

## finishing coffee
I just added `lsb-release` and `git` to the default arch installation, choose ext4 as filesystem. 

Nothing special except - perhaps  - moka machine! :-)

![moka](https://upload.wikimedia.org/wikipedia/commons/4/4f/Moka_Express_Bialetti.png)

**Comment by pieroproietti** [comment]
@hartmark 

You can try get-eggs too, it's just a script

* `git clone https://github.com/pieroproietti/get-eggs`
* `cd get-eggs`
* `sudo ./get-eggs`
* follow the instructions.

Note: will add [Chaotic-AUR ](https://aur.chaotic.cx/) to your repository, so don't need to wait compilation.

**Comment by hartmark** [comment]
I haven't used Chaotic AUR before, I like idea that you don't need to build all packages yourself, especially on my weaker machines :)

I tried using the one from Chaotic AUR and I get the same issue that it complains about:
`root/boot/vmlinuz-linux not exists!`

**Comment by pieroproietti** [comment]
At this point I suspect something on your system... As I told before I tried on clean systems and go well. My doubs are on btrfs, not tested too much or simply don't remember well the tests made, but with clean systems go well.

**Comment by hartmark** [comment]
Aha, you might be onto something. My /boot is actually in a subvolume named @root so perhaps the @ is lost in the path.

The full path is /@root/boot

Perhaps one way would be to have get the mounted subvolume

```
% df /boot
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/nvme0n1p2 488252940 154681496 302187576  34% /
% mount | grep nvme0n1p2
/dev/nvme0n1p2 on / type btrfs (rw,relatime,compress=zstd:3,ssd,dis
card=async,space_cache,subvolid=260,subvol=/@root)
```

**Comment by pieroproietti** [comment]
Yes, I think this is the problem. 

I'm not so much used on btrfs, so use always ext4 to test and same problem arise...

Unfortunately manage to test for four distros and two filesystems it too much also for a passionate like me.

**Comment by pieroproietti** [comment]
The problem arise from [here](https://github.com/pieroproietti/penguins-eggs/blob/81e9c985d1498d59617c96a7f31147a5786e31dc/src/classes/utils.tsx#L156)

Any advise how to manage this better?

**Comment by hartmark** [comment]
```
% cat /proc/cmdline
BOOT_IMAGE=/@root/boot/vmlinuz-linux root=UUID=d8081ed1-cf04-4ba1-8
a6e-6da80cdfc6de rw rootflags=subvol=@root loglevel=3 quiet
% file /boot/vmlinuz-linux
/boot/vmlinuz-linux: Linux kernel x86 boot executable bzImage, vers
ion 6.10.8-arch1-1 (linux@archlinux) #1 SMP PREEMPT_DYNAMIC Wed, 04
 Sep 2024 15:16:37 +0000, RO-rootFS, swap_dev 0XC, Normal VGA
```

You could just remove everything between @ and / and trim off one extra slash

**Comment by pieroproietti** [comment]
I think in this way must to be OK, I will release it just for arch as 10.0.35-2, later I will release for the others.

```
      // btrfs: eg: /@root/boot/vmlinuz
      if (vmlinuz.indexOf('@')) {
         let subvolumeEnd = vmlinuz.indexOf('/', vmlinuz.indexOf('@'))
         vmlinuz = vmlinuz.substring(subvolumeEnd)
      }
```

OK, is on the air... https://aur.archlinux.org/packages/penguins-eggs

**Comment by hartmark** [comment]
Seems latest updated version fixed this issue.

I can now successfully run "sudo eggs produce"
