### ISSUE TITLE
Is it posible to copy the necesary files to boot live via RAM?

### ISSUE THREAD

**Issue by Cuphead74832** [pieroproietti/penguins-eggs-legacy#391]
Yeah, i know there is some distro (dont remember the name) that had a Copy-to-RAM feature, It allowed the live medium to work without the Installation medium always on (you STILL need the USB to install). This tool IS amazing i been using It for a few years now. Did some live testing enviroments, but i want to be able to RUN EVERYTHING from the RAM (like Windows PE or the Windows Installation enviroment) any ideas?

**Comment by pieroproietti** [comment]
Actually not, but I'm looking to use dracut to "capture" fedora, and as I see [dracut](https://fedoraproject.org/wiki/LiveOS_image) let this too.

**Comment by Cuphead74832** [comment]
> Actually not, but I'm looking to use dracut to "capture" fedora, and as I see [dracut](https://fedoraproject.org/wiki/LiveOS_image) let this too.

Maybe if i use the "toram" boot parameter?
