### ISSUE TITLE
How do i make my own naked (super-mininal) version of ubuntu latest??

### ISSUE THREAD

**Issue by Cuphead74832** [pieroproietti/penguins-eggs-legacy#393]
I saw on your sourceforge that you have a super-minimal version of ubuntu. I been wondering how do i do this myself? I like this tool mostly to create tiny live images that can easily boot on any media of my very OLD machines.

**Comment by pieroproietti** [comment]
It's simple enought... a little less on Ubuntu.

I start with server version and install minimal, then remove two packages: `cloud-init` and something like `needrestart`.

At this point, you can install git, clone get-eggs and run it to install penguins-eggs and all the necessary.

On Debian I make a minimal installation from netinstall iso.

On Arch: install it using archinstall, minimal installation, copy network from iso, add packages `git` and `lsb-release`, install it. Then clone and run get-eggs.

Fedora, minimal installation, then see [WAY-TO-FEDORA](https://github.com/pieroproietti/penguins-eggs/blob/master/DOCS/WAY-TO-FEDORA.md), there is not yet a package for it.

To go more lite, you can try [Alpine Linux](https://alpinelinux.org/) too. Follow [WAY-TO-ALPINE](https://github.com/pieroproietti/penguins-eggs/blob/master/DOCS/WAY-TO-ALPINE.md) or simply download an Alpine Linux naked.

**Comment by pieroproietti** [comment]
I'm installing to illustrate a new naked Fedora. 

I use Fedora becouse, unfortunately until now I was not able to create an rpm package for penguins-eggs for it.

Just i'm installing the minimal version, it's descrived on WAY-OF-FEDORA too.

After installed it, we need to install all the packages eggs need to build and produce ISOs, plus samething usefull for us, like bash-completion or zsh-completion.

The fastest way, is to get the ip of the machine, connect via ssh, the cut and copy this:

```
dnf -y install \
    bash-completion \
    biosdevname \
    cifs-utils \
    cryptsetup \
    curl \
    device-mapper \
    dmraid \
    dosfstools \
    dracut \
    dracut-live \
    fuse \
    git \
    iproute \
    iscsi-initiator-utils \
    jq \
    lsb-release \
    lvm2 \
    mdadm \
    nbd \
    net-tools \
    nfs-utils \
    nodejs \
    nvme-cli \
    overlayfs-tools \
    parted \
    pnpm \
    rng-tools \
    rpcbind \
    rsync \
    squashfs-tools \
    sshfs \
    syslinux \
    wicked \
    xdg-user-dirs \
    xorriso \
    zstd
```

After installed this packages, we can clone penguins-eggs:

```
git clone https://github.com/pieroproietti/penguins-eggs
cd penguins-eggs
pnpm i
./install-eggs-dev
```
Before to run ```eggs love``` is better rename our host, I usually put `naked` on `/etc/hostname` and add  a line `127.0.1.1 naked` on `/etc/hosts`.

When finish, we can just run: ```eggs love``` and build our fedora naked ISO.
