### ISSUE TITLE
Last question (hopefully) How do i modify the grub.cfg before generating an ISO?

### ISSUE THREAD

**Issue by Cuphead74832** [pieroproietti/penguins-eggs-legacy#394]
I need to add extra stuff in the grub.cfg thing but i want to add it before i do the eggs produce command. How do i do that?

**Comment by pieroproietti** [comment]
You can change grub.cfg as you want on your janitor system, eggs will copy your configuration on filesystem.squashfs and  your configuration will be unpacked with all the others on your new system.

**Comment by Cuphead74832** [comment]
So does this update the grub.cfg from the Live Iso ([https://github.com/pieroproietti/penguins-eggs/blob/master/addons/eggs/theme/livecd/grub.main.cfg](url)) too?

**Comment by pieroproietti** [comment]
To change the grub.cfg on the live, you can edit [here](https://github.com/pieroproietti/penguins-eggs/tree/master/addons/eggs/theme/livecd) or create a theme and do that inside it.

**Comment by Cuphead74832** [comment]
Im using the PPA how do i do this with a pre-install in my OS?

**Comment by Cuphead74832** [comment]
I just modified It after creation. Thats the solution
