### ISSUE TITLE
Anyways to unattend production?

### ISSUE THREAD

**Issue by Cuphead74832** [pieroproietti/penguins-eggs-legacy#398]
Im running eggs produce by default but everytime i start It i have to interact with confirmation dialogs but would like to know if there IS a way to tell it to just YES everything.

**Comment by Cuphead74832** [comment]
Nevermind could not unattend BUT i found my ways!
Thanks for producing this amazing tool i have created about 5 distro this month!

**Comment by pieroproietti** [comment]
Thanks for the compliments, very happy to know you solved your problem alone.

I read your message this morning, but I had to leave.

I use usually `sudo eggs produce --unattended --nointeractive`, I think this is that you want.
