### ISSUE TITLE
Does an egg of an egg not work?

### ISSUE THREAD

**Issue by jon-bit** [pieroproietti/penguins-eggs-legacy#422]
I made an egg iso a while back, installed it on a virtual machine, and tried to re-do it and make another egg iso. For some reason I am not sure why, but it will not boot into another virtual machine. I have tried this on physical hardware too, however no luck. I just don't know what's going on at this point, but I can only guess there's something wrong with the packages I installed. But I don't know which one that may be. Maybe libdrm, but I have completely uninstalled that one (or at least the one I built myself. Their are sill apt packaes). 
I say that because of this screen shot:
![Screenshot from 2024-11-23 18-22-40](https://github.com/user-attachments/assets/f0dc3a41-9420-48ba-bffa-891d9ae1b7e4)

any idea @pieroproietti ?

**Comment by pieroproietti** [comment]
just a suggestion, perhaps stupid - I suppose your tryed it - virtualbox guest additions?

**Comment by jon-bit** [comment]
One sec. I'll try

**Comment by jon-bit** [comment]
OH! sorry, I'm using QEMU.

**Comment by jon-bit** [comment]
hmmmmmm. well I just tryed it any way and got this

VirtualBox can't enable the AMD-V extension. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_SVM_IN_USE).

**Comment by jon-bit** [comment]
OK.... Well I fixed it but now I get this on Vbox

![Screenshot from 2024-11-24 01-02-41](https://github.com/user-attachments/assets/c3fd6a39-f9e0-4fd4-99d0-128c471ce721)

**Comment by pieroproietti** [comment]
That to say: just don't know!

Sometime, when I end in a close hole, just went back from the original and rebuild all.  A long way sure...

**Comment by jon-bit** [comment]
:( OK I'll try....

**Comment by jon-bit** [comment]
Well I did it on another VM and it did not work. I might be because of what I said. I will try something else just to be sure. I report back when I do.

**Comment by jon-bit** [comment]
is their anyway to %100 uninstall eggs when installing from the install script? That might help a little with debugging.

**Comment by jon-bit** [comment]
OK. I don't know why but yes, It is the system. 
Rebuilding from scratch.... :(

**Comment by jon-bit** [comment]
OK I don't know why now but I rebuilt and I am getting this agian:

![Screenshot from 2024-11-25 03-08-11](https://github.com/user-attachments/assets/0ac75988-9765-4d5e-8c72-94a98953d646)

No clue what is happening. @pieroproietti any ideas? I'll give you what Installed if you want.

**Comment by pieroproietti** [comment]
I don't remembe that distro/version are you using... I don't think I can solve the problem just with the list of the packages installed, if you want and can share your ISO and can try to understand that happen. 

eggs, do the usual things did before: 
* create under /home/eggs/.mnt/iso the structure for the CDROM/DVD
* create initramfs under /home/eggs/.mnt/iso/live (will use: mkintramfs, mkinitcpio, dracut or mkinitfs depending on the distro in use) and copying vmlinux on /home/eggs/.mnt/iso/live;
* configure /home/eggs/.mnt/iso/boot and /home/eggs/.mnt/isolinux for the ISO;
* create a live filesystem under /home/eggs/.mnt/filesystem and the scripts: `bind`, `ubind`. `mksquashfs` and `mkiso` under ovarium. This is the largest part of that it do.
* create the ISO

There are not reasons, to generate an ISO who when is installed is not reproductive or, reproducing it cannot be installed. If this case exists it's a bug, long to discover - we must remaster and install twice -  but again a bug to solve.

Your original system, when is remastered using eggs - is installed correctly or not?

My idea is: there is something broken on your system, but - of course - i just suppose and don't know that distro are you using, that eggs versione and so on.

**Comment by jon-bit** [comment]
linux mint. I'm a mint user. my bad.

**Comment by jon-bit** [comment]
WOW! I'M DUMB! I'M SO DUMB! I'M A PROFESSIONAL MORON!
![image](https://github.com/user-attachments/assets/4ae256d4-36fd-490f-8b73-cf8206b57fae)

I forgot to run the PREREQUISITES script for Ubuntu. Closing due to my amazing stupidity.

**Comment by pieroproietti** [comment]
That's app? I hope all fine..  

And I think you solved and find same stupid error...  

anyway, you did experience!.

Stay up, and happy hacking!
