### ISSUE TITLE
Error booting Arch-based ISO

### ISSUE THREAD

**Issue by J-create-bit** [pieroproietti/penguins-eggs-legacy#433]
Hello everybody,

I have a virtual machine with Arch Linux and XFCE to which I installed Penguins' Eggs with get-eggs. At first I had some errors but I managed to fix them. When making an egg with `sudo eggs produce `(with the --max setting) and booting the ISO, I get: 

`end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)`

Screenshot:

![image](https://github.com/user-attachments/assets/2a31d379-f61a-4ed9-bac7-297657cc069b)

The system I did an egg on is Arch with the Zen Kernel. I think the bug might be using the Zen Kernel, but I don't know. Thanks in advance for your help.

**Comment by pieroproietti** [comment]
Hi @J-create-bit 

I normally don't use Zen Kernel, but I think is possible.

If you have a recent version of eggs, try to create the ISO using the command: `eggs love`

This is just a script who do the following things:
* `sudo eggs kill`
* `sudo eggs dad -d`
* `sudo eggs tools clean`
* `sudo eggs produce --pendrive --addons adapt`

You can also run this command in sequence, it's the same.

Here is important the second command: `sudo eggs dad -d` who make eggs configuration, detecting the kernel in use.

It's important to put the current kernel on the configuration `/etc/penguins-eggs.d/eggs.yaml` to have the system working.

I hope this help

**Comment by pieroproietti** [comment]
I did a test with kernel zen, it seem to go.

![eggs-love](https://github.com/user-attachments/assets/d20a0ddb-4cb1-4764-bd56-60d0261116ea)

This is the reinstalled system, command: `eggs status`

![reinstalled](https://github.com/user-attachments/assets/f980b1e6-cb6f-43be-b728-ac90a681067e)

**Comment by pieroproietti** [comment]
![reinstalled](https://github.com/user-attachments/assets/f980b1e6-cb6f-43be-b728-ac90a681067e)

**Comment by J-create-bit** [comment]
Hi!
I tried the command and it worked, I managed to boot the ISO image. Thank you very much! Penguins' Eggs has helped me a lot and I have to thank you for how awesome it is and how easy it makes everything. 
Best regards and thanks for your help
