### ISSUE TITLE
upgrade from 7.8.10 to 7.8.35 fails on Ufficio Zero versions

### ISSUE THREAD

**Issue by redflegias** [pieroproietti/penguins-eggs-legacy#46]
Hi Piero,

on our Siena/Vieste/Tropea version if we try to install eggs 7.8.35 with deb file on an existing eggs version (7.8.10) we have this error:

(Reading database ... 
(Reading database ... 5%%
(Reading database ... 10%%
(Reading database ... 15%%
(Reading database ... 20%%
(Reading database ... 25%%
(Reading database ... 30%%
(Reading database ... 35%%
(Reading database ... 40%%
(Reading database ... 45%%
(Reading database ... 50%%
(Reading database ... 55%%
(Reading database ... 60%%
(Reading database ... 65%%
(Reading database ... 70%%
(Reading database ... 75%%
(Reading database ... 80%%
(Reading database ... 85%%
(Reading database ... 90%%
(Reading database ... 95%%
(Reading database ... 100%%
(Reading database ... 406332 files and directories currently installed.)
Preparing to unpack .../eggs_7.8.35-1_amd64.deb ...
Unpacking eggs (7.8.35-1) over (7.6.57-1) ...
dpkg: error processing archive /home/pippo/Scaricati/eggs_7.8.35-1_amd64.deb (--install):
 unable to open '/usr/lib/penguins-eggs/conf/distros/buster/calamares/calamares-modules/bootloader-config/bootloader-config.sh.dpkg-new': No such file or directory
Errors were encountered while processing:
 /home/pippo/Scaricati/eggs_7.8.35-1_amd64.deb

We know the basket function to update eggs but we have our repository so if we try to upgrade eggs with dpkg command the system fails to install the new version, so we want to release a new eggs version on repository but if we do that, users may have this error.

Can you help us, please?

Thx a lot,
Cheers,
Julian

**Comment by pieroproietti** [comment]
Try to remove eggs first: sudo apt remove eggs sudo d pkg -i eggs-7.8.36-2.deb

**Comment by redflegias** [comment]
Hi Piero,

it works if I remove old version on various versions but with a repository I can't remove old eggs deb version but only update eggs version on it with a newest version of eggs. 
Your deb must have some instructions to clean the previous version and old pathes and install a new, so a new eggs deb version can works fine also on remote repositories.

Julian

**Comment by redflegias** [comment]
Hi Piero,

just an info for your.

If we remove the old version form our system we must delete all these files, pathes etc that remain:

apt purge calamares eggs
rm -rf /etc/calamares/
rm -rf /etc/penguins-eggs.d/
rm -rf /usr/local/share/penguins-eggs/
rm -rf /usr/lib/calamares/
rm -f /etc/penguins-eggs.conf
rm -f /usr/share/applications/penguins-eggs-adapt.desktop
rm -f /usr/share/applications/penguins-eggs.desktop
rm -f /usr/share/applications/penguins-eggs-installer.desktop
rm -f /usr/bin/penguins-links-add.sh
rm -rf /usr/lib/penguins-eggs/

Can you predict to do that with preinstall deb instructions on new deb eggs file?
Thx a lot

Julian

**Comment by pieroproietti** [comment]
Hi Julian,

I use oclif and oclif-dev to generate deb package, oclif is a framework for building CLIs in Node. 

oclif-dev pack CLI into debian package but don't have scripts for preinst, postinst, prerm and postrm.

To solve or alleviate that problem I wrote another package perrisbrewery who unpack the package deb, insert scripts for prerm, postrm, preinst and postinst. You can find that scripts in https://github.com/pieroproietti/penguins-eggs/tree/master/perrisbrewery/scripts.

Can you be so kind to get a look on them and eventually suggest to add or change something?

**Comment by redflegias** [comment]
Hi Piero,

ok.
Can you insert on various eggs deb packages these preinstall operations:

remove and purge the previous eggs' version for example: if you create eggs 7.8.40 preinstall instructions will remove 7.8.40-1 (39) deb version if present on a system.

Otherwise if you can, you main insert also these instructions in preinst file:

apt purge calamares eggs
rm -rf /etc/calamares/
rm -rf /etc/penguins-eggs.d/
rm -rf /usr/local/share/penguins-eggs/
rm -rf /usr/lib/calamares/
rm -f /etc/penguins-eggs.conf
rm -f /usr/share/applications/penguins-eggs-adapt.desktop
rm -f /usr/share/applications/penguins-eggs.desktop
rm -f /usr/share/applications/penguins-eggs-installer.desktop
rm -f /usr/bin/penguins-links-add.sh
rm -rf /usr/lib/penguins-eggs/

so after an iso file stribution is installed there is not problem to remove these.

With this we can deliver other newest eggs' version on our repositories without any problem.

Can you help us?

Thx a lot,
Cheers,
Julian

**Comment by redflegias** [comment]
Hi Piero,

we have solved it with our deb called deleteeggs that we deliver on our repo each time before deliver newest eggs' version, so deleteeggs remove the previous eggs and then we deliver the new version.
Our package has many controls and it's made from scratch.
If you're interested you can use our source packages from our sourceforge  here https://sourceforge.net/projects/ufficiozero/files/ in each distro source package folder.

Thx for all,
Julian

**Comment by pieroproietti** [comment]
Ok, thanx you and Adriano, I will take a look on it.

**Comment by pieroproietti** [comment]
I think the version 7.8.42 solve this problem. I just relesed it and need confirm. 

I made a lot of tests and changements lately to solve this problem. I can't remove calamares from install scripts. I see is going, expecially eggs --flag final who remove both eggs and calamares, but tested it mostly in Debian bullseye. 

Please take a look you or Adriano.

**Comment by pieroproietti** [comment]
Well, finally - after the last changements . we can close this issue. 

I tested on ufficiozero roma and ufficiozero siena without problems. Just want to advice you and Adriano who from the next release the produce flag --final will be changed in the most meaningful --release.

Thanx for collaboration.

**Comment by redflegias** [comment]
Hi Piero,

sorry for my delay... ok thx a lot, we'll try the new version asap ;)

Cheers,
Julian
