### ISSUE TITLE
"live" user password?

### ISSUE THREAD

**Issue by TerryLSR** [pieroproietti/penguins-eggs-legacy#77]
hi, when I use eggs to produce a image and then install my system , it has "live" user and need password to contiune. but I try to log in with the main user of my system with the main user password. but it do not works.  Do you some idea to solve this problem?
thanks

**Comment by pieroproietti** [comment]
Hi, welcome Terry

eggs create a live image allways with the user live. After - during the installation - calamares or krill create the user you choose. So this it is normal.

It is different if you choose to backup your system. In this case, if you install with krill (NOT with calamares) during the installation krill check for userdata presence. i described this in backup section on the users guide and restore users accounts and users data.

The default value for user_opt and his password are on /etc/penguins-eggs.d/eggs.yaml, but can be changed editing it or with sudo eggs dad.

This are defaults:
user_opt: live
user_opt_passwd: evolution
root_passwd: evolution

I hope this help.

PS: unfortunately Email replies do not support Markdown so I removed MD format here.

**Comment by TerryLSR** [comment]
ok, I see that. This tool is very useful. thanks~

**Comment by TerryLSR** [comment]
now I have anthor problem not about passwd, eggs can produce .iso file that size more than 4Gb. but when I generate it to copy to a usb key to boot my system, but it can not going to system but to initramfs. Some error just like the picture showed. 
![lADPD4PvNv0OxIzNA0bNBF4_1118_838](https://user-images.githubusercontent.com/33231393/127450374-bf42ea7b-0fdb-43dc-acfb-7309f24a3beb.jpg)
if iso file size is less than 4Gb，the usb key is working well. Do you have some suggestion?
thank you.

**Comment by pieroproietti** [comment]
Yes there are no problems to make iso more than 4GB. But I can't understand the problem just from this picture, can you put the results of the command: eggs info, like here?
![eggs-info](https://user-images.githubusercontent.com/958613/127508561-21847c11-2839-4f40-9863-daaf5843c8b7.png)

**Comment by TerryLSR** [comment]
eggs info
![image](https://user-images.githubusercontent.com/33231393/127586569-1546c1c5-e853-4950-8c32-ef6e42dae48f.png)
my system version is ubuntu20.04.
Thank you for your patient guidance.

**Comment by TerryLSR** [comment]
eggs info

![image](https://user-images.githubusercontent.com/33231393/127586868-83fb8d61-a436-447a-807a-0337679455cf.png)

my system version is ubuntu20.04.
Thank you for your patient guidance.

**Comment by pieroproietti** [comment]
As you can see, there are problems with dependencies, the red [KO] in figure. 

I think you must give:  ```sudo eggs config``` and accept the prerequisites installation. 

Due the fact you probably are in a GUI system, eggs will propose too to install [calamares](https://calamares.io/), a great GUI system installer. If you accept calamares will be installed and configurated for you.

After that, give ```eggs info``` again and check the red [KO] is converted to green [OK].

Well, at this point all must to be OK and you can produce again the iso: ```sudo eggs produce --fast``` will produce fastly the iso. 
If you want more compression - and time to wait - ```sudo eggs produce --max```

This is the automatically translated [penguin's eggs users guide](https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https://penguins-eggs.net/book/italiano), there is a recent [video](https://www.youtube.com/watch?v=cKSszLKUwxA) too, with english subtitles.

**Comment by TerryLSR** [comment]
now the dependencies is converted to OK, but the iso file more than 4GB is still no work. it also boot into initramfs.
But I notice that has a "Invalid regular expression" error in the top of picture. Maybe it can not work well was inflenced by the error when the iso file is more than 4GB?
![image](https://user-images.githubusercontent.com/33231393/127792302-5cf69215-145a-449d-a903-7939978b355c.png)

**Comment by TerryLSR** [comment]
now the dependencies is converted to OK, but the iso file more than 4GB is still no work. it also boot into initramfs.
But I notice that has a "Invalid regular expression" error in the top of picture. Maybe it can not work well was inflenced by the error when the iso file is more than 4GB?
![image](https://user-images.githubusercontent.com/33231393/127792730-5feac2c8-d4cf-43dd-8a93-27b83d063f2c.png)
