### ISSUE TITLE
ppa

### ISSUE THREAD

**Issue by SoftwareLiberoIMeP** [pieroproietti/penguins-eggs-legacy#83]
Hello
today trying to add the ppa (new installation with ubuntu mate 21.10)
curl -s --compressed "https://pieroproietti.github.io/penguins-eggs-ppa/KEY.gpg" | sudo apt-key add -
[sudo] user password: 
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
and obviously does not complete the operation
Package subsequently installed from deb and running without problems
Thanks

Translated with www.DeepL.com/Translator (free version)

**Comment by pieroproietti** [comment]
Thanx for the question Ugone, It work - except the warning  - and I leaved it old school. 

Anyway, You can use:

```wget -O- https://pieroproietti.github.io/penguins-eggs-ppa/KEY.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/penguins-eggs-ppa-keyring.gpg```

and edit the file /etc/aptt/source.d/penguins-eggs.net to:
```deb [signed-by=/usr/share/keyrings/penguins-eggs-ppa-keyring.gpg] https://pieroproietti.github.io/penguins-eggs-ppa ./```


**tested on neon-user20211021**

**Comment by pieroproietti** [comment]
## Help ##
Probably it is not so difficult to arrange a repository for eggs with all the supported architectures: amd64, i386, arm64 and armel, but I'm not able at the momenti, someone can help?

**Comment by pieroproietti** [comment]
OK, two days ago i restored penguins-eggs-ppa, today I add eggs-8.17.9 on it and work nicefully.
I will not add all the new versions of eggs to this repository, just the version more stable, if You want always try the most advanced versions You can download them on [sourceforge eggs page](https://sourceforge.net/projects/penguins-eggs/files/packages-deb/)
