### ISSUE TITLE
neon-user-20211028-132 

### ISSUE THREAD

**Issue by pieroproietti** [pieroproietti/penguins-eggs-legacy#84]
![neon-test](https://user-images.githubusercontent.com/958613/139593810-972a44da-1270-4bd9-80ec-c8f7da441d5e.png)
In my adventure to create an updated remastering tool compatible with the Debian, Ubuntu, Devuan world I’m running into the following problem:

I can remaster practically everything from Debian Jessie to bookworm and from Ubuntu bionic up to the development version jammy - instead, I can not and I have not understood why - to do the same with the latest version of neon with plasma-5.23.
I also report that the problem does not occur, however, with Kubuntu 21.10 impish with the beta of plasma-5.23 installed.
From a neon system installed, the ISO builds normally and is bootable, but when I go to boot from the liveCD obtained, the system does not come to show the monitor and moreover giving ALT-CTRL F2, F3, etc can not open the console.

Someone, could give me some clues or suggest me a way to debug?

**Comment by pieroproietti** [comment]
This is kubuntu 21.10 updated with the plasma-5.23
![kubuntu-login](https://user-images.githubusercontent.com/958613/139593925-4b9a5553-343b-4e9e-bed0-04b17be54623.png)

**Comment by behdanisohrab** [comment]
Hi 
I think the problem is related to the **Sddm** because  I tried remastering Debian sid with kde plasma 5.23 and the exact same black screen happend.

**Comment by pieroproietti** [comment]
I had the same problem in kde with neon, it's start with the october
edition of neon (basrd on ubuntu focal).

Today I was able to remaster it and reinstall removing live-config

try: sudo apt purge live-config

after, run sudo eggs produce

and when eggs ask to reinstall it, answer no and continue.

I today find this workaround for sddm. It work on neon and debian bullseye.

If you confirm, next day I will remove live-config in bullseye and focal.

Il gio 11 nov 2021, 13:10 سیستم عامل ایرانی bss ***@***.***>
ha scritto:

**Comment by behdanisohrab** [comment]
Thank you very much for your help🙏

**Comment by pieroproietti** [comment]
In the actual version of eggs I removed live-config package for bullseye, focal and next, so now remastered versions of neon work.
