### ISSUE TITLE
Penguin`s eggs books

### ISSUE THREAD

**Issue by behdanisohrab** [pieroproietti/penguins-eggs-legacy#86]
[](url)Hi
I recently made a remaster of debian gnu/linux 11 with Eggs
now how can i remove the Penguin`s eggs books from the live media?
![image](https://user-images.githubusercontent.com/72007820/141097474-e18eb549-bcd8-4594-a6e7-1341175d693e.png)

**Comment by pieroproietti** [comment]
Hi bsslinux, 

please leave it, it's just a link, and we need to spread! ;-)

In all the way you can remove it in this way, create your iso normally or with the option --script. After that:
* `cd /home/eggs`
* `sudo rm *.iso`
* `cd ovarium`
* `sudo rm iso/live/filesystem.squashfs `
* `sudo ./bind `
* `sudo rm filesystem.squashfs/etc/xdg/autostart/penguins-links-add.desktop `
* `sudo ./ubind`
* `sudo ./mksquashfs`
* `sudo ./mkisofs`
Now your iso with boot without the link!
![mksquashfs](https://user-images.githubusercontent.com/958613/141250808-deae1676-efd8-47c6-a1db-9eb49faa8f1d.png)
![mkiso](https://user-images.githubusercontent.com/958613/141250821-9f633e3a-49c6-41da-bbde-5a2e7e333de0.png)

**Comment by behdanisohrab** [comment]
Thank you very much for your help🙏
