### ISSUE TITLE
How do you do UEFI installer?

### ISSUE THREAD

**Issue by Crisespecial** [pieroproietti/penguins-eggs-legacy#87]
Problem with eggs i dont know if its my pc but i cannot install it using UEFI and the pc doesnt support legacy.

**Comment by pieroproietti** [comment]
Check the command ```eggs info``` and look if UEFI is green, if not, just: ```sudo apt install grub-efi-amd64-bin```, after that produce a new ISO and try again. I hope this can help.

**Comment by Crisespecial** [comment]
I already did the grub-efi-amd64 thingy and its green so im not gonna produce a new ISO. I use onworks.net so if it does not UEFI boot. Maybe is the computer.
Thanks anyways.
