### ISSUE TITLE
error code 23

### ISSUE THREAD

**Issue by behdanisohrab** [pieroproietti/penguins-eggs-legacy#90]
hi
i recently started to remastering ubuntu 20.04 lts
but i started to get error code 23
how can i fix that?
![image](https://user-images.githubusercontent.com/72007820/142461464-2f9643f3-b058-4b00-ad99-6e29d6c6dd9a.png)

**Comment by pieroproietti** [comment]
Hi bsslinux,  can you try: 

```sudo eggs produce --fast --verbose ```

to have more informations? Thanx

**Comment by behdanisohrab** [comment]
🙏🙏
