### ISSUE TITLE
Trying to boot from grub. get error: invalid magic number. 

### ISSUE THREAD

**Issue by un-simp** [pieroproietti/penguins-eggs-legacy#93]
Using default settings with prefix and username and password changed
getting error
error: invalid magic number
error: you must load the kernel first
no matter what i do (using a vm. ventoy or even flashing to a usb) i still get this error
help is greatly appreciated

**Comment by un-simp** [comment]
accidentally posted this but ill give details here
Using default settings with prefix and username and password changed
getting error
error: invalid magic number
error: you must load the kernel first
no matter what i do (using a vm. ventoy or even flashing to a usb) i still get this error
help is greatly appreciated

**Comment by pieroproietti** [comment]
Hi un-simp,,

I never had that error, but don't think it is strickly related to eggs. For sure it is not related to user, password or prefix changed.

**Comment by un-simp** [comment]
it is likely a issue in grub so i will try there. if not then im not sure what i did wrong. it might be an issue with my machine but i dunno

**Comment by un-simp** [comment]
yep was a grub issue. rebuilding the iso fixed it
